/** Lightweight local OpenEXR scanline decoder for browser HDRI loading.
 * Supports uncompressed, RLE, ZIPS and ZIP scanline EXR with UINT/HALF/FLOAT RGB(A)/Y.
 * PIZ/PXR24 and tiled/deep/multipart EXR intentionally fall through to the optional
 * hdrify network fallback in EnvironmentBridge.
 */
const MAGIC=20000630;
const NO=0,RLE=1,ZIPS=2,ZIP=3;
const td=new TextDecoder();
function cstring(bytes,state){const start=state.o;while(state.o<bytes.length&&bytes[state.o]!==0)state.o++;if(state.o>=bytes.length)throw new Error('Truncated EXR string.');const s=td.decode(bytes.subarray(start,state.o));state.o++;return s;}
const i32=(dv,o)=>dv.getInt32(o,true),u32=(dv,o)=>dv.getUint32(o,true);
function half(h){const s=(h&0x8000)?-1:1,e=(h>>>10)&31,m=h&1023;if(e===0)return s*Math.pow(2,-14)*(m/1024);if(e===31)return m?NaN:s*Infinity;return s*Math.pow(2,e-15)*(1+m/1024);}
function semantic(name){const n=name.toLowerCase().split('.').pop();if(n==='r'||n==='red')return'r';if(n==='g'||n==='green')return'g';if(n==='b'||n==='blue')return'b';if(n==='a'||n==='alpha')return'a';if(n==='y'||n==='l'||n==='luma'||n==='luminance')return'y';return n;}
function pixelBytes(type){if(type===0||type===2)return 4;if(type===1)return 2;throw new Error(`Unsupported EXR pixel type ${type}.`);}
function readValue(dv,o,type){if(type===0)return dv.getUint32(o,true);if(type===1)return half(dv.getUint16(o,true));return dv.getFloat32(o,true);}
function predictor(src){const size=src.length;if(size<2)return;if((size&1)===0)src[1]=(src[1]+(src[0]^0x80))&255;for(let i=2;i<size-1;i+=2){const a=(src[i-1]+src[i])&255;src[i]=a;src[i+1]=(src[i+1]+a)&255;src[i]=(a^0x80)&255;}}
function reorder(src){const out=new Uint8Array(src.length),halfSize=Math.floor(src.length/2),a=src.subarray(0,halfSize),b=src.subarray(halfSize,halfSize*2);for(let i=0;i<halfSize;i++){out[i*2]=a[i];out[i*2+1]=b[i];}if(src.length&1)out[src.length-1]=src[src.length-1];return out;}
function rleDecode(src,size){const out=new Uint8Array(size);let si=0,di=0;while(si<src.length&&di<size){const c=(src[si++]<<24)>>24;if(c<0){const n=-c;if(si+n>src.length)throw new Error('Truncated EXR RLE literal run.');out.set(src.subarray(si,si+n),di);si+=n;di+=n;}else{if(si>=src.length)throw new Error('Truncated EXR RLE repeat run.');const v=src[si++];for(let i=0;i<=c&&di<size;i++)out[di++]=v;}}if(di!==size)throw new Error(`EXR RLE size mismatch (${di}/${size}).`);predictor(out);return reorder(out);}
async function inflateZlib(src){if(typeof DecompressionStream==='undefined')throw new Error('This browser lacks DecompressionStream required for ZIP-compressed EXR.');let stream;try{stream=new Blob([src]).stream().pipeThrough(new DecompressionStream('deflate'));}catch(e){throw new Error(`Could not initialise EXR ZIP decompressor: ${e?.message||e}`);}const buf=await new Response(stream).arrayBuffer();const out=new Uint8Array(buf);predictor(out);return reorder(out);}
function parseHeader(buffer){const bytes=new Uint8Array(buffer),dv=new DataView(buffer);if(bytes.length<12||u32(dv,0)!==MAGIC)throw new Error('Not an OpenEXR file.');const version=u32(dv,4);if(version&0x00001000)throw new Error('Deep EXR is not supported.');if(version&0x00000800)throw new Error('Multipart EXR is not supported.');const st={o:8},attrs={};while(st.o<bytes.length){const name=cstring(bytes,st);if(!name)break;const type=cstring(bytes,st);if(st.o+4>bytes.length)throw new Error('Truncated EXR attribute.');const size=u32(dv,st.o);st.o+=4;if(st.o+size>bytes.length)throw new Error('Truncated EXR attribute payload.');attrs[name]={type,start:st.o,size};st.o+=size;}
 const dw=attrs.dataWindow;if(!dw||dw.size<16)throw new Error('EXR dataWindow is missing.');const xMin=i32(dv,dw.start),yMin=i32(dv,dw.start+4),xMax=i32(dv,dw.start+8),yMax=i32(dv,dw.start+12),width=xMax-xMin+1,height=yMax-yMin+1;if(width<1||height<1||width>30720||height>17280)throw new Error(`Unsafe EXR dimensions ${width}×${height}. Maximum supported EXR data window is 30720×17280.`);
 const ca=attrs.channels;if(!ca)throw new Error('EXR channel list is missing.');const cs={o:ca.start},end=ca.start+ca.size,channels=[];while(cs.o<end){const name=cstring(bytes,cs);if(!name)break;if(cs.o+16>end)throw new Error('Truncated EXR channel entry.');const pixelType=i32(dv,cs.o);cs.o+=4;const pLinear=bytes[cs.o];cs.o+=4;const xSampling=i32(dv,cs.o);cs.o+=4;const ySampling=i32(dv,cs.o);cs.o+=4;if(xSampling!==1||ySampling!==1)throw new Error('Subsampled EXR channels are not supported.');channels.push({name,semantic:semantic(name),pixelType,pLinear,bytes:pixelBytes(pixelType),xSampling,ySampling});}
 const compAttr=attrs.compression,compression=compAttr?bytes[compAttr.start]:NO;if(![NO,RLE,ZIPS,ZIP].includes(compression))throw new Error(`EXR compression ${compression} requires the extended decoder.`);const blockLines=compression===ZIP?16:1;return {bytes,dv,offset:st.o,width,height,xMin,yMin,xMax,yMax,channels,compression,blockLines};}
export async function decodeEXRLocal(buffer,{maxWidth=2048,maxHeight=1024}={}){const h=parseHeader(buffer),{bytes,dv,width,height,yMin,yMax,channels,compression,blockLines}=h;const hasRGB=['r','g','b'].every(k=>channels.some(c=>c.semantic===k)),hasY=channels.some(c=>c.semantic==='y');if(!hasRGB&&!hasY)throw new Error('EXR requires RGB channels or a luminance Y channel.');const blocks=Math.ceil(height/blockLines),tableBytes=blocks*8;if(h.offset+tableBytes>bytes.length)throw new Error('Truncated EXR scanline offset table.');const offsets=[];for(let i=0;i<blocks;i++){const v=Number(dv.getBigUint64(h.offset+i*8,true));if(!Number.isSafeInteger(v)||v<0||v+8>bytes.length)throw new Error('Invalid EXR scanline block offset.');offsets.push(v);}const scale=Math.min(1,maxWidth/width,maxHeight/height),outWidth=Math.max(1,Math.round(width*scale)),outHeight=Math.max(1,Math.round(height*scale)),rgba=new Float32Array(outWidth*outHeight*4);let peak=0;
 // Huge EXRs are decoded scanline-by-scanline directly into the bounded HDRI map.
 // This avoids allocating width*height*RGBA32F (8.5 GiB at the new maximum).
 const sourceYForDest=new Int32Array(outHeight);for(let y=0;y<outHeight;y++)sourceYForDest[y]=Math.max(0,Math.min(height-1,Math.floor((y+.5)*height/outHeight)));
 const destForSourceY=new Map();for(let y=0;y<outHeight;y++)destForSourceY.set(sourceYForDest[y],y);
 const sourceXForDest=new Int32Array(outWidth);for(let x=0;x<outWidth;x++)sourceXForDest[x]=Math.max(0,Math.min(width-1,Math.floor((x+.5)*width/outWidth)));
 for(const off of offsets){const firstY=i32(dv,off),packed=u32(dv,off+4),start=off+8;if(start+packed>bytes.length)throw new Error('Truncated EXR scanline block.');const lineCount=Math.max(0,Math.min(blockLines,yMax-firstY+1));if(!lineCount)continue;const bytesPerLine=channels.reduce((sum,c)=>sum+width*c.bytes,0),expected=bytesPerLine*lineCount;let raw;if(compression===NO){raw=bytes.subarray(start,start+packed);if(raw.length<expected)throw new Error('Truncated uncompressed EXR block.');}else if(compression===RLE)raw=rleDecode(bytes.subarray(start,start+packed),expected);else{raw=await inflateZlib(bytes.subarray(start,start+packed));if(raw.length<expected)throw new Error(`EXR ZIP block decoded to ${raw.length}, expected ${expected}.`);}const rdv=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);
  for(let li=0;li<lineCount;li++){const sy=firstY-yMin+li,dy=destForSourceY.get(sy);if(dy===undefined)continue;let channelBase=li*bytesPerLine;const channelOffsets={};for(const c of channels){channelOffsets[c.semantic]={base:channelBase,channel:c};channelBase+=width*c.bytes;}
   for(let dx=0;dx<outWidth;dx++){const sx=sourceXForDest[dx],read=(sem,def=0)=>{const entry=channelOffsets[sem];if(!entry)return def;const v=readValue(rdv,entry.base+sx*entry.channel.bytes,entry.channel.pixelType);return Number.isFinite(v)?Math.max(0,v):0;},yy=read('y',0),r=hasRGB?read('r',0):yy,g=hasRGB?read('g',0):yy,b=hasRGB?read('b',0):yy,a=read('a',1),o=(dy*outWidth+dx)*4;rgba[o]=r;rgba[o+1]=g;rgba[o+2]=b;rgba[o+3]=a;peak=Math.max(peak,r,g,b);}
  }
 }
 return {data:rgba,width:outWidth,height:outHeight,originalWidth:width,originalHeight:height,peak,compression,downsampled:outWidth!==width||outHeight!==height};}
