import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULTS} from '../src/core/parameters.js';
import {defaultPalettes,linearPalette} from '../src/core/lut.js';
import {planarField,sphereField,generateLinearFrame,modulatedSettings,waveValue,smoothFrame,temporalBlend,downsample,halfFloat,mipChain,resizeLinear} from '../src/environment/pattern.js';
import {decodeHDR} from '../src/environment/hdr.js';
import {decodeEXRLocal} from '../src/environment/exr.js';
import {makeGrid,makeSphere,cameraMatrix,normal} from '../src/core/math.js';
import {detailAtlas} from '../src/render/renderer.js';
const s={...DEFAULTS},lut=linearPalette(defaultPalettes()[0]);
test('four-wave reference vector at zero frequencies',()=>{const t=.71,z={...s,freqX:0,freqY:0,diagonal:0,radius:0};assert.ok(Math.abs(planarField(2,3,t,z)-(Math.sin(-1.2*t)+Math.sin(.6*t))/4)<1e-12);});
test('spherical longitude wraps and poles have no longitudinal seam',()=>{for(const v of [0,.2,.5,.9,1])assert.ok(Math.abs(sphereField(0,v,.3,s)-sphereField(1,v,.3,s))<1e-10);for(const u of [.1,.4,.8]){assert.ok(Math.abs(sphereField(0,0,.3,s)-sphereField(u,0,.3,s))<1e-10);assert.ok(Math.abs(sphereField(0,1,.3,s)-sphereField(u,1,.3,s))<1e-10);}});
test('generated maps carry nontrivial pattern variance and linear HDR above one',()=>{const frame=generateLinearFrame(96,48,.5,.2,s,lut);assert.equal(frame.length,96*48*4);let min=Infinity,max=0;for(let i=0;i<frame.length;i+=4){min=Math.min(min,frame[i]);max=Math.max(max,frame[i]);assert.equal(frame[i+3],1);assert.ok(Number.isFinite(frame[i]));}assert.ok(max>1);assert.ok(max-min>.8);});
test('smoothing preserves constant radiance, including seams and odd mip dimensions',()=>{const data=new Float32Array(10*5*4).fill(3);for(const v of smoothFrame(data,10,5,1))assert.equal(v,3);for(const v of resizeLinear(data,10,5,7,4))assert.ok(Math.abs(v-3)<1e-6);let {data:d,width,height}=downsample(data,10,5);assert.equal(width,5);assert.equal(height,2);for(const v of d)assert.ok(Math.abs(v-3)<1e-6);});
test('temporal smoothing is bounded and bypasses stale dimensions',()=>{const out=temporalBlend(new Float32Array([4,2]),new Float32Array([0,0]),.1,.2);assert.ok(out[0]>0&&out[0]<4);assert.deepEqual([...temporalBlend(new Float32Array([4]),new Float32Array([0,0]),.1,.2)],[4]);});
test('modulation is transient, signed and never mutates the base',()=>{const base={...s,modEnabled:true,modTargets:['freqX','speed'],modAmplitude:100,modHz:-1};const before=structuredClone(base),m=modulatedSettings(base,.25);assert.notEqual(m.settings.speed,base.speed);assert.deepEqual(base,before);assert.ok(m.output<=200&&m.output>=-200);});
test('waveforms are finite; periodic waves join exactly',()=>{for(const name of ['sine','smooth-triangle','loop-noise'])assert.ok(Math.abs(waveValue(name,0)-waveValue(name,1))<1e-10);for(const name of ['sine','smooth-triangle','loop-noise','wander-noise'])for(let i=-100;i<100;i++)assert.ok(Math.abs(waveValue(name,i*.031))<=1.000001);});
test('half-float packer reference values and bounded exceptional inputs',()=>{assert.equal(halfFloat(0),0);assert.equal(halfFloat(1),0x3C00);assert.equal(halfFloat(-2),0xC000);assert.equal(halfFloat(.5),0x3800);assert.equal(halfFloat(65504),0x7BFF);assert.equal(halfFloat(Infinity),0);assert.equal(halfFloat(1e20),0x7BFF);});
test('complete mip chain reaches 1x1 without allocating an upsampled source',()=>{const m=mipChain(generateLinearFrame(96,48,0,0,s,lut),96,48);assert.deepEqual(m.map(x=>[x.width,x.height]),[[96,48],[48,24],[24,12],[12,6],[6,3],[3,1],[1,1]]);assert.ok(m.every(x=>x.data instanceof Uint16Array));});
function hdr(w,h,modern=true){const head=new TextEncoder().encode(`#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n-Y ${h} +X ${w}\n`);const bytes=[...head];for(let y=0;y<h;y++){if(modern){bytes.push(2,2,w>>8,w&255);for(const c of [128,64,32,131]){bytes.push(w);for(let x=0;x<w;x++)bytes.push(c);}}else for(let x=0;x<w;x++)bytes.push(128,64,32,131);}return new Uint8Array(bytes);}
test('HDR reader decodes modern RLE into unclipped linear radiance',()=>{const a=decodeHDR(hdr(9,2));assert.equal(a.width,9);assert.equal(a.height,2);assert.deepEqual([...a.data.slice(0,4)],[4,2,1,1]);assert.equal(a.peak,4);});
test('HDR reader supports flat legacy RGBE',()=>{const a=decodeHDR(hdr(4,2,false));assert.deepEqual([...a.data.slice(0,4)],[4,2,1,1]);});
test('HDR truncation and corrupt runs reject rather than publish',()=>{const h=hdr(9,2);assert.throws(()=>decodeHDR(h.subarray(0,h.length-2)));const bad=h.slice();const index=new TextDecoder().decode(h).indexOf('-Y');assert.ok(index>=0);const start=new TextDecoder().decode(h).indexOf('\n',index)+1;bad[start+4]=0;assert.throws(()=>decodeHDR(bad),/zero/);});
test('HDR dimensions are rejected before pixel allocation',()=>{const h=new TextEncoder().encode('#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n-Y 100000 +X 100000\n');assert.throws(()=>decodeHDR(h),/cap/);});

function exrFixture(width=4,height=2){
 const chunks=[];const te=new TextEncoder();const push=(u)=>chunks.push(u);const cstr=s=>push(new Uint8Array([...te.encode(s),0]));const i32v=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setInt32(0,n,true);push(b);};const u32v=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n,true);push(b);};const f32v=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setFloat32(0,n,true);push(b);};
 const attr=(name,type,payload)=>{cstr(name);cstr(type);u32v(payload.length);push(payload);};
 const channelPayload=()=>{const a=[];const add=u=>a.push(...u);for(const name of ['R','G','B']){add([...te.encode(name),0]);const b=new Uint8Array(16),dv=new DataView(b.buffer);dv.setInt32(0,2,true);b[4]=0;dv.setInt32(8,1,true);dv.setInt32(12,1,true);add(b);}add([0]);return new Uint8Array(a);};
 const box=(x0,y0,x1,y1)=>{const b=new Uint8Array(16),dv=new DataView(b.buffer);[x0,y0,x1,y1].forEach((v,i)=>dv.setInt32(i*4,v,true));return b;};
 const magic=new Uint8Array(8),mdv=new DataView(magic.buffer);mdv.setUint32(0,20000630,true);mdv.setUint32(4,2,true);push(magic);
 attr('channels','chlist',channelPayload());attr('compression','compression',new Uint8Array([0]));attr('dataWindow','box2i',box(0,0,width-1,height-1));attr('displayWindow','box2i',box(0,0,width-1,height-1));attr('lineOrder','lineOrder',new Uint8Array([0]));const pa=new Uint8Array(4);new DataView(pa.buffer).setFloat32(0,1,true);attr('pixelAspectRatio','float',pa);attr('screenWindowCenter','v2f',new Uint8Array(8));const sw=new Uint8Array(4);new DataView(sw.buffer).setFloat32(0,1,true);attr('screenWindowWidth','float',sw);push(new Uint8Array([0]));
 let headerLength=chunks.reduce((n,c)=>n+c.length,0),blockSize=8+width*3*4,offset=headerLength+height*8;const table=new Uint8Array(height*8),tdv=new DataView(table.buffer);for(let y=0;y<height;y++){tdv.setBigUint64(y*8,BigInt(offset),true);offset+=blockSize;}push(table);
 for(let y=0;y<height;y++){const head=new Uint8Array(8),dv=new DataView(head.buffer);dv.setInt32(0,y,true);dv.setUint32(4,width*3*4,true);push(head);for(let c=0;c<3;c++){const line=new Uint8Array(width*4),ldv=new DataView(line.buffer);for(let x=0;x<width;x++){const value=c===0?2+x+y:c===1?1+x*.25:0.5+y*.5;ldv.setFloat32(x*4,value,true);}push(line);}}
 const total=chunks.reduce((n,c)=>n+c.length,0),out=new Uint8Array(total);let o=0;for(const c of chunks){out.set(c,o);o+=c.length;}return out;
}
test('local EXR decoder handles uncompressed float RGB scanlines without a network dependency',async()=>{const a=await decodeEXRLocal(exrFixture().buffer);assert.equal(a.width,4);assert.equal(a.height,2);assert.deepEqual([...a.data.slice(0,4)],[2,1,.5,1]);assert.ok(a.peak>=5);});
test('EXR decoder can downsample during decode while retaining original dimensions',async()=>{const a=await decodeEXRLocal(exrFixture().buffer,{maxWidth:2,maxHeight:1});assert.equal(a.width,2);assert.equal(a.height,1);assert.equal(a.originalWidth,4);assert.equal(a.originalHeight,2);assert.equal(a.downsampled,true);assert.equal(a.data.length,8);});
test('grid has valid indices, dense near-field sampling and bounded allocations',()=>{const g=makeGrid(128);assert.equal(g.vertices,16384);assert.equal(g.triangles,2*127*127);for(const i of g.indices)assert.ok(i<g.vertices);const d=g.data,spacingCenter=d[64*5]-d[63*5],spacingEdge=d[5]-d[0];assert.ok(spacingCenter<spacingEdge);assert.throws(()=>makeGrid(2048));});
test('sphere geometry contains finite unit vectors and valid indices',()=>{const g=makeSphere(32);for(let i=0;i<g.data.length;i+=5)assert.ok(Math.abs(Math.hypot(g.data[i],g.data[i+1],g.data[i+2])-1)<1e-6);for(const i of g.indices)assert.ok(i<g.vertices);});
test('view/projection matrix is finite at default poses',()=>{for(const p of [[0,12,0],[180,40,180]]){const m=cameraMatrix(p,normal([.7,-.2,.7]),16/9);assert.ok([...m.matrix].every(Number.isFinite));}});
test('detail texture is precomputed once and mipmapped',()=>{const a=detailAtlas(32);assert.equal(a[0].data.length,32*32*4);assert.deepEqual([a.at(-1).width,a.at(-1).height],[1,1]);});
