import {CHOICES,DEFAULTS,PARAMETERS} from '../core/parameters.js';
import {KINETIC_GROUPS,KINETIC_GROUP_KEYS,KINETIC_BOOLEAN_KEYS,KINETIC_COLOR_KEYS,kineticPanelKeys} from '../core/kinetic-parameters.js';
import {KINETIC_DEMOS} from '../core/kinetic-presets.js';
const $=id=>document.getElementById(id),labels={depth:'DEPTH',temporal:'TEMPORAL',volume:'XENOVOLUME',compositor:'COMPOSITOR',aa:'AA / FILTER',performance:'PERFORMANCE'};
const names={msaa:'Native MSAA',ssaaArea:'SSAA pixel area',temporalSamples:'Temporal samples',volumeRenderScale:'Ray resolution',volumeResolution:'Cache dimension',volumeSpace:'Placement',volumeSteps:'Primary ray steps',textureFilter:'Surface filtering',kineticDebug:'Debug view',volumeInterpolation:'Voxel sampling',volumeInterpolate:'Interpolate generations',volumeTemporal:'Reconstruct sparse rays',volumeUseMask:'Route mask into density',feedbackDepthReject:'Feedback depth guard',depthPyramidEnabled:'Enable depth pyramid',volumeDepthClip:'Clip against scene',distortionDepthGuard:'Protect foreground edges',bloomResolution:'Bloom resolution',feedbackResolution:'Feedback resolution',volumeDitherType:'Dither source',volumeMicroSource:'Fine-detail source',downsampleFilter:'Downsample filter'};
const help={msaa:'Native scene samples: off (1×) or 4×. Compositing depth stays single-sampled.',ssaaArea:'Total pixel area, not the multiplier on each axis. 8× means about 2.828× width and height before bounds.',temporalSamples:'Deterministic camera jitter with independent conservative history. One new sample per frame; not 32 samples in one frame.',textureFilter:'Applies to selected derivative-aware 2D surface detail, not explicit-LOD environment or volume reads. AF32 is a manual experimental 32-tap path.',volumeSpace:'Surface/mesh-normal shells use visible SceneAux depth, not a closed mesh SDF. Infinite mode tiles within a finite ray range.',volumeLighting:'Gradient and short marches run in the voxel cache; mip shadow builds a density pyramid. Live light march is explicitly expensive.',volumeTemporal:'Bilateral upsample plus independent depth-reprojected, clamped volume history. Dynamic fields use change rejection, not motion vectors.',volumeUseMask:'Shared router drives density at cache updates. Current depth and previous-frame volume/history prevent cyclic read/write hazards.',kineticDebug:'Inspect the actual graph surfaces. A disabled producer is neutral; selecting a view does not secretly enable expensive effects.',feedbackEnabled:'A separate destructive HDR history. It does not write into the conservative antialiasing history.'};
const pretty=key=>names[key]||key.replace(/^(volume|depth|feedback|distortion|positive|dark|colour|temporal)/,'$1 ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,s=>s.toUpperCase());
const optionLabel=(key,value)=>key==='msaa'?(value==='1'?'OFF / 1×':'4× NATIVE'):key==='ssaaArea'?`${value}× AREA`:key==='volumeResolution'?`${value}³${value==='96'?' EXPERIMENTAL':''}`:key==='volumeRenderScale'||key==='feedbackResolution'||key==='bloomResolution'?(value==='1'?'FULL':`1/${value} EACH AXIS`):value==='manual32'?'AF32 — MANUAL / EXPERIMENTAL':value==='live-march-experimental'?'LIVE LIGHT MARCH — EXPENSIVE':value.replaceAll('-',' ').toUpperCase();
function el(tag,attrs={},text){const n=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,v);}if(text)n.textContent=text;return n;}
export function mountKineticUI(app){
 const store=app.store,dock=el('section',{id:'kineticDock',class:'kinetic-dock hidden','aria-label':'Kinetic compositor controls'});
 const title=el('header',{class:'kinetic-title'}),name=el('b',{},'XENOFIELD / KINETIC 4.4b'),close=el('button',{type:'button','aria-label':'Close kinetic controls'},'×');title.append(name,close);dock.append(title);
 const tools=el('div',{class:'kinetic-tools'}),demo=el('select',{'aria-label':'Kinetic demonstration preset'});for(const [key,d] of Object.entries(KINETIC_DEMOS)){const o=el('option',{value:key},key);o.title=d.description;demo.append(o);}const load=el('button',{type:'button'},'LOAD STACK'),reset=el('button',{type:'button','data-tip':'Invalidate all conservative and kinetic histories without changing settings.'},'CLEAR HISTORY'),off=el('button',{type:'button','data-tip':'Disable the seven artistic layers and all temporal accumulation. Keep scene settings and independent spatial AA choices.'},'FX OFF');tools.append(demo,load,reset,off);dock.append(tools);
 load.onclick=()=>{try{store.applyGlobalStack(demo.value);}catch(e){app.notify(e.message);}};reset.onclick=()=>{const g=app.renderer?.kinetic;g?.temporal?.reset(null,'user clear');if(g){g.historyValid=false;g.previousImageValid=false;}};
 off.onclick=()=>store.patch({volumeEnabled:false,depthEnabled:false,distortionEnabled:false,feedbackEnabled:false,positiveEnabled:false,darkEnabled:false,colourEnabled:false,temporalEnabled:false,temporalSamples:'off',kineticDebug:'final',maskEnabled:false},'kinetic-off');
 const tabs=el('nav',{class:'kinetic-tabs','aria-label':'Kinetic modules'}),body=el('div',{class:'kinetic-body'}),controls=new Map();dock.append(tabs,body);
 for(const group of KINETIC_GROUPS){const tab=el('button',{type:'button','data-kinetic-tab':group},labels[group]),page=el('div',{'data-kinetic-page':group,class:'kinetic-page'});tabs.append(tab);body.append(page);
  const presets=el('div',{class:'panel-preset','data-panel-preset':group});presets.append(el('b',{},'PRESET'),el('button',{type:'button',class:'lock-toggle','data-submenu-lock':`kinetic-${group}`},'OFF'),el('select',{id:`preset-${group}`,'aria-label':`${labels[group]} preset`}),el('button',{'data-panel-load':group},'LOAD'),el('button',{'data-panel-save':group},'SAVE'),el('button',{'data-panel-delete':group},'−'));page.append(presets);
  const choices=el('div',{class:'kinetic-choices'});page.append(choices);
  for(const key of KINETIC_GROUP_KEYS[group]){
   const row=el('label',{class:'kinetic-choice','data-kinetic-key':key}),label=el('span',{},pretty(key));row.dataset.tip=help[key]||`${pretty(key)}. Saved with this module and global/project presets.`;let input;
   if(KINETIC_BOOLEAN_KEYS.includes(key)){input=el('input',{id:key,type:'checkbox'});input.onchange=()=>store.set(key,input.checked);row.classList.add('kinetic-toggle');}
   else if(KINETIC_COLOR_KEYS.includes(key)){input=el('input',{id:key,type:'color'});input.onchange=()=>store.set(key,input.value.slice(1));}
   else {input=el('select',{id:key});for(const v of CHOICES[key]||[]){input.append(el('option',{value:v},optionLabel(key,v)));}input.onchange=()=>store.set(key,input.value);}
   input.setAttribute('aria-label',pretty(key));input.dataset.tip=row.dataset.tip;row.append(label,input);choices.append(row);controls.set(key,input);
  }
  if(group==='aa'){
   for(const key of ['temporalSamples','jitterPattern']){const row=el('label',{class:'kinetic-choice'}),input=el('select',{id:`aa-${key}`,'aria-label':pretty(key)});row.append(el('span',{},pretty(key)),input);for(const v of CHOICES[key])input.append(el('option',{value:v},optionLabel(key,v)));input.onchange=()=>store.set(key,input.value);choices.append(row);controls.set(`aa-${key}`,input);}
   page.append(el('p',{class:'kinetic-note'},'MSAA / SSAA / temporal budgets are independent. The meter reports actual dimensions after device and memory bounds.'));
  }
  const bank=el('div',{id:`kinetic-${group}-controls`,class:'kinetic-params'});page.append(bank);
  if(group==='performance'){page.append(el('pre',{id:'kineticTimings',class:'kinetic-timings'},'Start the renderer to inspect pass timings.'));}
  tab.onclick=()=>{for(const b of tabs.children)b.classList.toggle('active',b===tab);for(const p of body.children)p.classList.toggle('active',p===page);dock.dataset.tab=group;};if(group==='volume')tab.click();
 }
 const meter=el('div',{id:'kineticMeter',class:'kinetic-meter'},'V4.4b · optional passes are off until enabled.');dock.append(meter);$('workspace').append(dock);
 const toggle=el('button',{id:'openKinetic',type:'button','data-tip':'Open depth, XenoVolume, temporal, compositor, AA and performance controls.'},'KINETIC 4.4b');$('dock').append(toggle);toggle.onclick=()=>{dock.classList.toggle('hidden');toggle.setAttribute('aria-pressed',String(!dock.classList.contains('hidden')));};close.onclick=()=>{dock.classList.add('hidden');toggle.setAttribute('aria-pressed','false');};
 let drag=null;title.onpointerdown=e=>{if(e.button!==0||e.target.closest('button'))return;const r=dock.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};title.setPointerCapture(e.pointerId);e.preventDefault();};title.onpointermove=e=>{if(!drag)return;dock.style.right='auto';dock.style.left=`${Math.max(0,Math.min(innerWidth-dock.offsetWidth,drag.left+e.clientX-drag.x))}px`;dock.style.top=`${Math.max(34,Math.min(innerHeight-100,drag.top+e.clientY-drag.y))}px`;};title.onpointerup=title.onpointercancel=()=>{drag=null;};dock.addEventListener('pointerdown',()=>{app.keyboardOwner='kinetic';app.cameraKeys?.clear();});
 const sync=()=>{for(const [id,input]of controls){const key=id.replace(/^aa-/,''),v=store.settings[key];if(document.activeElement===input)continue;if(input.type==='checkbox')input.checked=v;else input.value=input.type==='color'?'#'+v:v;}if(Object.hasOwn(KINETIC_DEMOS,store.globalStackName))demo.value=store.globalStackName;};store.addEventListener('change',sync);sync();
 let last=0;function update(){const now=performance.now();if(now-last<500)return;last=now;const r=app.renderer;if(!r?.ready)return;const m=r.metrics(),q=m.quality||{},g=m.kinetic||{},v=g.volume||{},hist=g.historyTracks||{};meter.textContent=`${m.renderSize?.join('×')} → ${m.outputSize?.join('×')} | SSAA ${Number(q.effectiveSSAA||1).toFixed(2)}×${q.limited?' BOUNDED':''} | MSAA ${q.msaa||1}× | T${store.settings.temporalSamples} | ≈${(q.estimatedBytes/1048576).toFixed(0)} MiB`;
   const timings=$('kineticTimings');if(!timings)return;const lines=[`ALLOCATIONS ≈${(q.estimatedBytes/1048576).toFixed(1)} MiB / ${store.settings.textureBudgetMB} MiB budget (estimate)`,`VOLUME ${v.cache?.[0]||'off'}³ / ${v.format||'—'} / ${v.framebuffer?.join('×')||'—'} ray target`,`CADENCE density ${store.settings.volumeDensityFPS} Hz / light ${store.settings.volumeLightFPS} Hz / ${store.settings.volumeSteps} rays`,`HISTORIES ${Object.entries(hist).map(([k,t])=>`${k}:${t.size.join('×')} age${t.age}`).join(' · ')||'none'}`,`RESET ${g.lastHistoryReset||'none'}`,''];
   if(m.gpuTimingsSupported){const measured=m.gpuTimingsMs||{},activity=g.timingActivity||{},keys=[...new Set([...Object.keys(measured),...Object.keys(activity)])];lines.push('GPU TIMINGS / sparse samples; idle stages have no current work');let sum=0;for(const key of keys){const value=measured[key],idle=Object.hasOwn(activity,key)&&!activity[key];if(!idle&&Number.isFinite(value))sum+=value;lines.push(`${key.replace(/^gpu/,'').replace(/Ms$/,'').padEnd(22)} ${idle?'idle':Number.isFinite(value)?value.toFixed(3)+' ms':'not sampled'}`);}lines.push(`ACTIVE PROFILED SUM   ${sum.toFixed(3)} ms (not frame wall time)`);}else lines.push('GPU TIMESTAMPS UNAVAILABLE — no estimated milliseconds shown.');
   lines.push('',`THIS FRAME ${Object.entries(g.passes||{}).map(([k,n])=>`${k} ×${n}`).join(' / ')||'base scene only'}`);for(const [k,error]of Object.entries(g.errors||{}))lines.push(`DISABLED ${k}: ${error}`);timings.textContent=lines.join('\n');
 }
 return {update,containers:Object.fromEntries(KINETIC_GROUPS.map(group=>[group,`kinetic-${group}-controls`])),finishControls(){
   // Collapse advanced volume editing into small parameter banks instead of one very tall panel.
   for(const group of ['volume','temporal','compositor']){const bank=$(`kinetic-${group}-controls`),rows=[...bank.children];if(rows.length<15)continue;const sections=group==='volume'?{CORE:/^volume(Density|Coverage|Threshold|Softness|Scale|Detail|Warp|Power|Amount)$/,CACHE:/FPS$|LightSteps|Attenuation/,CELLS:/Quantize|Dropout|Dither|PhaseSpeed|Posterize|Slices|StepQuantize|CellEdges/,LIGHT:/Emission|Absorption|Rim|Environment|Ambient/,SPACE:/Offset|Thickness|Size|Range|DepthSoftness/,MOTION:/Phase$|Speed$|SourceMix|Micro|TemporalWeight/}:group==='temporal'?{STABLE:/^temporal|^jitter/,FEEDBACK:/^feedback/}:{DISTORTION:/^distortion/,BLOOM:/^positive|^dark/,COLOUR:/^colour/};const nav=el('div',{class:'kinetic-subtabs'}),groups=el('div',{class:'kinetic-subpages'});bank.before(nav);bank.replaceWith(groups);const pages=[];for(const [name,regex] of Object.entries(sections)){const b=el('button',{type:'button'},name),p=el('div',{class:'kinetic-params kinetic-subpage'});for(const row of rows)if(!row.dataset.placed&&regex.test(row.dataset.parameter)){row.dataset.placed='1';p.append(row);}if(!p.children.length)continue;nav.append(b);groups.append(p);pages.push([b,p]);b.onclick=()=>{for(const [x,y]of pages){x.classList.toggle('active',x===b);y.classList.toggle('active',y===p);}};}const leftovers=rows.filter(x=>!x.dataset.placed);if(leftovers.length)pages[0][1].append(...leftovers);
   const routes=group==='volume'?{volumeSource:'CORE',volumeSourceB:'CORE',volumeGeneratorBlend:'CORE',volumeShape:'CORE',volumeInvert:'CORE',volumeUseMask:'CORE',volumeMask:'CORE',volumeInterpolate:'CACHE',volumeTemporal:'CACHE',volumeInterpolation:'CELLS',volumeDitherType:'CELLS',volumeLighting:'LIGHT',volumeColor:'LIGHT',volumeLightColor:'LIGHT',volumeDepthClip:'SPACE',volumeMicroSource:'MOTION'}:group==='temporal'?{feedbackDepthReject:'FEEDBACK',feedbackBlend:'FEEDBACK',feedbackResolution:'FEEDBACK',feedbackMask:'FEEDBACK'}:{distortionDepthGuard:'DISTORTION',distortionSource:'DISTORTION',distortionMask:'DISTORTION',positiveMask:'BLOOM',darkMask:'BLOOM',bloomResolution:'BLOOM',colourMask:'COLOUR'};
   const choiceBanks=new Map();for(const [key,name] of Object.entries(routes)){const page=pages.find(([b])=>b.textContent===name)?.[1],row=dock.querySelector(`[data-kinetic-key="${key}"]`);if(!page||!row)continue;let choices=choiceBanks.get(name);if(!choices){choices=el('div',{class:'kinetic-choices kinetic-subchoices'});page.prepend(choices);choiceBanks.set(name,choices);}choices.append(row);}
   pages[0]?.[0].click();}
 }};
}
