import {mountKineticUI} from './kinetic-ui.js';
import {mountProceduralCloudUI} from './procedural-cloud-ui.js';
import {PARAMETERS,DEFAULTS,BLEND_MODE_GROUPS,MASK_SOURCES,MASK_MIX_MODES,PROJECTION_MAPPINGS,PROJECTION_LAYER_CHOICES,PROJECTION_MASKS,PROJECTION_REFLECTION_CHOICES,PROJECTION_WRAP_MODES,validateSafetyCaps,validateRange,parseFunctionalExtremum} from '../core/parameters.js';
import {GLOBAL_PRESETS,PANEL_IDS,PANEL_DEFINITIONS,BUILTIN_PANEL_PRESETS,PATTERN_KEYS} from '../core/presets.js';
import {hexRGB,seeded} from '../core/lut.js';
import {installLUTEditor} from './lut-editor.js';
const $=id=>document.getElementById(id),fmt=n=>Number.isInteger(n)?String(n):Number(Number(n).toFixed(4)).toString(),editable=t=>!!t?.closest?.('input,select,textarea,[contenteditable=true]');
export function download(name,text,type='application/json'){const blob=text instanceof Blob?text:new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function installUI(app){
 const store=app.store,rows=new Map(),windows=[['skysynth','SKYSYNTH'],['surface','SURFACE'],['lut','LUT']];let z=10,rangeKey='',allHidden=false,latches=0,pointerDrag=null,yResize=null;const held=new Map(),randomHistory=[];let anchor={};app.keyboardOwner='camera';app.cameraKeys=new Set();const notify=m=>app.notify(m);const kineticUI=mountKineticUI(app);const cloudUI=mountProceduralCloudUI(app);
 let previewEnabled=true;function setPreviewEnabled(enabled){previewEnabled=!!enabled;const wrap=$('previewWrap');if(wrap)wrap.classList.toggle('preview-disabled',!previewEnabled);if($('envPreview'))$('envPreview').setAttribute('aria-hidden',String(!previewEnabled));}
 const clearHeld=()=>{for(const v of held.values()){clearTimeout(v.delay);clearInterval(v.interval);}held.clear();document.querySelectorAll('.key-held').forEach(e=>e.classList.remove('key-held'));app.cameraKeys.clear();},front=el=>el.style.zIndex=String(++z);
 function clampWindow(el){const bar=$('mainbar').getBoundingClientRect(),left=Math.max(6,Math.min(parseFloat(el.style.left)||8,innerWidth-el.offsetWidth-6)),top=Math.max(bar.bottom+6,Math.min(parseFloat(el.style.top)||bar.bottom+8,innerHeight-50));el.style.left=left+'px';el.style.top=top+'px';}
 function updateDock(){for(const [id] of windows){const b=document.querySelector(`[data-restore="${id}"]`);if(b)b.dataset.open=String(!$(id).classList.contains('hidden'));}}
 function closeSides(except=''){for(const id of ['modulation','skynoixture','skymixer','maskpanel'])if(id!==except)$(id).classList.add('hidden');}
 function toggleSide(id){const p=$(id),open=!p.classList.contains('hidden');closeSides();p.classList.toggle('hidden',open);front($('skysynth'));}
 function layout(){clearHeld();closeSides();const narrow=innerWidth<960,top=$('mainbar').getBoundingClientRect().bottom+8,coords={skysynth:[10,top],surface:[Math.max(10,innerWidth-470),top],lut:[Math.max(8,(innerWidth-940)/2),Math.max(top,(innerHeight-650)/2)]};for(const [id] of windows){const el=$(id);el.style.left=coords[id][0]+'px';el.style.top=coords[id][1]+'px';const width=id==='lut'?Math.min(940,innerWidth-16):(id==='skysynth'?390:460);el.style.width=width+'px';el.style.height=(id==='lut'?Math.min(650,innerHeight-top-8):Math.min(720,innerHeight-top-8))+'px';el.classList.toggle('hidden',id==='lut'||(narrow&&id==='surface'));front(el);clampWindow(el);}allHidden=false;updateDock();}
 for(const [id,label] of windows){const b=document.createElement('button');b.textContent=label;b.dataset.restore=id;b.onclick=()=>{$(id).classList.toggle('hidden');front($(id));clampWindow($(id));updateDock();};$('dock').append(b);const el=$(id);el.querySelector('[data-minimize]')?.addEventListener('click',()=>{el.classList.add('hidden');closeSides();updateDock();});el.addEventListener('pointerdown',()=>{front(el);app.keyboardOwner=id;},true);el.querySelector('.titlebar')?.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,select,label,[role=toolbar]'))return;pointerDrag={id,x:e.clientX,y:e.clientY,left:parseFloat(el.style.left),top:parseFloat(el.style.top)};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();});}
 for(const [handle,id,minH] of [['skyYResize','skysynth',350],['surfaceYResize','surface',260]])$(handle)?.addEventListener('pointerdown',e=>{if(e.button!==0)return;yResize={id,minH,y:e.clientY,h:$(id).getBoundingClientRect().height};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();});window.addEventListener('pointermove',e=>{if(yResize){const el=$(yResize.id),max=innerHeight-el.getBoundingClientRect().top-8;el.style.height=Math.max(yResize.minH,Math.min(max,yResize.h+e.clientY-yResize.y))+'px';return;}if(pointerDrag){const d=pointerDrag,el=$(d.id);el.style.left=d.left+e.clientX-d.x+'px';el.style.top=d.top+e.clientY-d.y+'px';clampWindow(el);}});window.addEventListener('pointerup',()=>{pointerDrag=null;yResize=null;clearHeld();});window.addEventListener('pointercancel',()=>{pointerDrag=null;yResize=null;clearHeld();});window.addEventListener('blur',clearHeld);window.addEventListener('resize',()=>windows.forEach(([id])=>clampWindow($(id))));
 $('layoutReset').onclick=layout;$('hidePanels').onclick=()=>{allHidden=!allHidden;for(const [id] of windows)$(id).classList.toggle('hidden',allHidden||(id==='lut'));if(allHidden){closeSides();$('kineticDock')?.classList.add('hidden');}updateDock();};$('fullscreen').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await $('workspace').requestFullscreen();}catch(e){notify(e.message);}};
 $('openModulation').onclick=()=>toggleSide('modulation');$('openNoixture').onclick=()=>toggleSide('skynoixture');$('openMixer').onclick=()=>toggleSide('skymixer');$('openMask').onclick=()=>toggleSide('maskpanel');document.querySelectorAll('[data-side-close]').forEach(b=>b.onclick=()=>$(b.dataset.sideClose).classList.add('hidden'));
 document.querySelectorAll('#liquidTabs [data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('#liquidTabs [data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-tab-page]').forEach(x=>x.classList.toggle('active',x.dataset.tabPage===b.dataset.tab));});

 function populateBlend(select){select.innerHTML='';for(const [group,modes] of BLEND_MODE_GROUPS){const g=document.createElement('optgroup');g.label=group;for(const [value,label] of modes){const o=document.createElement('option');o.value=value;o.textContent=label.toUpperCase();g.append(o);}select.append(g);}}document.querySelectorAll('[data-blend-select]').forEach(populateBlend);
 const maskLabels={'constant':'CONSTANT WHITE','skysynth-luma':'SKYSYNTH LUMA','hdri-luma':'HDRI LUMA','mixed-luma':'MIXED ENV LUMA','noixture':'NOIXTURE','clouds':'CLOUDS','perlin':'PERLIN','billow':'BILLOW','ridge':'RIDGE','weave':'WEAVE','vertical':'VERTICAL','radial':'RADIAL'};for(const id of ['maskSourceA','maskSourceB'])for(const v of MASK_SOURCES){const o=document.createElement('option');o.value=v;o.textContent=maskLabels[v]||v.toUpperCase();$(id).append(o);}for(const v of MASK_MIX_MODES){const o=document.createElement('option');o.value=v;o.textContent=v.toUpperCase();$('maskMixMode').append(o);}
 const fillOptions=(id,values)=>{const el=$(id);if(!el)return;el.innerHTML='';for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=value.replaceAll('-',' ').toUpperCase();el.append(o);}};fillOptions('projectionA',PROJECTION_MAPPINGS);fillOptions('projectionB',PROJECTION_MAPPINGS);fillOptions('projectionMaskSource',PROJECTION_MASKS);fillOptions('projectionWrap',PROJECTION_WRAP_MODES);fillOptions('reflectionProjection',PROJECTION_REFLECTION_CHOICES);for(const id of ['displacementProjection','patternProjection','foamProjection','emissionProjection','maskProjection'])fillOptions(id,PROJECTION_LAYER_CHOICES);

 function openRange(key){clearHeld();rangeKey=key;const s=PARAMETERS[key],r=store.ranges[key],cap=store.safetyCaps[key],fx=store.functionalExtremums[key];$('rangeTitle').textContent=s.label;$('rangeInfo').textContent=s.help;$('rangeMin').value=r.min;$('rangeMax').value=r.max;$('hardMin').value=cap.min;$('hardMax').value=cap.max;$('functionalMin').value=fx.min;$('functionalMax').value=fx.max;$('absoluteBounds').textContent=`ABSOLUTE ENGINEERING RANGE ${s.hardMin} … ${s.hardMax}`;$('rangeError').textContent='';$('rangeDialog').showModal();}
 $('rangeForm').onsubmit=e=>{e.preventDefault();try{const cap=validateSafetyCaps(rangeKey,$('hardMin').value,$('hardMax').value);if(store.settings[rangeKey]<cap.min||store.settings[rangeKey]>cap.max)throw new Error('CURRENT VALUE IS OUTSIDE THE PROPOSED SAFETY CAPS.');const r=validateRange(rangeKey,$('rangeMin').value,$('rangeMax').value,cap);store.setSafetyCaps(rangeKey,cap.min,cap.max);store.setRange(rangeKey,r.min,r.max);store.setFunctionalExtremums(rangeKey,parseFunctionalExtremum($('functionalMin').value),parseFunctionalExtremum($('functionalMax').value));$('rangeDialog').close();}catch(err){$('rangeError').textContent=err.message;}};$('rangeCancel').onclick=()=>$('rangeDialog').close();$('rangeDefault').onclick=()=>{const s=PARAMETERS[rangeKey],cap=store.safetyCaps[rangeKey];$('rangeMin').value=Math.max(s.min,cap.min);$('rangeMax').value=Math.min(s.max,cap.max);};$('hardDefault').onclick=()=>{const s=PARAMETERS[rangeKey];$('hardMin').value=s.hardMin;$('hardMax').value=s.hardMax;};

 function parameter(key,container){const s=PARAMETERS[key],root=document.createElement('div');root.className='param';root.dataset.parameter=key;const label=document.createElement('label');label.textContent=s.label;label.htmlFor=key;label.dataset.tip=s.help;const field=document.createElement('input');field.id=key;field.type='number';field.step='any';field.dataset.tip=`${s.help} DIRECT NUMERIC ENTRY.`;const bounds=document.createElement('button');bounds.textContent='↔';bounds.dataset.tip=`ADVANCED INFORMATION AND LIMITS FOR ${s.label}.`;bounds.onclick=()=>openRange(key);const track=document.createElement('div');track.className='track';const lo=document.createElement('span'),slider=document.createElement('input'),hi=document.createElement('span');slider.type='range';slider.step=s.step;slider.dataset.tip=s.help;track.append(lo,slider,hi);root.append(label,field,bounds,track);$(container).append(root);field.onchange=()=>{try{store.set(key,field.value);}catch(e){notify(e.message);sync();}};field.onkeydown=e=>{if(e.key==='Enter'){field.blur();}if(e.key==='Escape'){sync();field.blur();}};const updateRangeFill=()=>{const mn=+slider.min,mx=+slider.max,v=+slider.value,p=mx>mn?Math.max(0,Math.min(100,(v-mn)/(mx-mn)*100)):0;slider.style.setProperty('--range-progress',`${p}%`);};slider.oninput=()=>{try{store.set(key,+slider.value);updateRangeFill();}catch(e){notify(e.message);}};rows.set(key,{field,slider,lo,hi,updateRangeFill});}
 const containers={...kineticUI.containers,plasma:'plasmaControls',environment:'environmentControls',liquid:'liquidControls',reflection:'reflectionControls',pattern:'patternControls',distance:'distanceControls',finish:'finishControls',render:'renderControls',modulation:'modControls',lut:'lutControls',noixture:'noixtureControls',mixer:'mixerControls',mask:'maskControls',lighting:'lightingControls',geometry:'geometryControls',projection:'projectionControls'};
 for(const [key,s] of Object.entries(PARAMETERS)){if(['spatialSmooth','temporalSmooth'].includes(key)){parameter(key,'upsamplingQuick');continue;}const c=containers[s.group]||(s.group==='sampling'?'samplingControls':null);if(c)parameter(key,c);}

 kineticUI.finishControls();
 for(const id of ['sceneMode','envMode','upsampling','upsamplingStageB','processingStage','cloudBlend','noixtureMode','noixtureBlend','mixerBlend','foamBlend','maskSourceA','maskSourceB','maskMixMode','modWave','meshAsset','meshSpikeMode','projectionA','projectionB','projectionMaskSource','projectionWrap','displacementProjection','patternProjection','foamProjection','emissionProjection','reflectionProjection','maskProjection'])$(id).onchange=()=>{try{if(id==='envMode'&&$(id).value==='hdri'&&!app.hasHDRI()){notify('NO HDRI IS LOADED. LOAD HDR/EXR FIRST.');sync();return;}if(id==='meshAsset'&&$(id).value==='imported'&&!app.importedMeshSource){notify('NO IMPORTED MESH IS LOADED. IMPORT STL / OBJ / PLY FIRST.');sync();return;}store.set(id,$(id).value);}catch(e){notify(e.message);sync();}};
 for(const id of ['showSky','mixerEnabled','noixtureEnabled','maskEnabled','maskInvert','maskMixer','maskNoixture','maskClouds','maskFoam','ambientEnabled','emissiveEnabled','spotEnabled','meshRetessellate','meshPreserveBoundary','meshPreserveHardEdges'])$(id).onchange=()=>{if(id==='mixerEnabled'&&$(id).checked&&!app.hasHDRI())notify('MIXER ENABLED WITHOUT HDRI: IT WILL FAIL OPEN TO SKYSYNTH UNTIL A PANORAMA IS LOADED.');store.set(id,$(id).checked);};for(const id of ['bodyColor','foamColor','noixtureColor','ambientColor','emissiveColor','spotColor'])$(id).onchange=()=>{try{store.set(id,$(id).value);}catch(e){notify(e.message);sync();}};
 $('pause').onclick=()=>store.set('paused',!store.settings.paused);$('resetCamera').onclick=()=>app.resetCamera();$('restart').onclick=()=>void app.restart();$('headerBG').onchange=()=>{try{store.set('uiBackground',$('headerBG').value);}catch(e){notify(e.message);sync();}};

 // Panel presets and global stacks.
 function refreshPanelPreset(panel){const sel=$(`preset-${panel}`),current=store.panelSelections[panel]||'Custom';if(!sel)return;sel.innerHTML='';for(const name of store.panelChoices(panel)){const o=document.createElement('option');o.value=name;o.textContent=name;const p=store.resolvePanelPreset(panel,name);if(p?.description)o.title=p.description;sel.append(o);}sel.value=store.panelChoices(panel).includes(current)?current:'Custom';}
 function refreshPresets(){for(const panel of PANEL_IDS)refreshPanelPreset(panel);const g=$('globalPreset'),current=store.globalStackName||'Custom';g.innerHTML='';for(const name of store.globalChoices()){const o=document.createElement('option');o.value=name;o.textContent=name;const p=store.resolveGlobal(name);if(p?.description)o.title=p.description;g.append(o);}g.value=store.globalChoices().includes(current)?current:'Custom';}
 document.querySelectorAll('[data-panel-load]').forEach(b=>b.onclick=()=>{const panel=b.dataset.panelLoad,name=$(`preset-${panel}`).value;if(name==='Custom')return;try{store.applyPanelPreset(panel,name);if(panel==='skysynth')setAnchor();}catch(e){notify(e.message);}});
 document.querySelectorAll('[data-panel-save]').forEach(b=>b.onclick=()=>{const panel=b.dataset.panelSave,name=prompt(`SAVE ${PANEL_DEFINITIONS[panel].label} PRESET AS:`,'');if(!name)return;try{store.savePanelPreset(panel,name);refreshPresets();}catch(e){notify(e.message);}});
 document.querySelectorAll('[data-panel-delete]').forEach(b=>b.onclick=()=>{const panel=b.dataset.panelDelete,name=$(`preset-${panel}`).value;if(!store.panelPresets[panel]?.[name]){notify('ONLY USER PANEL PRESETS CAN BE DELETED.');return;}if(confirm(`DELETE ${name}?`))store.deletePanelPreset(panel,name);});
 $('loadGlobal').onclick=()=>{const select=$('globalPreset'),name=select.value;try{if(name!=='Custom'){store.applyGlobalStack(name);setAnchor();if(store.settings.mixerEnabled&&!app.hasHDRI())notify('GLOBAL STACK LOADED. ITS MIXER EXPECTS AN HDRI; LOAD ONE TO ACTIVATE THAT INPUT.');}}catch(e){notify(e.message);}finally{select.focus();}};
 $('saveGlobal').onclick=()=>{const name=prompt('SAVE GLOBAL STACK AS:','');if(!name)return;try{store.saveGlobalStack(name);refreshPresets();}catch(e){notify(e.message);}};$('deleteGlobal').onclick=()=>{const name=$('globalPreset').value;if(!store.globalStacks[name]){notify('ONLY USER GLOBAL STACKS CAN BE DELETED.');return;}if(confirm(`DELETE ${name}?`))store.deleteGlobalStack(name);};

 // Modular global-preset locks. Submenu locks are OFF/LOCK. Visual-panel overrides are NONE/LOCK/UNLOCK.
 document.querySelectorAll('[data-submenu-lock]').forEach(b=>{b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.submenuLock;store.setSubmenuLock(id,!store.submenuLocks[id]);};});
 document.querySelectorAll('[data-panel-global-lock]').forEach(b=>{b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.panelGlobalLock,current=store.panelGlobalLocks[id]||'none',next=current==='none'?'lock':current==='lock'?'unlock':'none';store.setPanelGlobalLock(id,next);};});
 function syncLocks(){for(const b of document.querySelectorAll('[data-submenu-lock]')){const locked=!!store.submenuLocks[b.dataset.submenuLock];b.textContent=locked?'LOCK':'OFF';b.dataset.lockState=locked?'lock':'off';b.setAttribute('aria-pressed',String(locked));}for(const b of document.querySelectorAll('[data-panel-global-lock]')){const state=store.panelGlobalLocks[b.dataset.panelGlobalLock]||'none';b.textContent=`G:${state.toUpperCase()}`;b.dataset.lockState=state;b.title=state==='lock'?'GLOBAL PRESET LOADS CANNOT CHANGE ANY SUBMENU IN THIS PANEL.':state==='unlock'?'GLOBAL PRESET LOADS OVERRIDE ALL SUBMENU LOCKS IN THIS PANEL.':'GLOBAL PRESET LOADS HONOUR INDIVIDUAL SUBMENU LOCKS.';}}

 // SkySynth keybed.
 const mapping={q:['freqY',.005],a:['freqY',-.005],w:['freqX',.005],s:['freqX',-.005],t:['speed',.03],g:['speed',-.03],y:['hueShift',.5],h:['hueShift',-.5],u:['radius',.005],j:['radius',-.005],i:['lutSlot',1],k:['lutSlot',-1]},pairs=[['FREQ Y','q','a'],['FREQ X','w','s'],['SPEED','t','g'],['LUT DRIFT','y','h'],['RADIUS','u','j'],['LUT SLOT','i','k']],keyButtons={};for(const [label,up,down] of pairs){const wrap=document.createElement('div');wrap.className='key-function';const l=document.createElement('label');l.textContent=label;wrap.append(l);for(const [key,sign] of [[up,'+'],[down,'−']]){const b=document.createElement('button');b.innerHTML=`<span class="sign">${sign}</span><span class="key">${key.toUpperCase()}</span>`;b.dataset.tip=`${sign==='+'?'INCREASE':'DECREASE'} ${label}. HOLD TO REPEAT.`;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);hold(key);};wrap.append(b);keyButtons[key]=b;}$('keycaps').append(wrap);}
 let latch=0;const updateLatch=()=>{$('latchOne').setAttribute('aria-pressed',String(!!(latch&1)));$('latchTwo').setAttribute('aria-pressed',String(!!(latch&2)));};$('latchOne').onclick=()=>{latch^=1;updateLatch();};$('latchTwo').onclick=()=>{latch^=2;updateLatch();};function stepKey(key){const [name,delta]=mapping[key];if(name==='lutSlot'){store.set(name,(store.settings.lutSlot+delta+10)%10);return;}const high=['speed','radius'].includes(name),scale=((latch&1)?(high?3:1.5):1)*((latch&2)?(high?6:3):1),spec=PARAMETERS[name];store.set(name,Math.max(store.safetyCaps[name].min,Math.min(store.safetyCaps[name].max,store.settings[name]+delta*scale)));}function hold(key){if(held.has(key))return;stepKey(key);keyButtons[key]?.classList.add('key-held');const delay=setTimeout(()=>{const interval=setInterval(()=>stepKey(key),70);held.set(key,{delay,interval});},350);held.set(key,{delay,interval:null});}function release(key){const h=held.get(key);if(!h)return;clearTimeout(h.delay);clearInterval(h.interval);held.delete(key);keyButtons[key]?.classList.remove('key-held');}
 function setAnchor(){anchor=Object.fromEntries(PATTERN_KEYS.map(k=>[k,store.settings[k]]));randomHistory.length=0;}
 function randomize(){randomHistory.push(Object.fromEntries(PATTERN_KEYS.map(k=>[k,store.settings[k]])));if(randomHistory.length>2)randomHistory.shift();const r=seeded((Date.now()^Math.floor(Math.random()*0xffffffff))>>>0),patch={freqY:r()*.9-.45,freqX:r()*.9-.45,speed:r()*.7-.18,hueShift:r()*36-18,radius:r()*.7-.18,diagonal:r()*.8-.4,warp:r()*.75,fieldContrast:.8+r()*2.4};store.patch(patch,'randomize');}
 $('randomPattern').onclick=randomize;$('undoPattern').onclick=()=>{const p=randomHistory.pop();if(p)store.patch(p,'randomize-undo');};$('resetKeybed').onclick=()=>store.patch(anchor,'key-reset');

 // Modulation.
 const targets=[['freqY','FREQ Y'],['freqX','FREQ X'],['speed','SPEED'],['hueShift','LUT DRIFT'],['radius','RADIUS']];for(const [key,label] of targets){const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.dataset.modTarget=key;c.onchange=()=>store.set('modTargets',targets.filter(([k])=>document.querySelector(`[data-mod-target="${k}"]`).checked).map(([k])=>k));l.append(c,label);$('modTargets').append(l);}$('modEnable').onclick=()=>store.set('modEnabled',!store.settings.modEnabled);$('skyModMeter').onclick=()=>$('modEnable').click();$('resetMod').onclick=()=>store.patch({modEnabled:false,modAmplitude:25,modHz:.5,modWidthMin:-100,modWidthMax:100,modOffset:0,modWave:'sine',modTargets:['speed']},'mod-reset');$('envPreview').onclick=()=>app.setPreviewEnabled(false);$('previewToggleText').onclick=()=>app.setPreviewEnabled(true);
 function updateModulation(value){const range=Math.max(1,store.settings.modAmplitude),q=Math.max(-1,Math.min(1,value/range)),fill=$('modMeterFill');if(q>=0){fill.style.left='50%';fill.style.width=`${q*50}%`;}else{fill.style.left=`${50+q*50}%`;fill.style.width=`${-q*50}%`;}$('modMeterValue').textContent=value.toFixed(2);$('skyModMeter').querySelector('i').style.height=`${Math.min(100,Math.abs(q)*100)}%`;}

 // LUT editor: 16×16 spatial selection, region clipboard, undo/redo, paint, eyedropper and gradients.
 const lutEditor=installLUTEditor({store,$,notify,download});
 const syncPalette=()=>lutEditor.syncPalette();

 // Files / project.
 $('loadMesh').onclick=()=>$('meshFile').click();$('meshFile').onchange=async()=>{const f=$('meshFile').files[0];if(f)await app.importMesh(f);$('meshFile').value='';};$('loadHDRI').onclick=()=>$('hdriFile').click();$('hdriFile').onchange=async()=>{const f=$('hdriFile').files[0];if(f)await app.importHDRI(f);$('hdriFile').value='';};$('exportProject').onclick=()=>download('Xenofield-v4.4b-project.json',JSON.stringify({...store.snapshot(),environmentAsset:app.assetName||null,note:'PANORAMA PIXELS ARE STORED SEPARATELY. RELOAD THE NAMED HDRI/EXR AFTER TRANSFERRING THIS PROJECT.'},null,2));$('importProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async()=>{const f=$('projectFile').files[0];if(!f)return;try{if(f.size>4*1024*1024)throw new Error('PROJECT FILE EXCEEDS 4 MIB.');const data=JSON.parse(await f.text());store.applySnapshot(data);refreshPresets();setAnchor();if((store.settings.envMode==='hdri'||store.settings.mixerEnabled)&&!app.hasHDRI())notify(`PROJECT EXPECTS AN HDRI${data.environmentAsset?': '+data.environmentAsset:''}. LOAD IT TO ACTIVATE THAT INPUT.`);}catch(e){notify(e.message);}finally{$('projectFile').value='';}};$('capture').onclick=()=>app.capture();$('diagnostics').onclick=()=>download('Xenofield-v4.4b-diagnostics.json',JSON.stringify(app.metrics(),null,2));$('notification').onclick=()=>$('notification').classList.add('hidden');

 // Camera/keyboard.
 const canvas=$('scene');canvas.onpointerdown=e=>{clearHeld();canvas.focus();if(cloudUI.pointerDown(e))return;app.keyboardOwner='camera';app.startLook(e);};canvas.onpointermove=e=>{if(cloudUI.pointerMove(e))return;app.look(e);};canvas.onpointerup=e=>{if(cloudUI.pointerUp(e))return;app.stopLook();};canvas.onpointercancel=e=>{cloudUI.pointerUp(e);app.stopLook();};canvas.addEventListener('wheel',e=>{if(cloudUI.wheel(e))return;e.preventDefault();app.zoom(e.deltaY);},{passive:false});window.addEventListener('keydown',e=>{if($('rangeDialog').open)return;if(e.key==='Escape'){layout();return;}if(editable(e.target)||e.altKey||e.metaKey)return;if(e.key==='Tab'){e.preventDefault();if(!e.repeat)$('hidePanels').click();return;}if(/^\d$/.test(e.key)&&!e.ctrlKey){const names=Object.keys(GLOBAL_PRESETS),i=+e.key;if(names[i]){e.preventDefault();$('globalPreset').value=names[i];$('loadGlobal').click();}return;}if(e.ctrlKey&&/^\d$/.test(e.key)){e.preventDefault();store.set('lutSlot',+e.key);return;}if(e.ctrlKey)return;const key=e.key.toLowerCase();if(key==='p'&&!e.repeat){randomize();return;}if(app.keyboardOwner==='skysynth'&&mapping[key]){e.preventDefault();hold(key);return;}if(app.keyboardOwner==='camera'){app.cameraKeys.add(e.key==='Shift'?'Shift':e.key.startsWith('Arrow')?e.key:key);if(e.key.startsWith('Arrow'))e.preventDefault();}});window.addEventListener('keyup',e=>{release(e.key.toLowerCase());app.cameraKeys.delete(e.key);app.cameraKeys.delete(e.key.toLowerCase());});

 // Tooltips and sync.
 const tips={loadHDRI:'LOAD AN EQUIRECTANGULAR HDRI. HDR/RGBE AND COMMON EXR (NONE/RLE/ZIP/ZIPS) DECODE LOCALLY; PIZ/PXR24 USE AN EXTENDED FALLBACK WHEN AVAILABLE.',openMixer:'OPEN SKYMIXER.',openNoixture:'OPEN SKYNOIXTURE.',openMask:'OPEN LIVE MASK GENERATOR.',openModulation:'OPEN TRANSIENT MODULATOR.',skyModMeter:'LIVE MODULATION MAGNITUDE; CLICK TO TOGGLE MODULATION.',restart:'RECREATE THE WEBGPU RENDERER.',diagnostics:'EXPORT CURRENT METRICS AND ERRORS.',loadMesh:'IMPORT STL, OBJ, OR ASCII PLY; CONDITION, RETESSELLATE, AND MAP XENOFIELD PROJECTIONS ONTO IT.'};function applyTooltips(){const on=store.uiSettings.tooltips;document.body.dataset.tooltips=String(on);for(const el of document.querySelectorAll('[data-tip],button,select,input[type=range]')){const tip=el.dataset.tip||tips[el.id]||el.getAttribute('aria-label')||'';if(on&&tip)el.title=tip;else el.removeAttribute('title');}$('tooltipsEnabled').checked=on;}$('tooltipsEnabled').onchange=()=>store.setUISetting('tooltips',$('tooltipsEnabled').checked);
 function updateSourceState(){const s=store.settings,loaded=app.hasHDRI();$('assetName').textContent=loaded?(app.assetName||'HDRI LOADED'):'NO HDRI LOADED';$('sourceState').textContent=s.mixerEnabled?(loaded?`MIXER ACTIVE · ${Math.round(s.mixerMix*100)}% HDRI`:'MIXER WAITING FOR HDRI'):(s.envMode==='hdri'?(loaded?'HDRI ACTIVE':'HDRI NOT LOADED'):'SKYSYNTH ACTIVE');}
 function updateMeshState(){const el=$('meshState');if(!el)return;const s=store.settings,stats=app.renderer?.meshStats||null;let label=s.meshAsset==='d20'?'D20 SHOWCASE · SUPPLIED STL':s.meshAsset==='imported'?(app.meshName||'IMPORTED MESH'):'PROJECTION KNOT';if(stats)label+=` · ${stats.vertices??'?'} V · ${stats.triangles??'?'} T`;el.textContent=label;}
 function syncPresetSelections(){for(const panel of PANEL_IDS){const el=$(`preset-${panel}`);if(el&&el.querySelector(`option[value="${CSS.escape(store.panelSelections[panel]||'Custom')}"]`))el.value=store.panelSelections[panel]||'Custom';}const g=$('globalPreset');if(g&&g.querySelector(`option[value="${CSS.escape(store.globalStackName||'Custom')}"]`))g.value=store.globalStackName||'Custom';}

 let lastProfilerPaint=0,profilerPending=false,profilerLatest=null;function updateProfiler(history,fpsLimit=60){kineticUI.update();profilerLatest={history,fpsLimit};const canvas=$('profilerChart'),now=performance.now();if(!canvas||canvas.getClientRects().length===0||profilerPending||now-lastProfilerPaint<180)return;profilerPending=true;const paint=()=>{profilerPending=false;const payload=profilerLatest;if(!payload||canvas.getClientRects().length===0)return;lastProfilerPaint=performance.now();const {history:rows,fpsLimit:limit}=payload,ctx=canvas.getContext('2d'),dpr=Math.max(1,window.devicePixelRatio||1),cssW=canvas.clientWidth||420,cssH=canvas.clientHeight||200;if(canvas.width!==Math.round(cssW*dpr)||canvas.height!==Math.round(cssH*dpr)){canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cssW,cssH);ctx.fillStyle='#050b10';ctx.fillRect(0,0,cssW,cssH);
 const msSeries=[['frameMs','#ffffff','FRAME'],['frameTotal','#7fffd4','FRAME CPU'],['renderCpuMs','#7ab6ff','RENDER CPU'],['envUploadMs','#ffc778','ENV UPLOAD'],['gpuSynthMs','#ffcf5c','GPU SYNTH'],['gpuSpatialMs','#f5a95c','GPU SPATIAL'],['gpuUpsampleAMs','#ff8c68','GPU UP A'],['gpuNLFilterMs','#ff6e92','GPU NL'],['gpuUpsampleBMs','#e978ff','GPU UP B'],['gpuMipMs','#b77cff','GPU MIPS'],['gpuLiquidFFTMs','#72a7ff','GPU FFT'],['gpuSceneMs','#5fdcff','GPU SCENE'],['gpuPostMs','#67ffc4','GPU POST'],['gpuPreviewMs','#b4ff8a','GPU PREVIEW']];const maxMs=Math.max(4,...rows.flatMap(s=>msSeries.map(([k])=>s[k]||0))),divisions=4;ctx.font='8px ui-monospace,monospace';ctx.textBaseline='top';for(let i=0;i<=divisions;i++){const value=maxMs*(divisions-i)/divisions,y=2+(cssH-4)*i/divisions;ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(cssW,y);ctx.stroke();ctx.fillStyle='rgba(220,235,238,.72)';ctx.fillText(`${value.toFixed(value>=10?0:1)} ms`,4,Math.min(cssH-12,y+2));}ctx.fillStyle='rgba(220,235,238,.8)';ctx.fillText('FRAME MS',4,2);ctx.textAlign='right';ctx.fillText(`${limit} FPS`,cssW-4,2);ctx.fillText('0 FPS',cssW-4,cssH-12);ctx.textAlign='left';
 const xAt=i=>rows.length>1?i*(cssW-1)/(rows.length-1):0;for(const [key,color] of msSeries){ctx.strokeStyle=color;ctx.lineWidth=1.25;ctx.beginPath();rows.forEach((s,i)=>{const x=xAt(i),y=cssH-Math.min(1,(s[key]||0)/maxMs)*(cssH-4)-2;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}ctx.strokeStyle='#ffffff';ctx.lineWidth=1.8;ctx.beginPath();rows.forEach((s,i)=>{const x=xAt(i),y=cssH-Math.min(1,(s.fps||0)/Math.max(1,limit))*(cssH-4)-2;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();const latest=rows[rows.length-1]||{},legend=[['fps','#ffffff','FPS',`${(latest.fps||0).toFixed(1)}`],...msSeries.map(([k,c,label])=>[k,c,label,`${(latest[k]||0).toFixed(2)} ms`])];$('profilerLegend').innerHTML=legend.map(([,c,label,value])=>`<span><i style="background:${c}"></i><b>${label}</b> ${value}</span>`).join('');};if('requestIdleCallback'in window)requestIdleCallback(paint,{timeout:350});else setTimeout(paint,0);}

 function sync(){for(const [id,key] of [['headerBG','uiBackground']])if(document.activeElement!==$(id))$(id).value=store.settings[key];for(const [key,row] of rows){const r=store.ranges[key],cap=store.safetyCaps[key],n=store.settings[key];if(document.activeElement!==row.field)row.field.value=fmt(n);row.field.min=cap.min;row.field.max=cap.max;row.slider.min=r.min;row.slider.max=r.max;row.slider.value=n;row.lo.textContent=fmt(r.min);row.hi.textContent=fmt(r.max);row.updateRangeFill?.();}for(const id of ['sceneMode','envMode','upsampling','upsamplingStageB','processingStage','cloudBlend','noixtureMode','noixtureBlend','mixerBlend','foamBlend','maskSourceA','maskSourceB','maskMixMode','modWave','bodyColor','foamColor','noixtureColor','ambientColor','emissiveColor','spotColor','meshAsset','meshSpikeMode','projectionA','projectionB','projectionMaskSource','projectionWrap','displacementProjection','patternProjection','foamProjection','emissionProjection','reflectionProjection','maskProjection'])if(document.activeElement!==$(id))$(id).value=store.settings[id];for(const id of ['showSky','mixerEnabled','noixtureEnabled','maskEnabled','maskInvert','maskMixer','maskNoixture','maskClouds','maskFoam','ambientEnabled','emissiveEnabled','spotEnabled','meshRetessellate','meshPreserveBoundary','meshPreserveHardEdges'])$(id).checked=!!store.settings[id];$('pause').textContent=store.settings.paused?'RESUME':'PAUSE';$('modEnable').textContent=store.settings.modEnabled?'ON':'OFF';$('skyModMeter').dataset.active=String(store.settings.modEnabled);document.querySelectorAll('[data-mod-target]').forEach(e=>e.checked=store.settings.modTargets.includes(e.dataset.modTarget));$('undoPattern').disabled=!randomHistory.length;document.documentElement.style.setProperty('--ui-back','#'+store.settings.uiBackground);const rgb=hexRGB(store.settings.uiBackground);document.documentElement.dataset.lightUi=String(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.52);syncPresetSelections();syncLocks();updateSourceState();updateMeshState();applyTooltips();}
 store.addEventListener('change',e=>{if(['panel-preset-saved','panel-preset-deleted','global-stack-saved','global-stack-deleted','project'].includes(e.detail.reason))refreshPresets();sync();if(e.detail.keys.includes('palette')||e.detail.keys.includes('lutSlot')||['project','panel-preset:lut','global-stack'].includes(e.detail.reason))syncPalette();if(['global-stack','project','panel-preset:skysynth'].includes(e.detail.reason))setAnchor();});
 layout();setPreviewEnabled(true);setAnchor();refreshPresets();sync();syncPalette();return {sync,layout,refreshPresets,syncPalette,clearHeld,setAnchor,rows,updateModulation,updateSourceState,updateMeshState,updateProfiler,setPreviewEnabled};
}
