const EPS=1e-12;
const V=(x=0,y=0,z=0)=>[x,y,z];
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const len=a=>Math.hypot(a[0],a[1],a[2]),norm=a=>{const l=len(a)||1;return [a[0]/l,a[1]/l,a[2]/l];};
const edgeKey=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
export const MESH_FILE_TYPES=['.stl','.obj','.ply','.glb','.gltf'];

function asMesh(positions,indices,uvs=null){return {positions:positions.map(v=>[+v[0],+v[1],+v[2]]),indices:Array.from(indices,Number),uvs:uvs?uvs.map(v=>[+v[0],+v[1]]):positions.map(()=>[0,0]),normals:null,name:'mesh'};}
export function parseSTL(buffer){
 const bytes=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
 const binary=bytes.byteLength>=84&&84+dv.getUint32(80,true)*50===bytes.byteLength;
 const positions=[],indices=[];
 if(binary){const n=dv.getUint32(80,true);let o=84;for(let i=0;i<n;i++,o+=50){o+=0;for(let k=0;k<3;k++){const p=o+12+k*12;positions.push([dv.getFloat32(p,true),dv.getFloat32(p+4,true),dv.getFloat32(p+8,true)]);indices.push(positions.length-1);}}}
 else {const text=new TextDecoder().decode(bytes);const re=/vertex\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)/g;let m;while((m=re.exec(text)))positions.push([+m[1],+m[2],+m[3]]);if(positions.length<3||positions.length%3)throw new Error('Invalid ASCII STL.');for(let i=0;i<positions.length;i++)indices.push(i);}
 return asMesh(positions,indices);
}
export function parseOBJ(text){
 const srcPos=[],srcUv=[],positions=[],uvs=[],indices=[],map=new Map();
 const lines=String(text).split(/\r?\n/);
 for(const line0 of lines){const line=line0.trim();if(!line||line[0]==='#')continue;const p=line.split(/\s+/);if(p[0]==='v'&&p.length>=4)srcPos.push([+p[1],+p[2],+p[3]]);else if(p[0]==='vt'&&p.length>=3)srcUv.push([+p[1],1-(+p[2])]);else if(p[0]==='f'&&p.length>=4){const face=[];for(const tok of p.slice(1)){const [vi0,ti0]=tok.split('/'),vi=+vi0<0?srcPos.length+(+vi0):(+vi0)-1,ti=ti0?(+ti0<0?srcUv.length+(+ti0):(+ti0)-1):-1;if(!srcPos[vi])continue;const key=`${vi}/${ti}`;let id=map.get(key);if(id===undefined){id=positions.length;map.set(key,id);positions.push(srcPos[vi]);uvs.push(srcUv[ti]||[0,0]);}face.push(id);}for(let i=1;i+1<face.length;i++)indices.push(face[0],face[i],face[i+1]);}}
 if(indices.length<3)throw new Error('OBJ contains no renderable faces.');return asMesh(positions,indices,uvs);
}
export function parsePLY(buffer){
 const bytes=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer),text=new TextDecoder().decode(bytes);if(!text.startsWith('ply'))throw new Error('Not a PLY file.');
 const end=text.indexOf('end_header');if(end<0)throw new Error('PLY header missing end_header.');const header=text.slice(0,end).split(/\r?\n/);if(!header.some(l=>/format\s+ascii/.test(l)))throw new Error('Only ASCII PLY is currently supported.');
 let nv=0,nf=0;for(const l of header){let m=l.match(/^element vertex\s+(\d+)/);if(m)nv=+m[1];m=l.match(/^element face\s+(\d+)/);if(m)nf=+m[1];}
 const body=text.slice(end+'end_header'.length).trim().split(/\r?\n/);if(body.length<nv)throw new Error('Truncated PLY.');const positions=[];for(let i=0;i<nv;i++){const p=body[i].trim().split(/\s+/).map(Number);positions.push([p[0],p[1],p[2]]);}const indices=[];for(let i=0;i<nf&&nv+i<body.length;i++){const p=body[nv+i].trim().split(/\s+/).map(Number),n=p[0],f=p.slice(1,1+n);for(let k=1;k+1<f.length;k++)indices.push(f[0],f[k],f[k+1]);}if(indices.length<3)throw new Error('PLY contains no renderable faces.');return asMesh(positions,indices);
}

const GLTF_COMPONENTS={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array};
const GLTF_COMPONENT_BYTES={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};
const GLTF_TYPE_SIZE={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
function decodeDataUri(uri){const m=String(uri).match(/^data:.*?(;base64)?,(.*)$/s);if(!m)throw new Error('GLTF external buffer is not embedded. Use GLB or a GLTF with data-URI buffers.');if(m[1]){const raw=atob(m[2]),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out.buffer;}return new TextEncoder().encode(decodeURIComponent(m[2])).buffer;}
function accessorData(gltf,buffers,index){const a=gltf.accessors?.[index],view=gltf.bufferViews?.[a?.bufferView];if(!a||!view)throw new Error('GLTF accessor/bufferView is missing.');if(a.sparse)throw new Error('Sparse GLTF accessors are not supported yet.');const C=GLTF_COMPONENTS[a.componentType],bytes=GLTF_COMPONENT_BYTES[a.componentType],size=GLTF_TYPE_SIZE[a.type];if(!C||!bytes||!size)throw new Error('Unsupported GLTF accessor format.');const buffer=buffers[view.buffer];if(!buffer)throw new Error('GLTF buffer is unavailable.');const base=(view.byteOffset||0)+(a.byteOffset||0),stride=view.byteStride||bytes*size,count=a.count||0,out=new Float64Array(count*size),dv=new DataView(buffer);const read=(o)=>{switch(a.componentType){case 5120:return dv.getInt8(o);case 5121:return dv.getUint8(o);case 5122:return dv.getInt16(o,true);case 5123:return dv.getUint16(o,true);case 5125:return dv.getUint32(o,true);default:return dv.getFloat32(o,true);}};for(let i=0;i<count;i++)for(let k=0;k<size;k++){let v=read(base+i*stride+k*bytes);if(a.normalized&&a.componentType!==5126){const signed=a.componentType===5120||a.componentType===5122,max=signed?(a.componentType===5120?127:32767):(a.componentType===5121?255:a.componentType===5123?65535:4294967295);v=signed?Math.max(-1,v/max):v/max;}out[i*size+k]=v;}return {data:out,size,count};}
function meshFromGLTF(gltf,buffers){const positions=[],uvs=[],indices=[];for(const mesh of gltf.meshes||[])for(const prim of mesh.primitives||[]){if(prim.mode!==undefined&&prim.mode!==4)continue;if(prim.attributes?.POSITION===undefined)continue;const pos=accessorData(gltf,buffers,prim.attributes.POSITION),tex=prim.attributes.TEXCOORD_0!==undefined?accessorData(gltf,buffers,prim.attributes.TEXCOORD_0):null,base=positions.length;for(let i=0;i<pos.count;i++){positions.push([pos.data[i*pos.size],pos.data[i*pos.size+1],pos.data[i*pos.size+2]]);uvs.push(tex&&i<tex.count?[tex.data[i*tex.size],1-tex.data[i*tex.size+1]]:[0,0]);}if(prim.indices!==undefined){const ind=accessorData(gltf,buffers,prim.indices);for(let i=0;i<ind.count;i++)indices.push(base+Math.trunc(ind.data[i]));}else for(let i=0;i<pos.count;i++)indices.push(base+i);}if(indices.length<3)throw new Error('GLTF contains no triangle primitives.');return asMesh(positions,indices,uvs);}
export function parseGLB(buffer){const bytes=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(bytes.byteLength<20||dv.getUint32(0,true)!==0x46546c67)throw new Error('Not a GLB file.');if(dv.getUint32(4,true)!==2)throw new Error('Only GLB 2.0 is supported.');let o=12,json=null,bin=null;while(o+8<=bytes.byteLength){const len=dv.getUint32(o,true),type=dv.getUint32(o+4,true);o+=8;if(o+len>bytes.byteLength)throw new Error('Truncated GLB chunk.');const chunk=bytes.slice(o,o+len);if(type===0x4E4F534A)json=JSON.parse(new TextDecoder().decode(chunk).replace(/\0+$/,''));else if(type===0x004E4942)bin=chunk.buffer;o+=len;}if(!json)throw new Error('GLB JSON chunk missing.');const buffers=(json.buffers||[]).map((b,i)=>i===0&&bin?bin:(b.uri?decodeDataUri(b.uri):null));return meshFromGLTF(json,buffers);}
export function parseGLTF(text){const gltf=JSON.parse(String(text)),buffers=(gltf.buffers||[]).map(b=>b.uri?decodeDataUri(b.uri):null);if(buffers.some((b,i)=>!b&&(gltf.buffers?.[i]?.byteLength||0)>0))throw new Error('GLTF references external .bin data. Use a self-contained GLB or embedded-data GLTF.');return meshFromGLTF(gltf,buffers);}


export async function loadBundledD20Mesh(){
 let bytes;
 const inline=globalThis.__XENOFIELD_D20_STL_BASE64__;
 if(inline){const raw=atob(inline),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);bytes=out;}
 else {const response=await fetch('assets/D20-showcase.stl');if(!response.ok)throw new Error(`Built-in D20 asset failed to load (${response.status}).`);bytes=new Uint8Array(await response.arrayBuffer());}
 const mesh=parseSTL(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));mesh.name='D20-showcase.stl';return mesh;
}

export async function parseMeshFile(file){const name=file?.name||'mesh';const lower=name.toLowerCase();if(file.size>512*1024*1024)throw new Error('Mesh file exceeds 512 MiB import cap.');let mesh;if(lower.endsWith('.stl'))mesh=parseSTL(await file.arrayBuffer());else if(lower.endsWith('.obj'))mesh=parseOBJ(await file.text());else if(lower.endsWith('.ply'))mesh=parsePLY(await file.arrayBuffer());else if(lower.endsWith('.glb'))mesh=parseGLB(await file.arrayBuffer());else if(lower.endsWith('.gltf'))mesh=parseGLTF(await file.text());else throw new Error('Supported mesh formats: STL, OBJ, ASCII PLY, GLB, embedded-data GLTF.');mesh.name=name;return mesh;}

export function normalizeMesh(mesh,targetRadius=100){const p=mesh.positions;if(!p.length)throw new Error('Empty mesh.');let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const v of p)for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],v[k]);mx[k]=Math.max(mx[k],v[k]);}const c=mul(add(mn,mx),.5),extent=sub(mx,mn),radius=Math.max(...extent)/2||1,scale=targetRadius/radius;mesh.positions=p.map(v=>mul(sub(v,c),scale));mesh.bounds={min:mul(sub(mn,c),scale),max:mul(sub(mx,c),scale),center:[0,0,0],radius:targetRadius};return mesh;}
export function weldMesh(mesh,epsilon=1e-5){if(epsilon<=0)return mesh;const out=[],uv=[],map=new Map(),remap=new Int32Array(mesh.positions.length);const inv=1/epsilon;for(let i=0;i<mesh.positions.length;i++){const v=mesh.positions[i],key=`${Math.round(v[0]*inv)},${Math.round(v[1]*inv)},${Math.round(v[2]*inv)}`;let j=map.get(key);if(j===undefined){j=out.length;map.set(key,j);out.push(v);uv.push(mesh.uvs?.[i]||[0,0]);}remap[i]=j;}mesh.positions=out;mesh.uvs=uv;mesh.indices=mesh.indices.map(i=>remap[i]);return mesh;}
function faceNormal(mesh,ti){const i=ti*3,a=mesh.positions[mesh.indices[i]],b=mesh.positions[mesh.indices[i+1]],c=mesh.positions[mesh.indices[i+2]];return norm(cross(sub(b,a),sub(c,a)));}
export function buildTopology(mesh,hardAngleDeg=55){const neighbors=Array.from({length:mesh.positions.length},()=>new Set()),edgeFaces=new Map(),faceNormals=[];for(let t=0;t<mesh.indices.length/3;t++){const ids=mesh.indices.slice(t*3,t*3+3);faceNormals[t]=faceNormal(mesh,t);for(let k=0;k<3;k++){const a=ids[k],b=ids[(k+1)%3];neighbors[a].add(b);neighbors[b].add(a);const key=edgeKey(a,b),list=edgeFaces.get(key)||[];list.push(t);edgeFaces.set(key,list);}}
 const boundary=new Set(),hard=new Set(),cos=Math.cos(hardAngleDeg*Math.PI/180);for(const [key,faces] of edgeFaces){const [a,b]=key.split(':').map(Number);if(faces.length===1){boundary.add(a);boundary.add(b);}else if(faces.length>=2&&dot(faceNormals[faces[0]],faceNormals[faces[1]])<cos){hard.add(a);hard.add(b);}}
 return {neighbors,edgeFaces,faceNormals,boundary,hard};}
export function smoothMesh(mesh,iterations=0,strength=.25,{preserveBoundary=true,preserveHard=true,hardAngle=55}={}){iterations=Math.max(0,Math.floor(iterations));for(let it=0;it<iterations;it++){const topo=buildTopology(mesh,hardAngle),next=mesh.positions.map(v=>[...v]);for(let i=0;i<mesh.positions.length;i++){if((preserveBoundary&&topo.boundary.has(i))||(preserveHard&&topo.hard.has(i)))continue;const ns=[...topo.neighbors[i]];if(ns.length<2)continue;let avg=[0,0,0];for(const j of ns)avg=add(avg,mesh.positions[j]);avg=mul(avg,1/ns.length);next[i]=add(mesh.positions[i],mul(sub(avg,mesh.positions[i]),strength));}mesh.positions=next;}return mesh;}
export function handleSpikes(mesh,{threshold=2.8,mode='relax',strength=.6,hardAngle=55,preserveBoundary=true,preserveHard=true}={}){if(mode==='leave')return {mesh,count:0};const topo=buildTopology(mesh,hardAngle),spikes=[];for(let i=0;i<mesh.positions.length;i++){if((preserveBoundary&&topo.boundary.has(i))||(preserveHard&&topo.hard.has(i)))continue;const ns=[...topo.neighbors[i]];if(ns.length<3)continue;let avg=[0,0,0],edge=0;for(const j of ns){avg=add(avg,mesh.positions[j]);edge+=len(sub(mesh.positions[j],mesh.positions[i]));}avg=mul(avg,1/ns.length);edge/=ns.length;const dev=len(sub(mesh.positions[i],avg));if(edge>EPS&&dev/edge>threshold)spikes.push([i,avg,edge,dev]);}
 if(mode==='cull'){const set=new Set(spikes.map(s=>s[0])),idx=[];for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i],b=mesh.indices[i+1],c=mesh.indices[i+2];if(!set.has(a)&&!set.has(b)&&!set.has(c))idx.push(a,b,c);}mesh.indices=idx;}
 else {for(const [i,avg,edge,dev] of spikes){if(mode==='clamp'){const dir=norm(sub(mesh.positions[i],avg));mesh.positions[i]=add(avg,mul(dir,edge*threshold));}else mesh.positions[i]=add(mesh.positions[i],mul(sub(avg,mesh.positions[i]),strength));}}
 return {mesh,count:spikes.length};}
export function retessellateMesh(mesh,{levels=1,targetEdge=12,curvatureAngle=35,triangleCap=1500000}={}){levels=Math.max(0,Math.min(4,Math.floor(levels)));const cosCurvature=Math.cos(Math.max(1,Math.min(179,curvatureAngle))*Math.PI/180);for(let pass=0;pass<levels;pass++){if(mesh.indices.length/3>=triangleCap)break;computeNormals(mesh);const sourceNormals=mesh.normals;const positions=mesh.positions.map(v=>[...v]),uvs=(mesh.uvs||mesh.positions.map(()=>[0,0])).map(v=>[...v]),mid=new Map(),idx=[];let split=0;const midpoint=(a,b)=>{const key=edgeKey(a,b);let m=mid.get(key);if(m!==undefined)return m;m=positions.length;mid.set(key,m);positions.push(mul(add(positions[a],positions[b]),.5));uvs.push(mul(add(uvs[a],uvs[b]),.5));return m;};for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i],b=mesh.indices[i+1],c=mesh.indices[i+2],pa=positions[a],pb=positions[b],pc=positions[c],mx=Math.max(len(sub(pa,pb)),len(sub(pb,pc)),len(sub(pc,pa))),curved=Math.min(dot(sourceNormals[a],sourceNormals[b]),dot(sourceNormals[b],sourceNormals[c]),dot(sourceNormals[c],sourceNormals[a]))<cosCurvature;if((mx>targetEdge||curved)&&idx.length/3+4<=triangleCap){const ab=midpoint(a,b),bc=midpoint(b,c),ca=midpoint(c,a);idx.push(a,ab,ca,ab,b,bc,ca,bc,c,ab,bc,ca);split++;}else idx.push(a,b,c);}mesh.positions=positions;mesh.uvs=uvs;mesh.indices=idx;if(!split)break;}return mesh;}

export function splitHardEdges(mesh,hardAngle=55){const topo=buildTopology(mesh,hardAngle),hardEdges=new Set();for(const [key,faces] of topo.edgeFaces){if(faces.length>=2&&dot(topo.faceNormals[faces[0]],topo.faceNormals[faces[1]])<Math.cos(hardAngle*Math.PI/180))hardEdges.add(key);}if(!hardEdges.size)return mesh;const positions=[],uvs=[],indices=[],shared=new Map();for(let i=0;i<mesh.indices.length;i+=3){const tri=[mesh.indices[i],mesh.indices[i+1],mesh.indices[i+2]],isHard=hardEdges.has(edgeKey(tri[0],tri[1]))||hardEdges.has(edgeKey(tri[1],tri[2]))||hardEdges.has(edgeKey(tri[2],tri[0]));for(const old of tri){let ni;if(isHard){ni=positions.length;positions.push([...mesh.positions[old]]);uvs.push([...(mesh.uvs?.[old]||[0,0])]);}else{ni=shared.get(old);if(ni===undefined){ni=positions.length;shared.set(old,ni);positions.push([...mesh.positions[old]]);uvs.push([...(mesh.uvs?.[old]||[0,0])]);}}indices.push(ni);}}mesh.positions=positions;mesh.uvs=uvs;mesh.indices=indices;return mesh;}

export function computeNormals(mesh){const normals=mesh.positions.map(()=>[0,0,0]);for(let i=0;i<mesh.indices.length;i+=3){const ia=mesh.indices[i],ib=mesh.indices[i+1],ic=mesh.indices[i+2],a=mesh.positions[ia],b=mesh.positions[ib],c=mesh.positions[ic],n=cross(sub(b,a),sub(c,a));normals[ia]=add(normals[ia],n);normals[ib]=add(normals[ib],n);normals[ic]=add(normals[ic],n);}mesh.normals=normals.map(norm);return mesh;}
export function localEdgeScales(mesh){const topo=buildTopology(mesh,180);return mesh.positions.map((p,i)=>{const ns=[...topo.neighbors[i]];if(!ns.length)return 1;let s=0;for(const j of ns)s+=len(sub(mesh.positions[j],p));return s/ns.length;});}
export function interleaveMesh(mesh){computeNormals(mesh);const edge=localEdgeScales(mesh),data=new Float32Array(mesh.positions.length*9);for(let i=0;i<mesh.positions.length;i++){const o=i*9,p=mesh.positions[i],n=mesh.normals[i],uv=mesh.uvs?.[i]||[0,0];data.set([p[0],p[1],p[2],n[0],n[1],n[2],uv[0],uv[1],edge[i]],o);}return {data,indices:new Uint32Array(mesh.indices),vertices:mesh.positions.length,triangles:mesh.indices.length/3};}
export function conditionMesh(source,settings={}){const start=performance.now(),mesh={positions:source.positions.map(v=>[...v]),indices:[...source.indices],uvs:(source.uvs||source.positions.map(()=>[0,0])).map(v=>[...v]),name:source.name||'mesh'};normalizeMesh(mesh,settings.meshScale||100);weldMesh(mesh,settings.meshWeldEpsilon??.002);const before=mesh.indices.length/3;if(settings.meshRetessellate!==false)retessellateMesh(mesh,{levels:settings.meshSubdivideLevels??1,targetEdge:settings.meshTargetEdge??12,curvatureAngle:settings.meshCurvatureAngle??35,triangleCap:settings.meshTriangleCap??1500000});let spikeCount=0;if((settings.meshSpikeMode||'relax')!=='leave'){const r=handleSpikes(mesh,{threshold:settings.meshSpikeThreshold??2.8,mode:settings.meshSpikeMode||'relax',strength:settings.meshSmoothStrength??.35,hardAngle:settings.meshHardEdgeAngle??55,preserveBoundary:settings.meshPreserveBoundary!==false,preserveHard:settings.meshPreserveHardEdges!==false});spikeCount=r.count;}smoothMesh(mesh,settings.meshSmoothIterations??1,settings.meshSmoothStrength??.25,{preserveBoundary:settings.meshPreserveBoundary!==false,preserveHard:settings.meshPreserveHardEdges!==false,hardAngle:settings.meshHardEdgeAngle??55});if(settings.meshPreserveHardEdges!==false)splitHardEdges(mesh,settings.meshHardEdgeAngle??55);const packed=interleaveMesh(mesh);return {...packed,name:mesh.name,sourceTriangles:before,spikeCount,processingMs:performance.now()-start};}

export function makeD20Mesh(){const phi=(1+Math.sqrt(5))/2,raw=[[-1,phi,0],[1,phi,0],[-1,-phi,0],[1,-phi,0],[0,-1,phi],[0,1,phi],[0,-1,-phi],[0,1,-phi],[phi,0,-1],[phi,0,1],[-phi,0,-1],[-phi,0,1]],positions=raw.map(norm),indices=[0,11,5,0,5,1,0,1,7,0,7,10,0,10,11,1,5,9,5,11,4,11,10,2,10,7,6,7,1,8,3,9,4,3,4,2,3,2,6,3,6,8,3,8,9,4,9,5,2,4,11,6,2,10,8,6,7,9,8,1];return asMesh(positions,indices);}
export function makeProjectionShowcaseMesh(){const rings=180,sides=24,R=2.0,tube=.42,positions=[],uvs=[],indices=[];const curve=t=>[(R+.6*Math.cos(3*t))*Math.cos(2*t),(R+.6*Math.cos(3*t))*Math.sin(2*t),.9*Math.sin(3*t)];for(let i=0;i<rings;i++){const t=i/rings*Math.PI*2,p=curve(t),p2=curve(t+.002),tan=norm(sub(p2,p)),ref=Math.abs(tan[2])<.9?[0,0,1]:[0,1,0],n1=norm(cross(tan,ref)),n2=norm(cross(tan,n1));for(let j=0;j<sides;j++){const a=j/sides*Math.PI*2,rad=tube*(1+.18*Math.sin(5*t+2*a)),off=add(mul(n1,Math.cos(a)*rad),mul(n2,Math.sin(a)*rad));positions.push(add(p,off));uvs.push([i/rings,j/sides]);}}for(let i=0;i<rings;i++)for(let j=0;j<sides;j++){const ni=(i+1)%rings,nj=(j+1)%sides,a=i*sides+j,b=ni*sides+j,c=i*sides+nj,d=ni*sides+nj;indices.push(a,b,c,c,b,d);}return asMesh(positions,indices,uvs);}
export function makeSphereMesh(n=192,radius=120){const w=n,h=Math.floor(n/2),positions=[],uvs=[],indices=[];for(let y=0;y<=h;y++)for(let x=0;x<=w;x++){const u=x/w,v=y/h,a=u*Math.PI*2,b=v*Math.PI;positions.push([Math.sin(b)*Math.cos(a)*radius,Math.cos(b)*radius,Math.sin(b)*Math.sin(a)*radius]);uvs.push([u,v]);}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const a=y*(w+1)+x,b=a+1,c=a+w+1,d=c+1;indices.push(a,b,c,b,d,c);}const mesh=asMesh(positions,indices,uvs);return interleaveMesh(mesh);}
