import {DEFAULTS} from './parameters.js';
import {KINETIC_GROUPS,kineticPanelKeys} from './kinetic-parameters.js';
const labels={depth:'Depth',temporal:'Temporal',volume:'XenoVolume',compositor:'Compositor',aa:'AA / Filtering',performance:'Performance'};
export const KINETIC_PANEL_DEFINITIONS=Object.freeze(Object.fromEntries(KINETIC_GROUPS.map(id=>[id,{label:labels[id],keys:kineticPanelKeys(id)}])));
export const KINETIC_SUBMENUS=Object.freeze(Object.fromEntries(KINETIC_GROUPS.map(id=>[`kinetic-${id}`,{label:labels[id].toUpperCase(),globalPanel:'surface',keys:kineticPanelKeys(id)}])));
// These are distinct strategies, not palette-only variants. Every stack resolves all six banks.
export const KINETIC_DEMOS=Object.freeze({
 'VOXEL SPRAY':{description:'24³ nearest cells, stochastic dropout, a depth-coupled shell and stable reconstruction.',scene:'liquid',settings:{volumeEnabled:true,volumeResolution:'24',volumeSpace:'surface-shell',volumeSteps:'8',volumeInterpolation:'nearest',volumeDitherType:'blue-noise',volumeQuantize:24,volumeDropout:.65,volumeDensity:1.2,volumeThreshold:.61,volumeSoftness:.06,volumeSourceMix:.18,volumeCoverage:.45,volumeCellEdges:.8,volumeEmission:1.4,volumeEnvironment:.06,volumeShellThickness:42,volumeMicrodetail:.7,volumeMicroSource:'hash',volumeDensityFPS:12,volumeLightFPS:6,volumeTemporalWeight:.82,temporalSamples:'8',positiveEnabled:true,positiveAmount:.2,volumeColor:'71EEEF'}},
 'ION VEIL':{description:'Smooth cached plasma with a soft shell, depth-aware displacement and low-resolution bloom.',scene:'liquid',settings:{volumeEnabled:true,volumeResolution:'32',volumeSpace:'surface-shell',volumeShellThickness:70,volumeThreshold:.42,volumeDensity:.25,volumeEmission:.8,volumeSourceB:'billow',volumeSourceMix:.15,volumeEnvironment:.08,volumeDropout:0,volumeDither:.25,volumeMicrodetail:.1,volumeLighting:'cached-march',volumeLightSteps:4,volumeSteps:'12',distortionEnabled:true,distortionSource:'volume-gradient',distortionStrength:14,distortionChromatic:.2,temporalSamples:'8',positiveEnabled:true,positiveAmount:.32,volumeColor:'48FFD6'}},
 'PHASE DUST':{description:'Sparse hash cells, eight ray samples and chromatic shear; intentionally granular.',scene:'field',settings:{volumeEnabled:true,volumeSpace:'camera-slab',volumeResolution:'32',volumeSource:'hash',volumeSourceB:'cellular',volumeThreshold:.7,volumeSoftness:.03,volumeDensity:.7,volumeDropout:.78,volumeEmission:1.5,volumeEnvironment:.04,volumeBlend:'add',volumeRenderScale:'3',volumeInterpolation:'nearest',volumeMicrodetail:.9,volumeMicroSource:'blue-noise',volumeSize:340,volumeRange:500,volumeDitherType:'bayer4',distortionEnabled:true,distortionSource:'procedural',distortionStrength:18,distortionChromatic:1.4,temporalSamples:'4',volumeColor:'E8C3FF'}},
 'CELLULAR STORM':{description:'Voronoi / cellular difference cache, cached shadows, positive and negative spread plus feedback.',scene:'field',settings:{volumeEnabled:true,volumeSpace:'world-box',volumeSize:260,volumeOffsetX:160,volumeOffsetY:35,volumeOffsetZ:190,volumeResolution:'32',volumeSource:'voronoi',volumeSourceB:'cellular',volumeGeneratorBlend:'difference',volumeSourceMix:.8,volumeThreshold:.38,volumeDensity:.45,volumeScale:5,volumeEmission:1.3,volumeEnvironment:.05,volumeLighting:'cached-march',volumeDropout:.1,volumeCellEdges:1.5,positiveEnabled:true,positiveMask:'volume-emission',positiveAmount:.4,darkEnabled:true,darkMask:'volume-edge',darkThreshold:.2,darkAmount:.6,feedbackEnabled:true,feedbackAmount:.15,feedbackDecay:.88,feedbackRotation:8,volumeColor:'FF994D'}},
 'VOID HALO':{description:'Absorptive planetary shell and a blurred silhouette mask, not a vignette.',scene:'planet',settings:{volumeEnabled:true,volumeSpace:'planet-shell',volumeOffsetY:0,volumeResolution:'24',volumeShellThickness:38,volumeShellOffset:3,volumeBlend:'absorption',volumeDensity:2,volumeEmission:0,volumeSource:'ridge',volumeSourceB:'billow',volumeThreshold:.35,volumeDropout:.12,darkEnabled:true,darkMask:'silhouette',darkThreshold:.1,darkRadius:32,darkAmount:1.4,depthEnabled:true,depthOperator:'edge-glow',depthAmount:.5,depthColor:'8B67FF',temporalSamples:'8',volumeColor:'A264EF'}},
 'TEMPORAL CRYSTAL':{description:'Four-ray stepped nearest voxels feeding an independent long-lived difference/max feedback history.',scene:'mesh',settings:{volumeEnabled:true,volumeSpace:'mesh-normal-shell',volumeResolution:'16',volumeSteps:'4',volumeInterpolation:'nearest',volumeDitherType:'bayer4',volumeDensityFPS:4,volumeLightFPS:2,volumeInterpolate:false,volumeSource:'cellular',volumeShape:'fold',volumeQuantize:16,volumeSlices:12,volumeThreshold:.44,volumeDensity:.8,volumeEmission:1.5,volumeCellEdges:.9,volumeEnvironment:.04,volumeTemporal:false,volumeMicrodetail:.6,feedbackEnabled:true,feedbackBlend:'max',feedbackPersistence:.995,feedbackAmount:.7,feedbackDecay:.985,feedbackGain:1,feedbackZoom:1.018,feedbackRotation:10,feedbackHue:40,feedbackWarp:.02,temporalSamples:'4',positiveEnabled:true,volumeColor:'D4FCFF'}},
 'CHROMATIC SHELL':{description:'A depth-coupled mesh-normal shell controls RGB-separated distortion with foreground guards.',scene:'mesh',settings:{volumeEnabled:true,volumeSpace:'mesh-normal-shell',volumeResolution:'32',volumeShellOffset:2,volumeShellThickness:28,volumeSource:'spectral',volumeSourceB:'ridge',volumeSourceMix:.65,volumeDensity:.7,volumeThreshold:.44,volumeEnvironment:.06,volumeBlend:'screen',volumeAmount:.4,volumeEmission:2,distortionEnabled:true,distortionSource:'volume-gradient',distortionStrength:36,distortionChromatic:2,distortionR:1,distortionG:0,distortionB:-1,distortionMask:'volume-density',temporalSamples:'8',volumeColor:'9A85FF'}},
 'DENSE NEBULA':{description:'48³ world cache, quarter-resolution rays, cached mip-shadow lighting and conservative history.',scene:'field',settings:{volumeEnabled:true,volumeSpace:'world-box',volumeOffsetX:180,volumeOffsetY:20,volumeOffsetZ:210,volumeResolution:'48',volumeSteps:'16',volumeRenderScale:'4',volumeLighting:'mip-shadow',volumeLightSteps:6,volumeLightFPS:8,volumeDensityFPS:15,volumeSource:'perlin',volumeSourceB:'billow',volumeSourceMix:.2,volumeScale:4.4,volumeDensity:.14,volumeThreshold:.45,volumeSoftness:.13,volumeDropout:0,volumeDither:.2,volumeEmission:.35,volumeEnvironment:.07,volumeAmbient:.14,volumeSize:300,volumeRange:700,volumeMicrodetail:.16,volumeTemporalWeight:.92,temporalSamples:'16',positiveEnabled:true,positiveAmount:.3,volumeColor:'D98DFF'}},
 'IMPOSSIBLE ATMOSPHERE':{description:'A planetary cache, animated depth strata, LUT cycling and slow warped screen feedback.',scene:'planet',settings:{volumeEnabled:true,volumeSpace:'planet-shell',volumeOffsetY:0,volumeResolution:'32',volumeShellThickness:75,volumeSource:'ridge',volumeSourceB:'skysynth',volumeSourceMix:.2,volumeThreshold:.5,volumeEmission:.6,volumeDensity:.45,volumeEnvironment:.05,depthEnabled:true,depthOperator:'bands',depthBlend:'screen',depthAmount:.35,depthNear:120,depthFar:700,depthBands:18,depthDrift:.13,colourEnabled:true,colourMask:'depth-sine',colourAmount:.3,colourSpeed:.07,feedbackEnabled:true,feedbackAmount:.25,feedbackDecay:.92,feedbackZoom:1.004,feedbackRotation:2,feedbackWarp:.04,temporalSamples:'8',volumeColor:'A8F568'}},
 'ABSURD AA':{description:'Experimental native MSAA4 + 8× pixel-area SSAA + Temporal32 + manual AF32. Allocation limits remain active.',scene:'mesh',settings:{msaa:'4',ssaaArea:'8',temporalSamples:'32',temporalWeight:.97,temporalLumaReject:3,temporalClamp:1,downsampleFilter:'lanczos2',textureFilter:'manual32',maxRenderMP:48,textureBudgetMB:4096,volumeEnabled:false}}
});
const pick=(group,settings)=>Object.fromEntries(kineticPanelKeys(group).map(key=>[key,settings[key]??DEFAULTS[key]]));
export const KINETIC_PANEL_PRESETS=Object.freeze(Object.fromEntries(KINETIC_GROUPS.map(group=>[group,Object.freeze({
 'Default':{description:'Neutral independent budget; optional effects disabled.',settings:pick(group,DEFAULTS)},
 ...Object.fromEntries(Object.entries(KINETIC_DEMOS).map(([name,demo])=>[name,{description:demo.description,settings:pick(group,{...DEFAULTS,...demo.settings})}]))
})])));
export const KINETIC_OUTPUT_PRESETS=Object.freeze(Object.fromEntries(['liquid','planet','mesh','field'].map(scene=>[`Kinetic ${scene}`,{description:'V4.4b neutral display; artistic effects own their bloom budgets.',settings:{sceneMode:scene,meshResolution:256,renderScale:1,displayFPS:60,exposure:.7,contrast:1.15,bloom:0,bloomThreshold:1.5,bloomRadius:2,sharpen:.08}}])));
export const KINETIC_GLOBAL_PRESETS=Object.freeze(Object.fromEntries(Object.entries(KINETIC_DEMOS).map(([name,demo],i)=>[name,{description:demo.description,panels:{skysynth:i%2?'Soft Nebula':'Glitch Lattice',liquid:'Glass Swell',reflection:'Kinetic Laboratory',pattern:'Dry Noise',atmosphere:'Kinetic Clear',lighting:'Noir Edge',output:`Kinetic ${demo.scene}`,modulation:'Disabled',lut:`Palette ${i%10}`,noixture:'Off',mixer:'Synth Only',mask:'Off',geometry:demo.scene==='mesh'?'D20 Conditioned':'Default Surface',projection:demo.scene==='planet'?'Octahedral Planet':demo.scene==='mesh'?'D20 Facet Storm':'Planar Legacy',...Object.fromEntries(KINETIC_GROUPS.map(group=>[group,name]))}}])));
