import {KINETIC_PANEL_DEFINITIONS,KINETIC_SUBMENUS,KINETIC_PANEL_PRESETS,KINETIC_OUTPUT_PRESETS,KINETIC_GLOBAL_PRESETS} from './kinetic-presets.js';
export const PANEL_DEFINITIONS=Object.freeze({
  ...KINETIC_PANEL_DEFINITIONS,
  proceduralClouds:{label:'Procedural Clouds',keys:['procCloudEnabled','procCloudDensity','procCloudCoverage','procCloudScale','procCloudAltitude','procCloudDetail','procCloudWindSpeed','procCloudSkipLight','procCloudRaySteps','procCloudLightSteps','procCloudShadowDark','procCloudSunIntensity','procCloudHeight','procCloudCacheRes','procCloudCacheUpdate','procCloudCacheSmooth','procCloudCenterX','procCloudCenterY','procCloudCenterZ','procCloudSizeX','procCloudSizeY','procCloudSizeZ','procCloudRenderScale','procCloudOpacity','procCloudDepthClip','procCloudDepthSoftness','procCloudEditActive','procCloudShowBounds','procCloudTransformMode','procCloudTransformAxis','procCloudDragSensitivity']},
  skysynth:{label:'SkySynth',keys:['envMode','freqY','freqX','speed','hueShift','radius','diagonal','warp','fieldContrast','radiance','sourceWidth','envMapWidth','generatorFPS','spatialSmooth','temporalSmooth','upsampling','upsamplingStageB','processingStage','nlFilterStrength','nlFilterRadius']},
  liquid:{label:'Liquid',keys:['waves','choppiness','swell','windSea','capillary','current']},
  reflection:{label:'Reflection',keys:['bodyGain','reflectionGain','fresnelBias','fresnelEdge','fresnelShape','roughness','envRotation','envGain','envBlur','showSky','bodyColor']},
  pattern:{label:'Pattern',keys:['patternScale','perlinGain','billowGain','ridgeGain','normalStrength','energyEmission','foamAmount','foamLight','foamBreakup','foamStreaks','foamPersistence','foamBlend','foamColor']},
  atmosphere:{label:'Atmosphere',keys:['drawDistance','fogBand','fogStrength','cloudCoverage','cloudOpacity','cloudScale','cloudDrift','cloudBlend']},
  lighting:{label:'Lighting',keys:['ambientEnabled','ambientColor','ambientIntensity','emissiveEnabled','emissiveColor','emissiveIntensity','spotEnabled','spotColor','spotIntensity','spotAzimuth','spotElevation','spotFocus']},
  geometry:{label:'Geometry',keys:['meshAsset','meshScale','meshWeldEpsilon','meshTargetEdge','meshCurvatureAngle','meshSubdivideLevels','meshSmoothIterations','meshSmoothStrength','meshSpikeThreshold','meshSpikeMode','meshHardEdgeAngle','meshTriangleCap','meshRetessellate','meshPreserveBoundary','meshPreserveHardEdges']},
  projection:{label:'Projection',keys:['projectionA','projectionB','projectionMix','projectionMaskSource','projectionScaleX','projectionScaleY','projectionScaleZ','projectionRotationX','projectionRotationY','projectionRotationZ','projectionOffsetX','projectionOffsetY','projectionOffsetZ','projectionOriginX','projectionOriginY','projectionOriginZ','projectionSharpness','projectionWarp','projectionDriftX','projectionDriftY','projectionWrap','projectionQuantize','projectionDisplacement','projectionDisplacementSafety','projectorFov','displacementProjection','patternProjection','foamProjection','emissionProjection','reflectionProjection','maskProjection']},
  output:{label:'Output',keys:['sceneMode','meshResolution','renderScale','displayFPS','exposure','contrast','bloom','bloomThreshold','bloomRadius','sharpen']},
  modulation:{label:'Modulation',keys:['modEnabled','modAmplitude','modHz','modWidthMin','modWidthMax','modOffset','modWave','modTargets']},
  lut:{label:'LUT',keys:['lutSlot','lutRandomScale'],palette:true},
  noixture:{label:'SkyNoixture',keys:['noixtureEnabled','noixtureMode','noixtureBlend','noixtureAmount','noixtureScale','noixtureContrast','noixtureDrift','noixtureColor']},
  mixer:{label:'SkyMixer',keys:['mixerEnabled','mixerBlend','mixerMix']},
  mask:{label:'Mask',keys:['maskEnabled','maskSourceA','maskSourceB','maskMixMode','maskSourceMix','maskBrightness','maskContrast','maskGamma','maskThreshold','maskSoftness','maskScale','maskDrift','maskInvert','maskMixer','maskNoixture','maskClouds','maskFoam']}
});
export const PANEL_IDS=Object.freeze(Object.keys(PANEL_DEFINITIONS));
export const SUBMENU_DEFINITIONS=Object.freeze({
  ...KINETIC_SUBMENUS,
  'skysynth-synth':{label:'SYNTH',globalPanel:'skysynth',keys:['freqY','freqX','speed','hueShift','radius','diagonal','warp','fieldContrast','radiance']},
  'skysynth-sampling':{label:'SAMPLING / ENV',globalPanel:'skysynth',keys:['envMode','sourceWidth','envMapWidth','generatorFPS','spatialSmooth','temporalSmooth','upsampling','upsamplingStageB','processingStage','nlFilterStrength','nlFilterRadius','envRotation','envGain','envBlur']},
  modulation:{label:'MODULATION',globalPanel:'skysynth',keys:[...PANEL_DEFINITIONS.modulation.keys]},
  noixture:{label:'SKYNOIXTURE',globalPanel:'skysynth',keys:[...PANEL_DEFINITIONS.noixture.keys]},
  mixer:{label:'SKYMIXER',globalPanel:'skysynth',keys:[...PANEL_DEFINITIONS.mixer.keys]},
  mask:{label:'MASK',globalPanel:'skysynth',keys:[...PANEL_DEFINITIONS.mask.keys]},
  'surface-motion':{label:'MOTION',globalPanel:'surface',keys:['sceneMode',...PANEL_DEFINITIONS.liquid.keys]},
  'surface-geometry':{label:'GEOMETRY / IMPORT',globalPanel:'surface',keys:[...PANEL_DEFINITIONS.geometry.keys]},
  'surface-projection':{label:'PROJECTION',globalPanel:'surface',keys:[...PANEL_DEFINITIONS.projection.keys]},
  'surface-material':{label:'MATERIAL',globalPanel:'surface',keys:PANEL_DEFINITIONS.reflection.keys.filter(k=>!['envRotation','envGain','envBlur'].includes(k))},
  'surface-pattern':{label:'SURFACE',globalPanel:'surface',keys:[...PANEL_DEFINITIONS.pattern.keys]},
  'surface-atmosphere':{label:'ATMOSPHERE',globalPanel:'surface',keys:[...PANEL_DEFINITIONS.atmosphere.keys]},
  'surface-lighting':{label:'LIGHTING',globalPanel:'surface',keys:[...PANEL_DEFINITIONS.lighting.keys]},
  'surface-output':{label:'OUTPUT',globalPanel:'surface',keys:PANEL_DEFINITIONS.output.keys.filter(k=>k!=='sceneMode')},
  lut:{label:'LUT',globalPanel:'lut',keys:[...PANEL_DEFINITIONS.lut.keys]}
});
export const SUBMENU_IDS=Object.freeze(Object.keys(SUBMENU_DEFINITIONS));
export const PANEL_GLOBAL_IDS=Object.freeze(['skysynth','surface','lut']);
const p=(description,settings,palette)=>Object.freeze({...description?{description}:null,settings:Object.freeze({...settings}),...(palette?{palette:Object.freeze([...palette])}:null)});
export const BUILTIN_PANEL_PRESETS=Object.freeze({
  ...KINETIC_PANEL_PRESETS,
  proceduralClouds:Object.freeze({
    'Off':p('Dedicated procedural cloud volume disabled.',{procCloudEnabled:false,procCloudEditActive:false}),
    'Reference Cloud':p('The original playground-style baseline inside a movable Xenofield world box.',{procCloudEnabled:true,procCloudDensity:1,procCloudCoverage:.8,procCloudScale:3.75,procCloudAltitude:.5,procCloudDetail:1,procCloudWindSpeed:.05,procCloudSkipLight:false,procCloudRaySteps:48,procCloudLightSteps:4,procCloudShadowDark:5,procCloudSunIntensity:17,procCloudHeight:1.5,procCloudCacheRes:96,procCloudCacheUpdate:2,procCloudCacheSmooth:0,procCloudOpacity:1}),
    'VIDEO · CELL MEMBRANES':p('Reference-video end-stop state: enormous hollow cellular sheets, tunnels and scalloped membranes.',{procCloudEnabled:true,procCloudDensity:4,procCloudCoverage:1,procCloudScale:5.85,procCloudAltitude:.58,procCloudDetail:0,procCloudWindSpeed:.15,procCloudSkipLight:false,procCloudRaySteps:16,procCloudLightSteps:1,procCloudShadowDark:20,procCloudSunIntensity:20,procCloudHeight:5,procCloudCacheRes:128,procCloudCacheUpdate:1,procCloudCacheSmooth:.95,procCloudOpacity:1}),
    'Thin Cellular Towers':p('Low-detail cellular field biased toward tall perforated towers and thin walls.',{procCloudEnabled:true,procCloudDensity:3.6,procCloudCoverage:1,procCloudScale:7.2,procCloudAltitude:.44,procCloudDetail:0,procCloudWindSpeed:.1,procCloudRaySteps:20,procCloudLightSteps:1,procCloudShadowDark:18,procCloudSunIntensity:18,procCloudHeight:5,procCloudCacheRes:96,procCloudCacheUpdate:2,procCloudCacheSmooth:.9}),
    'Soft Rolling Mass':p('Smoother cloud-like volume with more light samples and slower cache motion.',{procCloudEnabled:true,procCloudDensity:1.5,procCloudCoverage:.74,procCloudScale:3.1,procCloudAltitude:.63,procCloudDetail:2,procCloudWindSpeed:.035,procCloudRaySteps:56,procCloudLightSteps:5,procCloudShadowDark:6,procCloudSunIntensity:11,procCloudHeight:2.2,procCloudCacheRes:96,procCloudCacheUpdate:3,procCloudCacheSmooth:.75}),
    'Skip-Light Porcelain':p('Lighting bypass exposes the density graph itself as pale carved volumetric matter.',{procCloudEnabled:true,procCloudDensity:3.2,procCloudCoverage:.92,procCloudScale:4.9,procCloudAltitude:.5,procCloudDetail:.5,procCloudWindSpeed:.08,procCloudSkipLight:true,procCloudRaySteps:24,procCloudLightSteps:1,procCloudShadowDark:20,procCloudSunIntensity:9,procCloudHeight:4.2,procCloudCacheRes:96,procCloudCacheUpdate:2,procCloudCacheSmooth:.9})
  }),
  skysynth:Object.freeze({
    'Soft Nebula':p('Slow smooth synth field with a dense reconstruction target.',{envMode:'plasma',freqY:.18,freqX:.26,speed:.18,hueShift:6,radius:.21,diagonal:.18,warp:.15,fieldContrast:1.3,radiance:3.7,sourceWidth:96,envMapWidth:192,generatorFPS:24,spatialSmooth:.55,temporalSmooth:.12,upsampling:'bicubic',upsamplingStageB:'catmull-rom',processingStage:'mid',nlFilterStrength:.14,nlFilterRadius:1}),
    'Hard Caustics':p('Sharper, higher energy structure with two-stage reconstruction.',{freqY:.31,freqX:.42,speed:.46,hueShift:11,radius:.12,diagonal:.34,warp:.38,fieldContrast:2.05,radiance:5.4,sourceWidth:96,envMapWidth:256,generatorFPS:30,spatialSmooth:.22,temporalSmooth:.05,upsampling:'lanczos2',upsamplingStageB:'catmull-rom',processingStage:'post',nlFilterStrength:.08,nlFilterRadius:1}),
    'Velvet Aurora':p('Very soft broad gradients and restrained shimmer.',{freqY:.09,freqX:.16,speed:.11,hueShift:4,radius:.28,diagonal:.08,warp:.08,fieldContrast:1.0,radiance:3.0,sourceWidth:64,envMapWidth:192,generatorFPS:18,spatialSmooth:.7,temporalSmooth:.16,upsampling:'smooth',upsamplingStageB:'bicubic',processingStage:'post',nlFilterStrength:.22,nlFilterRadius:2}),
    'Glitch Lattice':p('Angular energetic field for metallic or cyber looks.',{freqY:.38,freqX:.39,speed:.61,hueShift:18,radius:.1,diagonal:.41,warp:.52,fieldContrast:2.45,radiance:6.2,sourceWidth:64,envMapWidth:256,generatorFPS:36,spatialSmooth:.1,temporalSmooth:.03,upsampling:'nearest',upsamplingStageB:'lanczos2',processingStage:'pre',nlFilterStrength:.04,nlFilterRadius:0}),
    'ACID CELLS':p('Legacy alias for a sharp high-energy synthetic field.',{freqY:.38,freqX:.39,speed:.61,hueShift:18,radius:.1,diagonal:.41,warp:.52,fieldContrast:2.45,radiance:6.2,sourceWidth:64,envMapWidth:256,generatorFPS:36,spatialSmooth:.1,temporalSmooth:.03,upsampling:'nearest',upsamplingStageB:'lanczos2',processingStage:'pre',nlFilterStrength:.04,nlFilterRadius:0}),
    'Economy Preview':p('Balanced low CPU baseline intended for stable interaction.',{freqY:.22,freqX:.32,speed:.3,hueShift:7,radius:.24,diagonal:.25,warp:.18,fieldContrast:1.5,radiance:4.5,sourceWidth:80,envMapWidth:160,generatorFPS:20,spatialSmooth:.45,temporalSmooth:.08,upsampling:'linear',upsamplingStageB:'none',processingStage:'none',nlFilterStrength:0,nlFilterRadius:0}),
    'Cobalt Reactor':p('Ion-Orchard-derived cobalt reactor field with hard internal structure.',{envMode:'plasma',freqY:.33,freqX:.46,speed:.48,hueShift:14,radius:.16,diagonal:.39,warp:.48,fieldContrast:2.55,radiance:5.6,sourceWidth:64,envMapWidth:256,generatorFPS:30,spatialSmooth:.12,temporalSmooth:.035,upsampling:'nearest',upsamplingStageB:'catmull-rom',processingStage:'post',nlFilterStrength:.05,nlFilterRadius:1}),
    'Petroleum Rift':p('Dense warped cellular field tuned for petroleum / particulate palettes.',{envMode:'plasma',freqY:.41,freqX:.29,speed:.39,hueShift:9,radius:.36,diagonal:.31,warp:.68,fieldContrast:2.7,radiance:5.1,sourceWidth:64,envMapWidth:256,generatorFPS:24,spatialSmooth:.16,temporalSmooth:.05,upsampling:'nearest',upsamplingStageB:'bicubic',processingStage:'mid',nlFilterStrength:.08,nlFilterRadius:1}),
    'Copper Storm':p('High-contrast warm storm field with rapid phase shear.',{envMode:'plasma',freqY:.27,freqX:.52,speed:.55,hueShift:8,radius:.2,diagonal:.48,warp:.4,fieldContrast:2.65,radiance:5.8,sourceWidth:64,envMapWidth:256,generatorFPS:30,spatialSmooth:.1,temporalSmooth:.03,upsampling:'nearest',upsamplingStageB:'lanczos2',processingStage:'post',nlFilterStrength:.04,nlFilterRadius:1}),
    'Cryo Prism':p('Cool prismatic blocks with sharp boundaries and slow drift.',{envMode:'plasma',freqY:.21,freqX:.37,speed:.28,hueShift:10,radius:.23,diagonal:.34,warp:.44,fieldContrast:2.45,radiance:5.0,sourceWidth:64,envMapWidth:256,generatorFPS:24,spatialSmooth:.14,temporalSmooth:.04,upsampling:'nearest',upsamplingStageB:'catmull-rom',processingStage:'post',nlFilterStrength:.06,nlFilterRadius:1}),
    'Magnetar Pulse':p('Magenta-blue ion field with compact high-energy cells.',{envMode:'plasma',freqY:.44,freqX:.36,speed:.59,hueShift:20,radius:.14,diagonal:.52,warp:.55,fieldContrast:2.8,radiance:6.1,sourceWidth:64,envMapWidth:256,generatorFPS:30,spatialSmooth:.08,temporalSmooth:.025,upsampling:'nearest',upsamplingStageB:'catmull-rom',processingStage:'post',nlFilterStrength:.04,nlFilterRadius:1})
  }),
  liquid:Object.freeze({
    'Glass Swell':p('',{waves:1.05,choppiness:.88,swell:1.1,windSea:.72,capillary:.8,current:.08}),
    'Open Sea':p('',{waves:1.4,choppiness:1.2,swell:1.05,windSea:1.2,capillary:1.4,current:.24}),
    'Needle Chop':p('',{waves:1.75,choppiness:1.56,swell:.8,windSea:1.5,capillary:1.95,current:.33}),
    'Slow Mercury':p('',{waves:.82,choppiness:.62,swell:1.35,windSea:.4,capillary:.35,current:.03}),
    'Orbital Field':p('',{waves:.34,choppiness:.42,swell:.2,windSea:.14,capillary:.08,current:0}),
    'Ion Chop':p('Ion Orchard motion with more small-scale directional fracture.',{waves:1.52,choppiness:1.42,swell:.92,windSea:1.48,capillary:1.78,current:.28}),
    'Ion Surge':p('High-energy rolling surface that retains broad wave shape.',{waves:1.82,choppiness:1.5,swell:1.22,windSea:1.42,capillary:1.62,current:.34}),
    'Ion Mercury':p('Smoother heavy liquid with enough capillary detail to carry neon linework.',{waves:1.18,choppiness:1.08,swell:1.3,windSea:.86,capillary:1.18,current:.16})
  }),
  reflection:Object.freeze({
    'Kinetic Laboratory':p('Low-gain environment leaves headroom for separate emissive and absorptive fields.',{bodyGain:.1,reflectionGain:.75,fresnelBias:.12,fresnelEdge:.98,fresnelShape:.8,roughness:.15,envRotation:0,envGain:.1,envBlur:1,showSky:true,bodyColor:'03070D'}),
    'Dark Chrome':p('',{bodyGain:.14,reflectionGain:1.35,fresnelBias:.12,fresnelEdge:.98,fresnelShape:.8,roughness:.08,envGain:1.1,envBlur:0,showSky:true,bodyColor:'061018'}),
    'Silk Water':p('',{bodyGain:.3,reflectionGain:1.05,fresnelBias:.3,fresnelEdge:.88,fresnelShape:.62,roughness:.18,envGain:1,envBlur:.2,showSky:true,bodyColor:'0A1830'}),
    'Fogged Metal':p('',{bodyGain:.18,reflectionGain:.95,fresnelBias:.16,fresnelEdge:.84,fresnelShape:.56,roughness:.42,envGain:.9,envBlur:1.1,showSky:true,bodyColor:'101820'}),
    'Night Void':p('',{bodyGain:.08,reflectionGain:1.5,fresnelBias:.08,fresnelEdge:1,fresnelShape:.92,roughness:.04,envGain:1.18,envBlur:0,showSky:false,bodyColor:'04070C'}),
    'HDRI Driver':p('',{bodyGain:.2,reflectionGain:1.2,fresnelBias:.24,fresnelEdge:.92,fresnelShape:.74,roughness:.1,envGain:1,envBlur:.15,showSky:true,bodyColor:'081018'}),
    'Ion Chrome Blue':p('Dark ion chrome preserving deep troughs and sharp environment colour.',{bodyGain:.11,reflectionGain:1.55,fresnelBias:.10,fresnelEdge:1,fresnelShape:.9,roughness:.055,envGain:1.08,envBlur:0,showSky:true,bodyColor:'030817'}),
    'Oil Chrome':p('Near-black petroleum material with coloured grazing reflection.',{bodyGain:.09,reflectionGain:1.42,fresnelBias:.08,fresnelEdge:.98,fresnelShape:.88,roughness:.09,envGain:.98,envBlur:.05,showSky:true,bodyColor:'020C0A'}),
    'Copper Mirror':p('Dark copper-biased reflective body with low face washout.',{bodyGain:.13,reflectionGain:1.48,fresnelBias:.11,fresnelEdge:.97,fresnelShape:.84,roughness:.07,envGain:1.02,envBlur:0,showSky:true,bodyColor:'160704'}),
    'Opal Chrome':p('Dark neutral chrome that lets opaline / magnetar LUTs dominate.',{bodyGain:.12,reflectionGain:1.5,fresnelBias:.12,fresnelEdge:.99,fresnelShape:.86,roughness:.08,envGain:1.04,envBlur:.05,showSky:true,bodyColor:'070713'})
  }),
  pattern:Object.freeze({
    'Thread Foam':p('',{patternScale:.18,perlinGain:.7,billowGain:.9,ridgeGain:1.2,normalStrength:.42,energyEmission:.55,foamAmount:.65,foamLight:1.2,foamBreakup:1.1,foamStreaks:.8,foamPersistence:.7,foamBlend:'normal',foamColor:'CFFFE8'}),
    'Biolume Veins':p('',{patternScale:.14,perlinGain:.42,billowGain:.7,ridgeGain:1.55,normalStrength:.36,energyEmission:1.2,foamAmount:.42,foamLight:2.3,foamBreakup:.76,foamStreaks:.6,foamPersistence:.84,foamBlend:'screen',foamColor:'87F0FF'}),
    'Storm Lace':p('',{patternScale:.22,perlinGain:1.05,billowGain:1.18,ridgeGain:1.52,normalStrength:.56,energyEmission:.4,foamAmount:.92,foamLight:1.5,foamBreakup:1.4,foamStreaks:1.4,foamPersistence:.62,foamBlend:'hard-light',foamColor:'F4FFF8'}),
    'Signal Wakes':p('',{patternScale:.11,perlinGain:.3,billowGain:.45,ridgeGain:.92,normalStrength:.24,energyEmission:1.6,foamAmount:.2,foamLight:2.8,foamBreakup:.42,foamStreaks:.22,foamPersistence:.35,foamBlend:'addition',foamColor:'72DFFF'}),
    'Dry Noise':p('',{patternScale:.2,perlinGain:1.15,billowGain:.35,ridgeGain:.6,normalStrength:.64,energyEmission:.18,foamAmount:.14,foamLight:.65,foamBreakup:1.7,foamStreaks:.08,foamPersistence:.15,foamBlend:'normal',foamColor:'D2E6FF'}),
    'Ion Filaments':p('High-contrast Ion Orchard surface filaments with dark gaps and emissive seams.',{patternScale:.16,perlinGain:.62,billowGain:.88,ridgeGain:1.78,normalStrength:.78,energyEmission:1.15,foamAmount:.58,foamLight:1.75,foamBreakup:1.65,foamStreaks:1.35,foamPersistence:.5,foamBlend:'screen',foamColor:'A8F5FF'}),
    'Petroleum Filaments':p('Cellular oily filaments with sparse bright particulate-like highlights.',{patternScale:.22,perlinGain:.92,billowGain:1.18,ridgeGain:1.62,normalStrength:.8,energyEmission:.85,foamAmount:.46,foamLight:1.55,foamBreakup:1.8,foamStreaks:.92,foamPersistence:.42,foamBlend:'addition',foamColor:'B8FF72'}),
    'Cryo Lattice':p('Cold prismatic ridges with high normal relief and restrained foam.',{patternScale:.18,perlinGain:.52,billowGain:.74,ridgeGain:1.92,normalStrength:.84,energyEmission:.72,foamAmount:.42,foamLight:1.5,foamBreakup:1.55,foamStreaks:1.12,foamPersistence:.44,foamBlend:'overlay',foamColor:'B4F9FF'}),
    'Copper Seams':p('Warm metallic seams and hard ridge breakup.',{patternScale:.15,perlinGain:.46,billowGain:.72,ridgeGain:2.05,normalStrength:.86,energyEmission:1.0,foamAmount:.34,foamLight:1.65,foamBreakup:1.7,foamStreaks:1.18,foamPersistence:.38,foamBlend:'hard-light',foamColor:'FFD091'}),
    'Magenta Mesh':p('Dense magnetar mesh with dark negative space and high-energy linework.',{patternScale:.17,perlinGain:.4,billowGain:.8,ridgeGain:2.18,normalStrength:.9,energyEmission:1.45,foamAmount:.38,foamLight:2.0,foamBreakup:1.8,foamStreaks:1.45,foamPersistence:.36,foamBlend:'screen',foamColor:'FF9AF3'}),
    'Phase Filaments':p('Slightly restrained version of Signal Wakes for Phase Difference.',{patternScale:.12,perlinGain:.32,billowGain:.52,ridgeGain:1.18,normalStrength:.38,energyEmission:1.35,foamAmount:.24,foamLight:2.25,foamBreakup:.72,foamStreaks:.42,foamPersistence:.3,foamBlend:'addition',foamColor:'8CFFE6'})
  }),
  atmosphere:Object.freeze({
    'Kinetic Clear':p('Keep the cached 3D field distinct from the legacy 2D sky clouds.',{drawDistance:980,fogBand:300,fogStrength:.2,cloudCoverage:0,cloudOpacity:0,cloudScale:1,cloudDrift:.04,cloudBlend:'screen'}),
    'Open Horizon':p('',{drawDistance:1180,fogBand:420,fogStrength:.28,cloudCoverage:.36,cloudOpacity:.26,cloudScale:1.2,cloudDrift:.07,cloudBlend:'screen'}),
    'Sealed Basin':p('',{drawDistance:760,fogBand:300,fogStrength:.72,cloudCoverage:.58,cloudOpacity:.42,cloudScale:1.05,cloudDrift:.05,cloudBlend:'soft-light'}),
    'Whiteout':p('',{drawDistance:520,fogBand:240,fogStrength:.96,cloudCoverage:.82,cloudOpacity:.7,cloudScale:1.5,cloudDrift:.14,cloudBlend:'screen'}),
    'High Atmosphere':p('',{drawDistance:1450,fogBand:520,fogStrength:.18,cloudCoverage:.22,cloudOpacity:.16,cloudScale:2.2,cloudDrift:.03,cloudBlend:'overlay'}),
    'Electric Weather':p('',{drawDistance:930,fogBand:360,fogStrength:.4,cloudCoverage:.63,cloudOpacity:.48,cloudScale:.86,cloudDrift:.16,cloudBlend:'hard-light'}),
    'Deep Neon Horizon':p('Ion-style atmosphere: dark distance seal with colourful structured clouds.',{drawDistance:980,fogBand:380,fogStrength:.34,cloudCoverage:.5,cloudOpacity:.28,cloudScale:1.08,cloudDrift:.11,cloudBlend:'overlay'}),
    'Black Rift':p('Very dark atmospheric closure leaving neon cells exposed.',{drawDistance:860,fogBand:340,fogStrength:.46,cloudCoverage:.56,cloudOpacity:.3,cloudScale:.92,cloudDrift:.09,cloudBlend:'multiply'}),
    'Cobalt Vault':p('Cool high-contrast vaulted sky with limited whitening.',{drawDistance:1080,fogBand:420,fogStrength:.3,cloudCoverage:.44,cloudOpacity:.24,cloudScale:1.22,cloudDrift:.08,cloudBlend:'soft-light'}),
    'Copper Squall':p('Warm high-frequency cloud breakup with darker interstices.',{drawDistance:900,fogBand:360,fogStrength:.38,cloudCoverage:.58,cloudOpacity:.3,cloudScale:1.0,cloudDrift:.15,cloudBlend:'overlay'})
  }),
  lighting:Object.freeze({
    'Neutral Fill':p('',{ambientEnabled:true,ambientColor:'A9C6FF',ambientIntensity:.22,emissiveEnabled:true,emissiveColor:'9BE8FF',emissiveIntensity:.45,spotEnabled:true,spotColor:'FFF1C6',spotIntensity:.55,spotAzimuth:28,spotElevation:42,spotFocus:.52}),
    'Moonlit':p('',{ambientEnabled:true,ambientColor:'94B6FF',ambientIntensity:.36,emissiveEnabled:true,emissiveColor:'8FE7FF',emissiveIntensity:.28,spotEnabled:false,spotColor:'FFFFFF',spotIntensity:0,spotAzimuth:0,spotElevation:40,spotFocus:.5}),
    'Biolume Core':p('',{ambientEnabled:true,ambientColor:'7CA2E0',ambientIntensity:.14,emissiveEnabled:true,emissiveColor:'76F0FF',emissiveIntensity:1.2,spotEnabled:false,spotColor:'FFFFFF',spotIntensity:0,spotAzimuth:0,spotElevation:32,spotFocus:.4}),
    'Hard Spot':p('',{ambientEnabled:true,ambientColor:'B0B7D0',ambientIntensity:.1,emissiveEnabled:true,emissiveColor:'C8F4FF',emissiveIntensity:.22,spotEnabled:true,spotColor:'FFF0B8',spotIntensity:1.35,spotAzimuth:18,spotElevation:56,spotFocus:.82}),
    'Noir Edge':p('',{ambientEnabled:true,ambientColor:'5A6A88',ambientIntensity:.08,emissiveEnabled:false,emissiveColor:'9BE8FF',emissiveIntensity:0,spotEnabled:true,spotColor:'C7D4FF',spotIntensity:.92,spotAzimuth:-36,spotElevation:18,spotFocus:.9}),
    'Warm Dawn':p('',{ambientEnabled:true,ambientColor:'FFD9B0',ambientIntensity:.24,emissiveEnabled:true,emissiveColor:'FFD7A6',emissiveIntensity:.18,spotEnabled:true,spotColor:'FFE5B4',spotIntensity:.8,spotAzimuth:52,spotElevation:24,spotFocus:.48}),
    'Ion Edge':p('Cold grazing edge light with low ambient fill.',{ambientEnabled:true,ambientColor:'42658A',ambientIntensity:.08,emissiveEnabled:true,emissiveColor:'6CEBFF',emissiveIntensity:.55,spotEnabled:true,spotColor:'A6E7FF',spotIntensity:1.05,spotAzimuth:-28,spotElevation:24,spotFocus:.88}),
    'Cryo Edge':p('Cyan-violet edge lighting for cryogenic surfaces.',{ambientEnabled:true,ambientColor:'436AA0',ambientIntensity:.1,emissiveEnabled:true,emissiveColor:'8FF6FF',emissiveIntensity:.62,spotEnabled:true,spotColor:'D8E7FF',spotIntensity:.9,spotAzimuth:36,spotElevation:18,spotFocus:.84}),
    'Toxic Edge':p('Green-biased emissive and hard side light.',{ambientEnabled:true,ambientColor:'334D39',ambientIntensity:.07,emissiveEnabled:true,emissiveColor:'9EFF6B',emissiveIntensity:.72,spotEnabled:true,spotColor:'D9FF9A',spotIntensity:.88,spotAzimuth:-42,spotElevation:20,spotFocus:.86}),
    'Copper Edge':p('Warm hard grazing spot over a dark surface.',{ambientEnabled:true,ambientColor:'4D3026',ambientIntensity:.07,emissiveEnabled:true,emissiveColor:'FF8D55',emissiveIntensity:.52,spotEnabled:true,spotColor:'FFD39B',spotIntensity:1.0,spotAzimuth:48,spotElevation:20,spotFocus:.88}),
    'Magenta Edge':p('Magenta/cyan dual impression via emissive and cool spot.',{ambientEnabled:true,ambientColor:'40264F',ambientIntensity:.08,emissiveEnabled:true,emissiveColor:'FF69D8',emissiveIntensity:.75,spotEnabled:true,spotColor:'6EDBFF',spotIntensity:.92,spotAzimuth:-34,spotElevation:26,spotFocus:.86})
  }),
  geometry:Object.freeze({
    'Default Surface':p('No imported-mesh conditioning is needed for the planar liquid surface.',{meshAsset:'showcase',meshScale:100,meshWeldEpsilon:.002,meshTargetEdge:12,meshCurvatureAngle:35,meshSubdivideLevels:1,meshSmoothIterations:0,meshSmoothStrength:.2,meshSpikeThreshold:2.8,meshSpikeMode:'leave',meshHardEdgeAngle:55,meshTriangleCap:350000,meshRetessellate:false,meshPreserveBoundary:true,meshPreserveHardEdges:true}),
    'Showcase Knot':p('Conditioning tuned for the built-in torus-knot projection demonstrator.',{meshAsset:'showcase',meshScale:105,meshWeldEpsilon:.001,meshTargetEdge:9,meshCurvatureAngle:35,meshSubdivideLevels:1,meshSmoothIterations:1,meshSmoothStrength:.12,meshSpikeThreshold:3.2,meshSpikeMode:'relax',meshHardEdgeAngle:72,meshTriangleCap:450000,meshRetessellate:true,meshPreserveBoundary:true,meshPreserveHardEdges:true}),
    'D20 Conditioned':p('Uses the supplied detailed D20 STL directly, preserving engraved/bevel geometry and hard facet normals while leaving retessellation available as an optional experiment.',{meshAsset:'d20',meshScale:100,meshWeldEpsilon:.001,meshTargetEdge:7,meshCurvatureAngle:35,meshSubdivideLevels:1,meshSmoothIterations:0,meshSmoothStrength:.08,meshSpikeThreshold:4.5,meshSpikeMode:'leave',meshHardEdgeAngle:28,meshTriangleCap:500000,meshRetessellate:false,meshPreserveBoundary:true,meshPreserveHardEdges:true}),
    'Imported Adaptive':p('General-purpose imported mesh conditioning with mild spike relaxation.',{meshAsset:'imported',meshScale:100,meshWeldEpsilon:.002,meshTargetEdge:10,meshCurvatureAngle:35,meshSubdivideLevels:2,meshSmoothIterations:1,meshSmoothStrength:.18,meshSpikeThreshold:2.8,meshSpikeMode:'relax',meshHardEdgeAngle:55,meshTriangleCap:500000,meshRetessellate:true,meshPreserveBoundary:true,meshPreserveHardEdges:true}),
    'Dense Smooth':p('High-density retessellation with controlled smoothing for strong displacement.',{meshAsset:'imported',meshScale:100,meshWeldEpsilon:.001,meshTargetEdge:6,meshCurvatureAngle:35,meshSubdivideLevels:3,meshSmoothIterations:2,meshSmoothStrength:.22,meshSpikeThreshold:2.4,meshSpikeMode:'clamp',meshHardEdgeAngle:65,meshTriangleCap:900000,meshRetessellate:true,meshPreserveBoundary:true,meshPreserveHardEdges:true})
  }),
  projection:Object.freeze({
    'Planar Legacy':p('Original XZ projected field; preserves the deliberately wrong planar-wrap character.',{projectionA:'planar-xz',projectionB:'planar-xz',projectionMix:0,projectionMaskSource:'constant',projectionScaleX:1,projectionScaleY:1,projectionScaleZ:1,projectionRotationX:0,projectionRotationY:0,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:4,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:0,projectionQuantize:6,projectionDisplacement:4,projectionDisplacementSafety:.7,projectorFov:70,displacementProjection:'master',patternProjection:'master',foamProjection:'master',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'master'}),
    'Octahedral Planet':p('Low-distortion directional mapping selected for Orbital Planet.',{projectionA:'octahedral',projectionB:'equal-area',projectionMix:.12,projectionMaskSource:'normal-up',projectionScaleX:1,projectionScaleY:1,projectionScaleZ:1,projectionRotationX:0,projectionRotationY:12,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:5,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.08,projectionQuantize:8,projectionDisplacement:4.5,projectionDisplacementSafety:.62,projectorFov:70,displacementProjection:'master',patternProjection:'master',foamProjection:'octahedral',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'master'}),
    'Triplanar Volume':p('Triplanar/object-volume blend designed to expose curvature on arbitrary geometry.',{projectionA:'triplanar',projectionB:'object3d',projectionMix:.32,projectionMaskSource:'ridge',projectionScaleX:1.25,projectionScaleY:1.25,projectionScaleZ:1.25,projectionRotationX:18,projectionRotationY:32,projectionRotationZ:8,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:6,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.32,projectionQuantize:8,projectionDisplacement:6.5,projectionDisplacementSafety:.72,projectorFov:70,displacementProjection:'triplanar',patternProjection:'object3d',foamProjection:'tangent-local',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'octahedral'}),
    'D20 Facet Storm':p('Cubemap/octahedral hybrid that preserves D20 facets and forces patterns across face transitions.',{projectionA:'cubemap',projectionB:'octahedral',projectionMix:.46,projectionMaskSource:'ridge',projectionScaleX:1.4,projectionScaleY:1.4,projectionScaleZ:1.4,projectionRotationX:17,projectionRotationY:34,projectionRotationZ:9,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:12,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.45,projectionQuantize:6,projectionDisplacement:5.2,projectionDisplacementSafety:.48,projectorFov:62,displacementProjection:'axis-dominant',patternProjection:'cubemap',foamProjection:'quantized-normal',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'octahedral'}),
    'Cylindrical Shear':p('Cylindrical field with tangent-local foam.',{projectionA:'cylindrical',projectionB:'tangent-local',projectionMix:.24,projectionMaskSource:'perlin',projectionScaleX:1,projectionScaleY:1.6,projectionScaleZ:1,projectionRotationX:0,projectionRotationY:0,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:4,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.18,projectionQuantize:8,projectionDisplacement:5,projectionDisplacementSafety:.65,projectorFov:70,displacementProjection:'cylindrical',patternProjection:'master',foamProjection:'tangent-local',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'master'}),
    'Reflection Warp':p('Reflection-vector and camera projection blended into a view-responsive energy skin.',{projectionA:'reflection-vector',projectionB:'camera',projectionMix:.38,projectionMaskSource:'normal-up',projectionScaleX:1,projectionScaleY:1,projectionScaleZ:1,projectionRotationX:0,projectionRotationY:0,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:4,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.22,projectionQuantize:8,projectionDisplacement:2.8,projectionDisplacementSafety:.55,projectorFov:75,displacementProjection:'radial',patternProjection:'reflection-vector',foamProjection:'camera',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'reflection-vector'}),
    'Polar Crush':p('Intentionally pathological spherical compression.',{projectionA:'polar-crush',projectionB:'spherical',projectionMix:.18,projectionMaskSource:'radial',projectionScaleX:1,projectionScaleY:1,projectionScaleZ:1,projectionRotationX:0,projectionRotationY:0,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:0,projectionSharpness:4,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.28,projectionQuantize:8,projectionDisplacement:4.5,projectionDisplacementSafety:.55,projectorFov:70,displacementProjection:'master',patternProjection:'master',foamProjection:'master',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'master'}),
    'Projector Slice':p('Projector-space pattern with radial displacement and UV fallback.',{projectionA:'projector',projectionB:'uv',projectionMix:.16,projectionMaskSource:'perlin',projectionScaleX:1,projectionScaleY:1,projectionScaleZ:1,projectionRotationX:-18,projectionRotationY:25,projectionRotationZ:0,projectionOffsetX:0,projectionOffsetY:0,projectionOffsetZ:0,projectionOriginX:0,projectionOriginY:0,projectionOriginZ:160,projectionSharpness:4,projectionDriftX:0,projectionDriftY:0,projectionWrap:'none',projectionWarp:.12,projectionQuantize:8,projectionDisplacement:3.8,projectionDisplacementSafety:.6,projectorFov:58,displacementProjection:'radial',patternProjection:'projector',foamProjection:'uv',reflectionProjection:'environment',maskProjection:'master',emissionProjection:'projector'})
  }),
  output:Object.freeze({
    ...KINETIC_OUTPUT_PRESETS,
    'Balanced':p('',{sceneMode:'liquid',meshResolution:384,renderScale:1,displayFPS:60,exposure:1,contrast:1.06,bloom:.16,bloomThreshold:1.4,bloomRadius:2.5,sharpen:.12}),
    'Fast Preview':p('',{sceneMode:'liquid',meshResolution:256,renderScale:.8,displayFPS:45,exposure:.95,contrast:1.02,bloom:.1,bloomThreshold:1.6,bloomRadius:2,sharpen:.08}),
    'Hero Shot':p('',{sceneMode:'liquid',meshResolution:512,renderScale:1.15,displayFPS:60,exposure:1.06,contrast:1.12,bloom:.24,bloomThreshold:1.25,bloomRadius:3.1,sharpen:.16}),
    'Planetary':p('',{sceneMode:'planet',meshResolution:384,renderScale:1,displayFPS:60,exposure:1.02,contrast:1.05,bloom:.12,bloomThreshold:1.5,bloomRadius:2.4,sharpen:.1}),
    'Field Study':p('',{sceneMode:'field',meshResolution:320,renderScale:.9,displayFPS:60,exposure:.98,contrast:1.01,bloom:.08,bloomThreshold:1.7,bloomRadius:1.8,sharpen:.06}),
    'Mesh Showcase':p('',{sceneMode:'mesh',meshResolution:384,renderScale:1,displayFPS:60,exposure:.94,contrast:1.22,bloom:.12,bloomThreshold:1.4,bloomRadius:2.2,sharpen:.2}),
    'D20 Showcase':p('',{sceneMode:'mesh',meshResolution:384,renderScale:1,displayFPS:60,exposure:.9,contrast:1.28,bloom:.16,bloomThreshold:1.25,bloomRadius:2.5,sharpen:.22}),
    'Ion Punch':p('Contrast-forward output with low bloom to preserve neon microstructure.',{sceneMode:'liquid',meshResolution:448,renderScale:1,displayFPS:60,exposure:.78,contrast:1.42,bloom:.055,bloomThreshold:1.75,bloomRadius:1.4,sharpen:.3}),
    'Ion Hero':p('Higher-density ion output retaining dark troughs.',{sceneMode:'liquid',meshResolution:544,renderScale:1.08,displayFPS:60,exposure:.82,contrast:1.38,bloom:.07,bloomThreshold:1.65,bloomRadius:1.6,sharpen:.28}),
    'Ion Fast':p('Performance-oriented ion look without the washed-out output curve.',{sceneMode:'liquid',meshResolution:288,renderScale:.82,displayFPS:60,exposure:.8,contrast:1.34,bloom:.04,bloomThreshold:1.8,bloomRadius:1.2,sharpen:.22}),
    'Ion Planet':p('Planet mode with stronger contrast and much less bloom.',{sceneMode:'planet',meshResolution:448,renderScale:1,displayFPS:60,exposure:.8,contrast:1.38,bloom:.055,bloomThreshold:1.7,bloomRadius:1.5,sharpen:.24}),
    'Phase Punch':p('Small Phase Difference tuning: darker exposure, harder contrast, controlled glow.',{sceneMode:'liquid',meshResolution:512,renderScale:1.05,displayFPS:60,exposure:.84,contrast:1.32,bloom:.08,bloomThreshold:1.55,bloomRadius:1.8,sharpen:.24})
  }),
  modulation:Object.freeze({
    'Disabled':p('',{modEnabled:false,modAmplitude:25,modHz:.5,modWidthMin:-100,modWidthMax:100,modOffset:0,modWave:'sine',modTargets:['speed']}),
    'Slow Pulse':p('',{modEnabled:true,modAmplitude:18,modHz:.15,modWidthMin:-70,modWidthMax:70,modOffset:0,modWave:'sine',modTargets:['speed','radius']}),
    'Wander':p('',{modEnabled:true,modAmplitude:22,modHz:.32,modWidthMin:-100,modWidthMax:100,modOffset:0,modWave:'wander-noise',modTargets:['freqX','freqY','radius']}),
    'Pressure Sweep':p('',{modEnabled:true,modAmplitude:40,modHz:.22,modWidthMin:-30,modWidthMax:100,modOffset:0,modWave:'smooth-triangle',modTargets:['speed','hueShift']}),
    'Loop Drift':p('',{modEnabled:true,modAmplitude:28,modHz:.42,modWidthMin:-100,modWidthMax:100,modOffset:0,modWave:'loop-noise',modTargets:['freqX','speed','radius']})
  }),
  lut:Object.freeze({
    'Palette 0':p('',{lutSlot:0,lutRandomScale:25}),
    'Palette 1':p('',{lutSlot:1,lutRandomScale:25}),
    'Palette 2':p('',{lutSlot:2,lutRandomScale:25}),
    'Palette 3':p('',{lutSlot:3,lutRandomScale:25}),
    'Palette 4':p('',{lutSlot:4,lutRandomScale:25}),
    'Palette 5':p('',{lutSlot:5,lutRandomScale:25}),
    'Palette 6':p('',{lutSlot:6,lutRandomScale:25}),
    'Palette 7':p('',{lutSlot:7,lutRandomScale:25}),
    'Palette 8':p('',{lutSlot:8,lutRandomScale:25}),
    'Palette 9':p('',{lutSlot:9,lutRandomScale:25})
  }),
  noixture:Object.freeze({
    'Off':p('',{noixtureEnabled:false,noixtureMode:'billow',noixtureBlend:'soft-light',noixtureAmount:.28,noixtureScale:1,noixtureContrast:1.35,noixtureDrift:.12,noixtureColor:'D7E6FF'}),
    'Billow Veil':p('',{noixtureEnabled:true,noixtureMode:'billow',noixtureBlend:'soft-light',noixtureAmount:.24,noixtureScale:1.1,noixtureContrast:1.2,noixtureDrift:.08,noixtureColor:'C8DAFF'}),
    'Ridge Sparks':p('',{noixtureEnabled:true,noixtureMode:'ridge',noixtureBlend:'screen',noixtureAmount:.34,noixtureScale:1.8,noixtureContrast:1.8,noixtureDrift:.16,noixtureColor:'E6F5FF'}),
    'Weave Circuit':p('',{noixtureEnabled:true,noixtureMode:'weave',noixtureBlend:'overlay',noixtureAmount:.42,noixtureScale:1.45,noixtureContrast:1.6,noixtureDrift:.2,noixtureColor:'94C0FF'}),
    'Perlin Dust':p('',{noixtureEnabled:true,noixtureMode:'perlin',noixtureBlend:'difference',noixtureAmount:.18,noixtureScale:.68,noixtureContrast:1.05,noixtureDrift:.04,noixtureColor:'E8E8FF'}),
    'Ion Circuit':p('Ion Orchard style hard weave/overlay detail.',{noixtureEnabled:true,noixtureMode:'weave',noixtureBlend:'overlay',noixtureAmount:.52,noixtureScale:1.62,noixtureContrast:1.95,noixtureDrift:.18,noixtureColor:'8CEBFF'}),
    'Turbulent Ridges':p('Aggressive ridge modulation for petroleum and storm variants.',{noixtureEnabled:true,noixtureMode:'ridge',noixtureBlend:'hard-light',noixtureAmount:.36,noixtureScale:1.34,noixtureContrast:2.15,noixtureDrift:.13,noixtureColor:'D4FF98'})
  }),
  mixer:Object.freeze({
    'Synth Only':p('',{mixerEnabled:false,mixerBlend:'normal',mixerMix:0}),
    'Crossfade 35':p('',{mixerEnabled:true,mixerBlend:'normal',mixerMix:.35}),
    'Soft-Light 50':p('',{mixerEnabled:true,mixerBlend:'soft-light',mixerMix:.5}),
    'Screen 65':p('',{mixerEnabled:true,mixerBlend:'screen',mixerMix:.65}),
    'Difference 40':p('',{mixerEnabled:true,mixerBlend:'difference',mixerMix:.4})
  }),
  mask:Object.freeze({
    'Off':p('',{maskEnabled:false,maskSourceA:'mixed-luma',maskSourceB:'billow',maskMixMode:'mix',maskSourceMix:.5,maskBrightness:0,maskContrast:1,maskGamma:1,maskThreshold:0,maskSoftness:.5,maskScale:1,maskDrift:0,maskInvert:false,maskMixer:true,maskNoixture:false,maskClouds:false,maskFoam:false}),
    'Cloud Gate':p('',{maskEnabled:true,maskSourceA:'clouds',maskSourceB:'vertical',maskMixMode:'multiply',maskSourceMix:.5,maskBrightness:0,maskContrast:1.2,maskGamma:1,maskThreshold:.42,maskSoftness:.16,maskScale:1.2,maskDrift:.05,maskInvert:false,maskMixer:true,maskNoixture:false,maskClouds:true,maskFoam:false}),
    'Foam Bands':p('',{maskEnabled:true,maskSourceA:'ridge',maskSourceB:'weave',maskMixMode:'screen',maskSourceMix:.4,maskBrightness:0,maskContrast:1.55,maskGamma:.92,maskThreshold:.24,maskSoftness:.22,maskScale:1.8,maskDrift:.08,maskInvert:false,maskMixer:false,maskNoixture:false,maskClouds:false,maskFoam:true}),
    'Radial Vignette':p('',{maskEnabled:true,maskSourceA:'radial',maskSourceB:'constant',maskMixMode:'mix',maskSourceMix:0,maskBrightness:0,maskContrast:1.6,maskGamma:1.15,maskThreshold:.28,maskSoftness:.3,maskScale:1,maskDrift:0,maskInvert:false,maskMixer:true,maskNoixture:true,maskClouds:false,maskFoam:false}),
    'Noise Window':p('',{maskEnabled:true,maskSourceA:'perlin',maskSourceB:'billow',maskMixMode:'difference',maskSourceMix:.52,maskBrightness:.04,maskContrast:1.8,maskGamma:.9,maskThreshold:.36,maskSoftness:.18,maskScale:1.4,maskDrift:.14,maskInvert:false,maskMixer:true,maskNoixture:true,maskClouds:false,maskFoam:true}),
    'Ion Window':p('High-contrast multi-route mask tuned to retain dark negative space.',{maskEnabled:true,maskSourceA:'ridge',maskSourceB:'mixed-luma',maskMixMode:'difference',maskSourceMix:.44,maskBrightness:-.08,maskContrast:2.15,maskGamma:.82,maskThreshold:.38,maskSoftness:.12,maskScale:1.55,maskDrift:.12,maskInvert:false,maskMixer:true,maskNoixture:true,maskClouds:true,maskFoam:true})
  })
});
const g=(description,panels)=>Object.freeze({description,panels:Object.freeze({...Object.fromEntries(Object.keys(KINETIC_PANEL_DEFINITIONS).map(k=>[k,'Default'])),proceduralClouds:'Off',...panels})});
export const GLOBAL_PRESETS=Object.freeze({
  '0 Balanced Ocean':g('Ion-derived cryogenic ocean: much darker troughs and stronger surface structure.',{skysynth:'Cobalt Reactor',liquid:'Ion Chop',reflection:'Ion Chrome Blue',pattern:'Cryo Lattice',atmosphere:'Cobalt Vault',lighting:'Cryo Edge',output:'Ion Punch',modulation:'Loop Drift',lut:'Palette 3',noixture:'Ion Circuit',mixer:'Synth Only',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  'ION ORCHARD':g('High-reflection nocturnal metallic look.',{skysynth:'Glitch Lattice',liquid:'Glass Swell',reflection:'Dark Chrome',pattern:'Signal Wakes',atmosphere:'Sealed Basin',lighting:'Noir Edge',output:'Hero Shot',modulation:'Loop Drift',lut:'Palette 1',noixture:'Weave Circuit',mixer:'Synth Only',mask:'Noise Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  'VENT PARTICULATE':g('Ion-derived petroleum rift with cellular filaments and toxic edge lighting.',{skysynth:'Petroleum Rift',liquid:'Ion Surge',reflection:'Oil Chrome',pattern:'Petroleum Filaments',atmosphere:'Black Rift',lighting:'Toxic Edge',output:'Ion Punch',modulation:'Wander',lut:'Palette 6',noixture:'Turbulent Ridges',mixer:'Synth Only',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  '3 Hero Ocean':g('High-detail Ion derivative with stronger wave relief and cyan filaments.',{skysynth:'Cobalt Reactor',liquid:'Ion Surge',reflection:'Ion Chrome Blue',pattern:'Ion Filaments',atmosphere:'Deep Neon Horizon',lighting:'Ion Edge',output:'Ion Hero',modulation:'Pressure Sweep',lut:'Palette 0',noixture:'Ion Circuit',mixer:'Synth Only',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  '4 Biolume Plate':g('Dark magnetar bioluminescent plate derived from Ion Orchard.',{skysynth:'Magnetar Pulse',liquid:'Ion Mercury',reflection:'Opal Chrome',pattern:'Magenta Mesh',atmosphere:'Black Rift',lighting:'Magenta Edge',output:'Ion Punch',modulation:'Wander',lut:'Palette 5',noixture:'Ion Circuit',mixer:'Synth Only',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  '5 Weather Engine':g('Copper ion storm with hard seams and structured weather rather than white haze.',{skysynth:'Copper Storm',liquid:'Ion Chop',reflection:'Copper Mirror',pattern:'Copper Seams',atmosphere:'Copper Squall',lighting:'Copper Edge',output:'D20 Showcase',modulation:'Pressure Sweep',lut:'Palette 2',noixture:'Turbulent Ridges',mixer:'Synth Only',mask:'Ion Window',geometry:'D20 Conditioned',projection:'D20 Facet Storm'}),
  '6 Economy Interactive':g('Low-cost Ion derivative retaining contrast and useful detail.',{skysynth:'Glitch Lattice',liquid:'Glass Swell',reflection:'Ion Chrome Blue',pattern:'Ion Filaments',atmosphere:'Deep Neon Horizon',lighting:'Ion Edge',output:'Mesh Showcase',modulation:'Disabled',lut:'Palette 0',noixture:'Ion Circuit',mixer:'Synth Only',mask:'Noise Window',geometry:'Showcase Knot',projection:'Triplanar Volume'}),
  '7 Planetary Orbit':g('Ion-derived reflective alien planet with cryogenic lattice relief.',{skysynth:'Cryo Prism',liquid:'Ion Mercury',reflection:'Opal Chrome',pattern:'Cryo Lattice',atmosphere:'Black Rift',lighting:'Cryo Edge',output:'Ion Planet',modulation:'Slow Pulse',lut:'Palette 7',noixture:'Ion Circuit',mixer:'Synth Only',mask:'Ion Window',geometry:'Default Surface',projection:'Octahedral Planet'}),
  '8 Field Scan':g('Flat field visualisation mode.',{skysynth:'Glitch Lattice',liquid:'Orbital Field',reflection:'Dark Chrome',pattern:'Dry Noise',atmosphere:'Sealed Basin',lighting:'Hard Spot',output:'Field Study',modulation:'Wander',lut:'Palette 1',noixture:'Weave Circuit',mixer:'Synth Only',mask:'Noise Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  'HDRI SYNTH FUSION':g('Ion-derived HDRI fusion that remains visually strong even before an HDRI is loaded.',{skysynth:'Cobalt Reactor',liquid:'Ion Chop',reflection:'Ion Chrome Blue',pattern:'Ion Filaments',atmosphere:'Deep Neon Horizon',lighting:'Ion Edge',output:'Ion Punch',modulation:'Loop Drift',lut:'Palette 8',noixture:'Ion Circuit',mixer:'Crossfade 35',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  '10 Soft Light Mix':g('Opaline Ion derivative prepared for soft-light HDRI compositing.',{skysynth:'Cryo Prism',liquid:'Ion Mercury',reflection:'Opal Chrome',pattern:'Cryo Lattice',atmosphere:'Cobalt Vault',lighting:'Cryo Edge',output:'Ion Punch',modulation:'Loop Drift',lut:'Palette 7',noixture:'Ion Circuit',mixer:'Soft-Light 50',mask:'Ion Window',geometry:'Default Surface',projection:'Planar Legacy'}),
  'PHASE DIFFERENCE':g('Aggressive synthetic contrast stack, lightly tuned for clearer liquid structure.',{skysynth:'Glitch Lattice',liquid:'Needle Chop',reflection:'Dark Chrome',pattern:'Phase Filaments',atmosphere:'Electric Weather',lighting:'Hard Spot',output:'Phase Punch',modulation:'Pressure Sweep',lut:'Palette 4',noixture:'Weave Circuit',mixer:'Difference 40',mask:'Foam Bands',geometry:'Default Surface',projection:'Planar Legacy'}),
  ...Object.fromEntries(Object.entries(KINETIC_GLOBAL_PRESETS).map(([name,stack])=>[name,Object.freeze({...stack,panels:Object.freeze({proceduralClouds:'Off',...stack.panels})})]))
});
export const GLOBAL_PRESET_NAMES=Object.freeze(Object.keys(GLOBAL_PRESETS));
export const PATTERN_KEYS=['freqY','freqX','speed','hueShift','radius','diagonal','warp','fieldContrast'];

export const PERFORMANCE_KEYS=Object.freeze(['sourceWidth','envMapWidth','generatorFPS','meshResolution','renderScale','displayFPS','spatialSmooth','temporalSmooth','nlFilterStrength','nlFilterRadius','msaa','ssaaArea','temporalSamples','textureFilter','volumeResolution','volumeRenderScale','volumeSteps','volumeDensityFPS','volumeLightFPS','bloomResolution','feedbackResolution','maxRenderMP','textureBudgetMB']);
