"""Bounded offline V4.4b UI/component checks. Not a WebGPU render certification."""
from pathlib import Path
import json,os,shutil
from playwright.sync_api import sync_playwright
root=Path(__file__).resolve().parents[1]
html=(root/'Xenofield-standalone.html').read_text()
results=[]
skipped=[]
def check(value,label):
    assert value,label
    results.append(label)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('chromium-browser'),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':900});errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content(html,wait_until='load');page.wait_for_timeout(900)
    page.evaluate("document.getElementById('notification').classList.add('hidden')")
    check(page.locator('.param').count()==208,'All 208 numeric parameters use schema-backed controls')
    check(page.locator('[data-panel-preset]').count()==20,'All twenty functional panels expose preset menus')
    check(page.locator('#globalPreset option').count()==23,'Global menu exposes Custom plus twenty-two defaults')
    page.locator('#globalPreset').select_option('ION ORCHARD');page.locator('#loadGlobal').click();check(page.evaluate("document.activeElement===document.getElementById('globalPreset')"),'Global LOAD returns keyboard focus to global preset dropdown')
    check(page.locator('#liquidTabs button').count()==7,'Surface window exposes seven focused tabs including mesh/projection')
    check(page.locator('#surface .titlebar #liquidTabs').count()==1,'Liquid tab buttons live in the liquid titlebar')
    check(page.locator('#surfaceYResize').count()==1,'Liquid panel exposes a vertical resize handle')
    mesh_accept=page.locator('#meshFile').get_attribute('accept') or '';check(page.locator('#loadMesh').count()==1 and '.stl' in mesh_accept and '.obj' in mesh_accept and '.ply' in mesh_accept and '.glb' in mesh_accept and '.gltf' in mesh_accept,'Mesh import UI exposes STL/OBJ/PLY/GLB/GLTF')
    check(page.locator('#projectionA option').count()>=19 and page.locator('#projectionB option').count()>=19,'Projection A/B expose full non-geodesic mapping bank')
    check(page.locator('#preset-geometry').count()==1 and page.locator('#preset-projection').count()==1,'Geometry and projection panels expose preset banks')
    check(page.locator('#renderGate').count()==1,'First-render click gate exists')
    check(page.locator('#lightingControls .param').count()>=6,'Lighting tab exposes ambient/emissive/spot controls')
    check(page.locator('#sourceWidth').count()==1 and page.locator('#generatorFPS').count()==1,'SkySynth resolution and FPS are normal slider parameters')
    for selector in ['#upsampling','#upsamplingStageB']:
        opts=page.locator(selector+' option').all_text_contents()
        check('LANCZOS2' in opts and 'CATMULL-ROM' in opts,f'{selector} exposes extended upsamplers')
    check(page.locator('#processingStage option').count()==4,'Image-processing stage can be pre/mid/post/none')
    check(page.locator('#profilerChart').count()==1,'Live performance profiler chart exists')
    check(page.locator('details[open]').count()==0,'Submenus default closed')

    # V4.3b LUT spatial editor: region selection, editing history, clipboard-equivalent paste, paint and gradient tools.
    page.evaluate("document.querySelector('[data-restore=lut]').click()")
    check(page.locator('#lutGrid .lut-cell').count()==256,'LUT editor exposes a dense 16x16 spatial cell grid')
    check(page.locator('#lut .lut-title-tools button').count()>=10,'LUT titlebar exposes dense selection/clipboard/history controls')
    page.locator('#lutSelectNone').click()
    c0=page.locator('#lutGrid .lut-cell').nth(0).bounding_box();c17=page.locator('#lutGrid .lut-cell').nth(17).bounding_box()
    page.mouse.move(c0['x']+c0['width']/2,c0['y']+c0['height']/2);page.mouse.down();page.mouse.move(c17['x']+c17['width']/2,c17['y']+c17['height']/2);page.mouse.up()
    check(page.locator('#lutGrid .lut-cell.selected').count()==4,'LUT drag-selection creates an exact rectangular 2x2 region')
    before0=page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][0]')
    page.locator('#lutColorAHex').fill('FF0000');page.locator('#lutColorAHex').press('Enter');page.locator('#lutFill').click();page.wait_for_timeout(30)
    check(page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][0]')=='FF0000','LUT fill applies colour A only through the selected region')
    page.locator('#lutUndo').click();page.wait_for_timeout(20);check(page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][0]')==before0,'LUT undo restores palette edits')
    page.locator('#lutRedo').click();page.wait_for_timeout(20);check(page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][0]')=='FF0000','LUT redo reapplies palette edits')
    page.locator('#lutCopy').click();page.wait_for_timeout(20);page.locator('#lutSelectNone').click();c34=page.locator('#lutGrid .lut-cell').nth(34).bounding_box();page.mouse.click(c34['x']+c34['width']/2,c34['y']+c34['height']/2);page.mouse.move(c34['x']+c34['width']/2,c34['y']+c34['height']/2);page.mouse.down();c51=page.locator('#lutGrid .lut-cell').nth(51).bounding_box();page.mouse.move(c51['x']+c51['width']/2,c51['y']+c51['height']/2);page.mouse.up();page.locator('#lutPaste').click();page.wait_for_timeout(30)
    check(page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][34]')=='FF0000','LUT clipboard region pastes into an equivalent offset area')
    page.locator('#lutColorAHex').fill('000000');page.locator('#lutColorAHex').press('Enter');page.locator('#lutColorBHex').fill('FFFFFF');page.locator('#lutColorBHex').press('Enter');page.locator('#lutGradientMode').select_option('diagonal');page.locator('#lutGradient').click();page.wait_for_timeout(20)
    check(page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][34]')=='000000' and page.evaluate('__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][51]')=='FFFFFF','LUT diagonal gradient spans colour A to B across the selected region')
    page.locator('#lutToolBrush').click();page.locator('#lutBrushShape').select_option('irregular');page.locator('#lutBrushSize').fill('3');c85=page.locator('#lutGrid .lut-cell').nth(85).bounding_box();page.mouse.click(c85['x']+c85['width']/2,c85['y']+c85['height']/2);page.wait_for_timeout(20)
    check(page.locator('#lutGrid .lut-cell.selected').count()>1,'Irregular LUT brush paints a multi-cell irregular footprint')
    page.locator('#lutToolSelect').click();c0=page.locator('#lutGrid .lut-cell').nth(0).bounding_box();page.mouse.click(c0['x']+c0['width']/2,c0['y']+c0['height']/2);page.locator('#lutSelectNone').click();page.evaluate("()=>{const dt=new DataTransfer();dt.setData('text/plain','112233 445566\\n778899 AABBCC');document.getElementById('lut').dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}));}");page.wait_for_timeout(20)
    check(page.evaluate("[0,1,16,17].map(i=>__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot][i]).join(',')")=="112233,445566,778899,AABBCC",'LUT native paste accepts a plain 2D hex matrix and preserves row geometry')
    page.evaluate("document.querySelector('[data-restore=lut]').click()")

    check(page.locator('[data-submenu-lock]').count()>=15,'All requested functional submenus expose two-state locks')
    check(page.locator('[data-panel-global-lock]').count()==3,'SkySynth, Surface and LUT expose panel-global lock overrides')
    check(page.evaluate("document.getElementById('previewWrap').compareDocumentPosition(document.querySelector('#skysynth .window-body')) & Node.DOCUMENT_POSITION_FOLLOWING")!=0,'SkySynth preview is pinned above its scrollable controls')
    check(page.locator('#profilerChart').evaluate("e=>!!e.closest('.profiler-pin')"),'Profiler chart is in the pinned output header')
    # Lock behaviour: local LOCK blocks global change; panel UNLOCK overrides it without mutating local lock.
    page.evaluate("__XENOFIELD__.store.setSubmenuLock('skysynth-synth',true); __XENOFIELD__.store.set('freqX',-0.321); __XENOFIELD__.store.applyGlobalStack('0 Balanced Ocean')")
    check(abs(page.evaluate('__XENOFIELD__.store.settings.freqX')+0.321)<1e-6,'Submenu LOCK protects synth frequency from global preset')
    page.evaluate("__XENOFIELD__.store.setPanelGlobalLock('skysynth','unlock'); __XENOFIELD__.store.applyGlobalStack('VENT PARTICULATE')")
    check(abs(page.evaluate('__XENOFIELD__.store.settings.freqX')+0.321)>1e-4 and page.evaluate("__XENOFIELD__.store.submenuLocks['skysynth-synth']") is True,'Panel UNLOCK overrides but preserves submenu lock state')
    check(page.locator('#hdriFile').get_attribute('accept').startswith('.exr,.hdr'),'HDRI picker advertises EXR/HDR first-class')
    # Preview can collapse and re-enable.
    page.evaluate("document.getElementById('envPreview').click()")
    check(page.locator('#previewWrap').get_attribute('class').find('preview-disabled')>=0,'Preview click collapses preview')
    check('CLICK TO ENABLE PREVIEW' in page.locator('#previewToggleText').inner_text(),'Collapsed preview presents enable affordance')
    page.evaluate("document.getElementById('previewToggleText').click()")
    check('preview-disabled' not in page.locator('#previewWrap').get_attribute('class'),'Preview can be re-enabled')
    # Local EXR import remains functional in CPU/browser test mode.
    page.locator('#hdriFile').set_input_files(str(root/'assets/calibration-panorama.exr'));page.wait_for_timeout(250)
    check(page.evaluate('__XENOFIELD__.hdriFrame?.type')=='exr','EXR publishes as HDRI input')
    check('local EXR' in page.evaluate('__XENOFIELD__.hdriFrame.metrics.decoder'),'Common EXR decodes locally')
    check(not errors,'No JavaScript page errors during bounded UI checks')
    check(page.evaluate('__XENOFIELD__.bridge.fallback===null'),'Embedded standalone worker starts without main-thread fallback')
    page.evaluate("__XENOFIELD__.store.set('envMode','plasma'); __XENOFIELD__.bridge.tick(performance.now(),__XENOFIELD__.store.settings,__XENOFIELD__.store.palettes[__XENOFIELD__.store.settings.lutSlot])");page.wait_for_timeout(250);check(page.evaluate("__XENOFIELD__.bridge.frames>0 && __XENOFIELD__.bridge.metrics?.backend==='Web Worker'"),'Embedded classic worker executes a SkySynth frame and returns it')
    # V4.4b: real DOM interactions with independent controls, ranges, presets, locks and persistence.
    page.evaluate("for(const key of Object.keys(__XENOFIELD__.store.submenuLocks))__XENOFIELD__.store.setSubmenuLock(key,false);for(const key of Object.keys(__XENOFIELD__.store.panelGlobalLocks))__XENOFIELD__.store.setPanelGlobalLock(key,'none');document.getElementById('notification').classList.add('hidden')")
    page.locator('#openKinetic').click()
    check(page.locator('#kineticDock').is_visible(),'Kinetic dock opens from the workspace toolbar')
    check(page.locator('[data-kinetic-tab]').count()==6,'Six kinetic module tabs are present')
    check(page.locator('#kineticDock .param').count()==94,'All 94 new numeric controls are in the validated range system')
    check(page.locator('#kineticDock .param label[data-tip]').count()==94,'All new numeric controls carry explanatory tooltips')
    check(page.locator('#kineticDock .kinetic-tools select option').count()==10,'Ten distinct demonstration stacks are available')
    page.locator('#kineticDock .kinetic-tools select').select_option('VOXEL SPRAY')
    page.locator('#kineticDock .kinetic-tools button').filter(has_text='LOAD STACK').click()
    check(page.evaluate("__XENOFIELD__.store.settings.volumeEnabled && __XENOFIELD__.store.settings.volumeResolution==='24'"),'Loading Voxel Spray sets the actual volume module, not a disconnected UI preview')
    page.locator('[data-kinetic-tab=volume]').click()
    page.locator('[data-kinetic-page=volume] .kinetic-subtabs button').filter(has_text='CACHE').click()
    page.locator('#volumeDensityFPS').fill('0.1');page.locator('#volumeDensityFPS').press('Enter')
    check(page.evaluate('__XENOFIELD__.store.settings.volumeDensityFPS')==0.1,'Numeric cache cadence accepts its slow 0.1 Hz engineering limit')
    page.locator('[data-kinetic-tab=temporal]').click()
    page.locator('[data-kinetic-page=temporal] .kinetic-subtabs button').filter(has_text='FEEDBACK').click()
    page.locator('#feedbackPersistence').fill('0.99');page.locator('#feedbackPersistence').press('Enter')
    page.locator('#feedbackAmount').fill('0.2');page.locator('#feedbackAmount').press('Enter')
    page.locator('#feedbackBlend').select_option('add')
    check(page.evaluate("__XENOFIELD__.store.settings.feedbackPersistence===0.99&&__XENOFIELD__.store.settings.feedbackAmount===0.2&&__XENOFIELD__.store.settings.feedbackBlend==='add'"),'Feedback persistence, layer opacity and additive blend are independently editable')
    page.locator('[data-kinetic-tab=aa]').click()
    page.locator('#ssaaArea').select_option('2');page.locator('#msaa').select_option('4');page.locator('#textureFilter').select_option('manual32')
    check('MANUAL' in page.locator('#textureFilter option:checked').inner_text(),'AF32 is visibly labelled manual experimental')
    page.locator('[data-submenu-lock=kinetic-aa]').click()
    page.locator('#kineticDock .kinetic-tools select').select_option('ABSURD AA');page.locator('#kineticDock .kinetic-tools button').filter(has_text='LOAD STACK').click()
    check(page.evaluate("__XENOFIELD__.store.settings.ssaaArea==='2'&&__XENOFIELD__.store.settings.temporalSamples==='32'"),'AA module lock protects SSAA while independent temporal sample target can change')
    page.evaluate("__XENOFIELD__.store.setSubmenuLock('kinetic-aa',false);__XENOFIELD__.store.set('feedbackPersistence',0.973);__XENOFIELD__.store.savePanelPreset('temporal','UI roundtrip');globalThis.kineticSnapshot=__XENOFIELD__.store.snapshot();__XENOFIELD__.store.set('feedbackPersistence',0.1);__XENOFIELD__.store.applySnapshot(kineticSnapshot)")
    check(page.evaluate("__XENOFIELD__.store.settings.feedbackPersistence===0.973&&__XENOFIELD__.store.panelPresets.temporal['UI roundtrip'].settings.feedbackPersistence===0.973"),'Project snapshot round-trip retains new values and user module presets')
    page.locator('#kineticDock .kinetic-tools button').filter(has_text='FX OFF').click()
    check(page.evaluate("!__XENOFIELD__.store.settings.volumeEnabled&&!__XENOFIELD__.store.settings.feedbackEnabled&&__XENOFIELD__.store.settings.temporalSamples==='off'&&__XENOFIELD__.store.settings.msaa==='4'"),'FX OFF disables temporal and artistic work without overwriting independent MSAA')
    # V4.4b dedicated procedural cloud world-volume instrument.
    check(page.locator('#openProceduralClouds').count()==1,'Procedural Clouds has a dedicated workspace dock entry')
    page.locator('#openProceduralClouds').click();check(page.locator('#proceduralClouds').is_visible(),'Procedural Clouds panel opens independently of the kinetic dock')
    reference_keys=['procCloudDensity','procCloudCoverage','procCloudScale','procCloudAltitude','procCloudDetail','procCloudWindSpeed','procCloudRaySteps','procCloudLightSteps','procCloudShadowDark','procCloudSunIntensity','procCloudHeight','procCloudCacheRes','procCloudCacheUpdate','procCloudCacheSmooth']
    check(page.locator('#procCloudParams .proc-cloud-param').count()==14,'Cloud panel exposes all fourteen reference playground controls')
    check(page.locator('#procCloudParams .proc-cloud-param').evaluate_all("els=>els.map(e=>e.dataset.parameter)")==reference_keys,'Cloud controls preserve the reference playground order')
    page.locator('#procCloudPreset').select_option('VIDEO · CELL MEMBRANES');page.locator('#procCloudLoad').click()
    check(page.evaluate("(()=>{const s=__XENOFIELD__.store.settings;return s.procCloudDensity===4&&s.procCloudCoverage===1&&s.procCloudScale===5.85&&s.procCloudDetail===0&&s.procCloudRaySteps===16&&s.procCloudLightSteps===1&&s.procCloudCacheRes===128&&s.procCloudCacheSmooth===.95})()"),'Video membrane preset reproduces the demonstrated extreme parameter state')
    page.locator('[data-cloud-number=procCloudCenterX]').fill('123');page.locator('[data-cloud-number=procCloudCenterX]').press('Enter');page.locator('[data-cloud-number=procCloudSizeY]').fill('77');page.locator('[data-cloud-number=procCloudSizeY]').press('Enter')
    check(page.evaluate("__XENOFIELD__.store.settings.procCloudCenterX===123&&__XENOFIELD__.store.settings.procCloudSizeY===77"),'World volume position and independent axis size are directly editable')
    page.locator('[data-cloud-mode=scale]').click();page.locator('[data-cloud-axis=xz]').click();page.locator('#procCloudEdit').click()
    check(page.evaluate("(()=>{const s=__XENOFIELD__.store.settings;return s.procCloudTransformMode==='scale'&&s.procCloudTransformAxis==='xz'&&s.procCloudEditActive})()"),'In-view world tool exposes move/scale mode and axis constraints')
    page.evaluate("__XENOFIELD__.store.savePanelPreset('proceduralClouds','UI cloud roundtrip');globalThis.cloudSnapshot=__XENOFIELD__.store.snapshot();__XENOFIELD__.store.set('procCloudCenterX',0);__XENOFIELD__.store.applySnapshot(cloudSnapshot)")
    check(page.evaluate("__XENOFIELD__.store.settings.procCloudCenterX===123&&!!__XENOFIELD__.store.panelPresets.proceduralClouds['UI cloud roundtrip']"),'Cloud transform and user cloud preset survive project snapshot round-trip')
    check(page.locator('#proceduralClouds').evaluate('e=>e.getBoundingClientRect().height<800&&e.scrollWidth<=e.clientWidth+1'),'Procedural cloud instrument remains compact and has no horizontal overflow')
    page.locator('[data-kinetic-tab=volume]').click()
    page.locator('[data-kinetic-page=volume] .kinetic-subtabs button').filter(has_text='CORE').click()
    check(page.locator('#kineticDock').evaluate('e=>e.getBoundingClientRect().height<600'),'Default dock is content-sized, not padded to a large fixed height')
    output=os.environ.get('UI_TEST_OUT')
    if output:
        Path(output).mkdir(parents=True,exist_ok=True);page.locator('#kineticDock').screenshot(path=str(Path(output)/'kinetic-controls.png'))
    page.set_viewport_size({'width':600,'height':800});page.wait_for_timeout(50)
    check(page.locator('#kineticDock').evaluate('e=>e.getBoundingClientRect().right<=innerWidth&&e.getBoundingClientRect().left>=0'),'Compact dock remains inside a 600-pixel viewport')
    check(page.locator('#kineticDock .kinetic-body').evaluate('e=>e.scrollWidth<=e.clientWidth+1'),'Small-viewport controls do not require horizontal scrolling')
    page.set_viewport_size({'width':1440,'height':900})
    check(not errors,'No JavaScript errors after the kinetic UI interaction and project persistence tests')
    # Try the exact file:// launch mode used by Windows users. Some CI/container browser policies block file navigation entirely;
    # in that case the opaque-origin set_content worker check above is still required and the file-specific check is reported skipped.
    file_page=browser.new_page(viewport={'width':900,'height':600});file_errors=[];file_page.on('pageerror',lambda e:file_errors.append(str(e)))
    try:
        file_page.goto((root/'Xenofield-standalone.html').as_uri(),wait_until='load');file_page.wait_for_timeout(700);check(file_page.evaluate('__XENOFIELD__.bridge.fallback===null'),'file:// standalone starts its embedded classic worker without cross-origin failure');check(not any('cross-origin redirects' in e.lower() for e in file_errors),'file:// standalone emits no worker cross-origin page error')
    except Exception as e:
        if 'ERR_BLOCKED_BY_ADMINISTRATOR' not in str(e):
            raise
        skipped.append('file:// launch: managed Chromium policy blocks local-file navigation')
    finally:
        file_page.close()
    metrics=page.evaluate('__XENOFIELD__.metrics()')
    print(json.dumps({'passed':len(results),'skipped':skipped,'tests':results,'pageErrors':errors,'validationScope':'Offline DOM/component + local EXR decode test. Not a WebGPU rendered frame.','metrics':metrics},indent=2))
    browser.close()
