import {StateStore} from './core/store.js';
import {EnvironmentBridge} from './environment/bridge.js';
import {loadLastHDRI,saveLastHDRI} from './environment/assets.js';
import {XenofieldRenderer} from './render/renderer.js';
import {installUI,download} from './ui/ui.js';
import {parseMeshFile} from './mesh/mesh-tools.js';
const $=id=>document.getElementById(id);
const sat=x=>Math.max(0,Math.min(1,x)),lum=c=>c[0]*.2126+c[1]*.7152+c[2]*.0722;
const safe=(a,b)=>Math.abs(b)<1e-5?0:a/b;
function rgbToHsv(c){const mx=Math.max(...c),mn=Math.min(...c),d=mx-mn;let h=0;if(d>1e-8){if(mx===c[0])h=(c[1]-c[2])/d;else if(mx===c[1])h=2+(c[2]-c[0])/d;else h=4+(c[0]-c[1])/d;h=((h/6)%1+1)%1;}return [h,mx>1e-8?d/mx:0,mx];}
function hsvToRgb([h,s,v]){const f=n=>{const k=(n+h*6)%6;return v-v*s*Math.max(0,Math.min(k,4-k,1));};return [f(5),f(3),f(1)];}
function clipColor(c){let l=lum(c),mn=Math.min(...c),mx=Math.max(...c),o=[...c];if(mn<0)o=o.map(x=>l+(x-l)*l/Math.max(l-mn,1e-5));mx=Math.max(...o);if(mx>1)o=o.map(x=>l+(x-l)*(1-l)/Math.max(mx-l,1e-5));return o;}
const setLum=(c,l)=>clipColor(c.map(x=>x+l-lum(c)));
function rgbToOklab(c){const r=Math.max(0,c[0]),g=Math.max(0,c[1]),b=Math.max(0,c[2]),l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);return [.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s];}
function oklabToRgb([L,a,b]){let l=L+.3963377774*a+.2158037573*b,m=L-.1055613458*a-.0638541728*b,s=L-.0894841775*a-1.291485548*b;l=l*l*l;m=m*m*m;s=s*s*s;return [Math.max(0,4.0767416621*l-3.3077115913*m+.2309699292*s),Math.max(0,-1.2684380046*l+2.6097574011*m-.3413193965*s),Math.max(0,-.0041960863*l-.7034186147*m+1.707614701*s)];}
function lchBlend(base,source,mode){const b=rgbToOklab(base),s=rgbToOklab(source),bc=Math.hypot(b[1],b[2]),sc=Math.hypot(s[1],s[2]),bd=bc>1e-6?[b[1]/bc,b[2]/bc]:[1,0],sd=sc>1e-6?[s[1]/sc,s[2]/sc]:[1,0],o=[...b];if(mode==='lch-hue'){o[1]=sd[0]*bc;o[2]=sd[1]*bc;}else if(mode==='lch-chroma'){o[1]=bd[0]*sc;o[2]=bd[1]*sc;}else if(mode==='lch-color'){o[1]=s[1];o[2]=s[2];}else o[0]=s[0];return oklabToRgb(o);}
function blendPixel(base,source,mode,amount=1,random=.5){const a=sat(amount),b=base.map(sat),s=source.map(sat),ch=(fn)=>b.map((x,i)=>fn(x,s[i]));let r;
 if(mode==='dissolve')return random<a?source:base;if(mode==='normal')r=source;else if(mode==='lighten')r=base.map((x,i)=>Math.max(x,source[i]));else if(mode==='luma-lighten')r=lum(source)>lum(base)?source:base;else if(mode==='screen')r=ch((x,y)=>1-(1-x)*(1-y));else if(mode==='dodge')r=ch((x,y)=>Math.min(1,safe(x,1-y)));else if(mode==='addition')r=base.map((x,i)=>x+source[i]);else if(mode==='darken')r=base.map((x,i)=>Math.min(x,source[i]));else if(mode==='luma-darken')r=lum(source)<lum(base)?source:base;else if(mode==='multiply')r=base.map((x,i)=>x*source[i]);else if(mode==='burn')r=ch((x,y)=>Math.max(0,1-safe(1-x,y)));else if(mode==='linear-burn')r=base.map((x,i)=>x+source[i]-1);else if(mode==='overlay')r=ch((x,y)=>x<=.5?2*x*y:1-2*(1-x)*(1-y));else if(mode==='hard-light')r=ch((x,y)=>y<=.5?2*x*y:1-2*(1-x)*(1-y));else if(mode==='soft-light')r=ch((x,y)=>y<=.5?x-(1-2*y)*x*(1-x):x+(2*y-1)*((x<=.25?((16*x-12)*x+4)*x:Math.sqrt(x))-x));else if(mode==='vivid-light')r=ch((x,y)=>y<.5?Math.max(0,1-safe(1-x,2*y)):Math.min(1,safe(x,1-2*(y-.5))));else if(mode==='pin-light')r=ch((x,y)=>y<.5?Math.min(x,2*y):Math.max(x,2*(y-.5)));else if(mode==='linear-light')r=base.map((x,i)=>x+2*source[i]-1);else if(mode==='hard-mix')r=base.map((x,i)=>x+source[i]<1?0:1);else if(mode==='difference')r=base.map((x,i)=>Math.abs(x-source[i]));else if(mode==='exclusion')r=base.map((x,i)=>.5-2*(x-.5)*(source[i]-.5));else if(mode==='subtract')r=base.map((x,i)=>x-source[i]);else if(mode==='grain-extract')r=base.map((x,i)=>x-source[i]+.5);else if(mode==='grain-merge')r=base.map((x,i)=>x+source[i]-.5);else if(mode==='divide')r=base.map((x,i)=>safe(x,source[i]));else if(mode==='hsv-hue'){const hb=rgbToHsv(b),hs=rgbToHsv(s);r=hsvToRgb([hs[0],hb[1],hb[2]]);}else if(mode==='hsv-saturation'){const hb=rgbToHsv(b),hs=rgbToHsv(s);r=hsvToRgb([hb[0],hs[1],hb[2]]);}else if(mode==='hsv-value'){const hb=rgbToHsv(b),hs=rgbToHsv(s);r=hsvToRgb([hb[0],hb[1],hs[2]]);}else if(mode==='hsl-color')r=setLum(s,lum(b));else if(mode.startsWith('lch-'))r=lchBlend(b,s,mode);else if(mode==='luminance')r=setLum(b,lum(s));else r=source;
 return base.map((x,i)=>x+(r[i]-x)*a);
}

export class XenofieldApp{
 constructor(){
  this.store=new StateStore();this.renderer=null;this.plasmaFrame=null;this.hdriFrame=null;this.latestFrame=null;this.assetName='';this.errors=[];this.fps=0;this.fpsSmooth=60;this.presented=0;this.lastStatus=performance.now();this.lastMetricsUI=0;this.lastFrame=0;this.lastRAF=0;this.lookPointer=null;this.restarting=null;this.fallbackActive=false;this.fallbackReason='';this.storeTimer=0;this.previewDirty=true;this.previewEnabled=true;this.lastPreviewDraw=0;this.previewDrawMs=0;this.profilerHistory=[];this.lastFrameProfile=null;this.smoothedMod=0;this.lastModUI=0;this.importedMeshSource=null;this.meshName='';this.meshRebuildTimer=0;
  this.bridge=new EnvironmentBridge(frame=>this.onEnvironment(frame),error=>this.notify(`Environment: ${error}`));
  this.ui=installUI(this);this.store.addEventListener('change',e=>this.settingsChanged(e.detail));
  if(this.store.globalStackName==='Custom'&&this.store.settings.freqX===.32){this.store.applyGlobalStack('ION ORCHARD');this.ui?.setAnchor?.();}
  this.assetsPending=null;window.__XENOFIELD__=this;
 }
 notify(message){this.errors.push({at:new Date().toISOString(),message});this.errors=this.errors.slice(-24);$('notification').textContent=message;$('notification').classList.remove('hidden');}
 hasHDRI(){return !!this.hdriFrame;}
 settingsChanged({keys,reason}){
  const generatorKeys=['freqY','freqX','speed','hueShift','radius','diagonal','warp','fieldContrast','radiance','sourceWidth','envMapWidth','generatorFPS','spatialSmooth','temporalSmooth','upsampling','upsamplingStageB','processingStage','nlFilterStrength','nlFilterRadius','palette','lutSlot'];
  if(keys.some(k=>generatorKeys.includes(k))||reason==='project')this.bridge.invalidate(reason==='project');
  if(keys.includes('envMode')&&this.store.settings.envMode==='plasma')this.bridge.invalidate(true);
  if(keys.includes('mixerEnabled')&&this.store.settings.mixerEnabled)this.bridge.invalidate(true);
  if(keys.some(k=>['envMode','mixerEnabled','mixerMix','mixerBlend','noixtureEnabled','noixtureMode','noixtureBlend','noixtureAmount','noixtureScale','noixtureContrast','noixtureDrift','noixtureColor','cloudBlend','cloudCoverage','cloudOpacity','cloudScale','cloudDrift','maskEnabled','maskInvert','maskMixer','maskNoixture','maskClouds','maskSourceA','maskSourceB','maskMixMode','maskSourceMix','maskBrightness','maskContrast','maskGamma','maskThreshold','maskSoftness','maskScale','maskDrift','envGain','ambientIntensity','emissiveIntensity','spotIntensity'].includes(k)))this.requestPreviewDraw();
  if(keys.includes('meshResolution')){clearTimeout(this.storeTimer);this.storeTimer=setTimeout(()=>{try{this.renderer?.ready&&this.renderer.setMeshResolution(this.store.settings.meshResolution);}catch(e){this.notify(`Mesh rebuild: ${e.message}`);}},220);}
  const geometryKeys=['meshAsset','meshScale','meshWeldEpsilon','meshTargetEdge','meshCurvatureAngle','meshSubdivideLevels','meshSmoothIterations','meshSmoothStrength','meshSpikeThreshold','meshSpikeMode','meshHardEdgeAngle','meshTriangleCap','meshRetessellate','meshPreserveBoundary','meshPreserveHardEdges'];if(keys.some(k=>geometryKeys.includes(k))){clearTimeout(this.meshRebuildTimer);this.meshRebuildTimer=setTimeout(()=>{try{if(!this.renderer?.ready)return;if(this.store.settings.meshAsset==='imported'&&this.importedMeshSource)this.renderer.setImportedMesh(this.importedMeshSource,this.store.settings);else this.renderer.setMeshAsset(this.store.settings.meshAsset,this.store.settings);this.ui?.updateMeshState?.();}catch(e){this.notify(`MESH CONDITIONING FAILED: ${e.message}`);}},180);}
  if(keys.includes('sceneMode'))this.resetCamera();
 }
 onEnvironment(frame){
  const imported=frame.type!=='frame';
  if(imported){
   this.hdriFrame=frame;this.assetName=this.bridge.assetName||'Imported panorama';if(!this.store.settings.mixerEnabled)this.store.set('envMode','hdri');$('assetName').textContent=this.assetName;this.ui?.updateSourceState?.();
   if(this.assetsPending){const asset=this.assetsPending;if(asset.size<=256*1024*1024)saveLastHDRI(asset).catch(()=>this.notify('HDRI loaded, but local asset storage is unavailable. Reload the file next session.'));else this.notify('HDRI loaded. Files above 256 MiB are not auto-cached in browser storage; reload this panorama next session.');this.assetsPending=null;}
   const ow=frame.metrics.originalWidth||frame.levels[0].width,oh=frame.metrics.originalHeight||frame.levels[0].height,peak=frame.metrics.peak;
   this.notify(`${this.assetName} loaded: ${ow} × ${oh}; GPU map ${frame.levels[0].width} × ${frame.levels[0].height}${Number.isFinite(peak)?`; radiance peak ${peak.toFixed(2)}`:''}.`);
  }else this.plasmaFrame=frame;
  this.latestFrame=frame;if(this.renderer?.ready&&imported)this.renderer.queueEnvironment(frame,'hdri');this.requestPreviewDraw(true);this.ui?.updateSourceState?.();
 }
 previewPixel(frame,u,v){if(!frame?.preview)return [0,0,0];const w=frame.previewWidth,h=frame.previewHeight,x=Math.max(0,Math.min(w-1,Math.round(u*(w-1)))),y=Math.max(0,Math.min(h-1,Math.round(v*(h-1)))),i=(y*w+x)*4;return [frame.preview[i],frame.preview[i+1],frame.preview[i+2]];}
 previewNoixtureValue(u,v){const s=this.store.settings,t=performance.now()*.001*s.noixtureDrift,fract=x=>x-Math.floor(x),h=fract(Math.sin((u*s.noixtureScale*17.3+t)*12.9898+(v*s.noixtureScale*11.7-t*.71)*78.233)*43758.5453);let n=h;if(s.noixtureMode==='billow')n=Math.abs(h*2-1);else if(s.noixtureMode==='ridge')n=1-Math.abs(h*2-1);else if(s.noixtureMode==='weave')n=.5+.5*Math.sin((u+v)*s.noixtureScale*36+t*2);return sat((n-.5)*s.noixtureContrast+.5);}
 previewCloudValue(u,v){const s=this.store.settings,t=performance.now()*.001*s.cloudDrift,h=Math.sin((u*s.cloudScale*19+t)*8.2)+Math.sin((v*s.cloudScale*11-t*.7)*12.7)+Math.sin((u+v)*s.cloudScale*7.3+t*.4);return sat((h/3+.5-s.cloudCoverage*.35)*1.65);}
 previewMaskSource(source,u,v){const s=this.store.settings,scale=s.maskScale||1,drift=performance.now()*.001*(s.maskDrift||0),uu=((u-.5)*scale+.5+drift*.03)%1,vv=((v-.5)*scale+.5-drift*.02)%1,U=(uu+1)%1,V=(vv+1)%1,hash=(x,y)=>{const q=Math.sin(x*127.1+y*311.7)*43758.5453;return q-Math.floor(q);};if(source==='constant')return 1;if(source==='skysynth-luma')return lum(this.previewPixel(this.plasmaFrame||this.hdriFrame,U,V));if(source==='hdri-luma')return lum(this.previewPixel(this.hdriFrame||this.plasmaFrame,U,V));if(source==='mixed-luma'){const a=this.previewPixel(this.plasmaFrame||this.hdriFrame,U,V),b=this.previewPixel(this.hdriFrame||this.plasmaFrame,U,V);return lum(a.map((x,i)=>x+(b[i]-x)*s.mixerMix));}if(source==='noixture')return this.previewNoixtureValue(U,V);if(source==='clouds')return this.previewCloudValue(U,V);const n=hash(U*17,V*13);if(source==='perlin')return n;if(source==='billow')return Math.abs(n*2-1);if(source==='ridge')return 1-Math.abs(n*2-1);if(source==='weave')return .5+.5*Math.sin((U+V)*44);if(source==='vertical')return V;return sat(1-Math.hypot(U-.5,V-.5)*1.4142);}
 previewMask(u,v){const s=this.store.settings,a=this.previewMaskSource(s.maskSourceA,u,v),b=this.previewMaskSource(s.maskSourceB,u,v),m=s.maskSourceMix;let x=a+(b-a)*m;if(s.maskMixMode==='multiply')x=a*b;else if(s.maskMixMode==='screen')x=1-(1-a)*(1-b);else if(s.maskMixMode==='addition')x=a+b*m;else if(s.maskMixMode==='difference')x=Math.abs(a-b*m);else if(s.maskMixMode==='minimum')x=Math.min(a,b);else if(s.maskMixMode==='maximum')x=Math.max(a,b);x=(x-.5)*s.maskContrast+.5+s.maskBrightness;x=Math.pow(Math.max(0,x),1/Math.max(.05,s.maskGamma));if(s.maskSoftness<.499){const lo=s.maskThreshold-s.maskSoftness,hi=s.maskThreshold+s.maskSoftness,t=sat((x-lo)/Math.max(hi-lo,1e-5));x=t*t*(3-2*t);}x=sat(x);return s.maskInvert?1-x:x;}
 previewMaskFor(target,u,v){const s=this.store.settings;if(!s.maskEnabled||!s[target])return 1;return this.previewMask(u,v);}
 applyPreviewNoixture(rgb,u,v){const s=this.store.settings;if(!s.noixtureEnabled||s.noixtureAmount<=0)return rgb;const n=this.previewNoixtureValue(u,v),tint=s.noixtureColor.match(/../g).map(x=>parseInt(x,16)/255),layer=tint.map(c=>c*n),a=s.noixtureAmount*this.previewMaskFor('maskNoixture',u,v);return blendPixel(rgb,layer,s.noixtureBlend,a,((u*997+v*313)%1));}
 requestPreviewDraw(force=false){this.previewDirty=true;if(force&&this.fallbackActive&&this.previewEnabled)this.drawPreview();}
 setPreviewEnabled(enabled){this.previewEnabled=!!enabled;this.renderer?.setPreviewEnabled?.(this.previewEnabled);this.ui?.setPreviewEnabled?.(this.previewEnabled);if(this.previewEnabled&&this.fallbackActive)this.requestPreviewDraw(true);}
 drawPreview(){
  const start=performance.now(),s=this.store.settings,a=this.plasmaFrame||this.hdriFrame,b=this.hdriFrame||a;if(!a)return;
  const mix=this.hdriFrame?(s.mixerEnabled?s.mixerMix:(s.envMode==='hdri'?1:0)):0,w=256,h=128;
  // envPreview is normally a WebGPU canvas in V4.2c. Browsers permanently bind a
  // canvas to the first context type requested, so getContext('2d') legitimately
  // returns null after WebGPU has claimed it. CPU fallback rendering therefore uses
  // a dedicated scratch canvas and only mirrors into envPreview when a 2D context is
  // actually available. This keeps HDRI import independent from preview backend state.
  if(!this.cpuPreviewCanvas){this.cpuPreviewCanvas=document.createElement('canvas');this.cpuPreviewCanvas.width=w;this.cpuPreviewCanvas.height=h;}
  const scratch=this.cpuPreviewCanvas,ctx=scratch.getContext('2d',{willReadFrequently:true});if(!ctx){this.previewDirty=false;return;}
  if(scratch.width!==w||scratch.height!==h){scratch.width=w;scratch.height=h;}
  const image=ctx.createImageData(w,h),tone=x=>sat((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14));
  for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=(x+.5)/w,v=(y+.5)/h,pa=this.previewPixel(a,u,v),pb=this.previewPixel(b,u,v),random=((x*73856093^y*19349663)>>>0)/4294967295;let rgb=s.mixerEnabled?blendPixel(pa,pb,s.mixerBlend,mix*this.previewMaskFor('maskMixer',u,v),random):pa.map((q,i)=>q+(pb[i]-q)*mix);rgb=this.applyPreviewNoixture(rgb,u,v);const cloud=this.previewCloudValue(u,v),cloudLayer=rgb.map(q=>q*(.45+.55*cloud)+cloud*.18),cloudAlpha=s.cloudOpacity*cloud*this.previewMaskFor('maskClouds',u,v);rgb=blendPixel(rgb,cloudLayer,s.cloudBlend,cloudAlpha,random);const o=(y*w+x)*4;for(let c=0;c<3;c++)image.data[o+c]=255*Math.pow(tone(rgb[c]*s.envGain),1/2.2);image.data[o+3]=255;}
  ctx.putImageData(image,0,0);
  const canvas=$('envPreview'),displayCtx=canvas?.getContext?.('2d');if(displayCtx){if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}displayCtx.drawImage(scratch,0,0,w,h);}
  const paSize=this.plasmaFrame?`${this.plasmaFrame.levels[0].width}×${this.plasmaFrame.levels[0].height}`:'—',hbSize=this.hdriFrame?`${this.hdriFrame.levels[0].width}×${this.hdriFrame.levels[0].height}`:'—';$('sourceInfo').textContent=s.mixerEnabled?`MIX ${paSize} / ${hbSize}`:(s.envMode==='hdri'?`${hbSize} HDRI`:`${paSize} SYNTH → ${s.envMapWidth}×${Math.round(s.envMapWidth/2)}`);
  if(this.fallbackActive){const fallback=$('fallback'),f=fallback.getContext('2d');if(f){if(fallback.width!==innerWidth||fallback.height!==innerHeight){fallback.width=innerWidth;fallback.height=innerHeight;}f.imageSmoothingEnabled=true;f.imageSmoothingQuality='high';f.drawImage(scratch,0,0,fallback.width,fallback.height);}}
  this.previewDirty=false;this.lastPreviewDraw=performance.now();this.previewDrawMs=this.lastPreviewDraw-start;
 }
 async importMesh(file){try{this.notify(`IMPORTING MESH ${file.name.toUpperCase()}…`);const source=await parseMeshFile(file);this.importedMeshSource=source;this.meshName=file.name;this.store.set('meshAsset','imported');const stats=this.renderer?.ready?this.renderer.setImportedMesh(source,this.store.settings):null;this.store.set('sceneMode','mesh');this.ui?.updateMeshState?.();if(stats)this.notify(`${file.name} READY · ${stats.vertices.toLocaleString()} VERTICES · ${stats.triangles.toLocaleString()} TRIANGLES · ${stats.spikes} SPIKES HANDLED · ${stats.processingMs.toFixed(1)} MS CONDITIONING`);return true;}catch(e){this.notify(`MESH IMPORT FAILED: ${e?.message||e}`);return false;}}
 async importHDRI(file){try{this.notify(`LOADING ${file.name.toUpperCase()}…`);this.assetsPending=file;const accepted=await this.bridge.importFile(file);if(!accepted)this.assetsPending=null;this.ui?.updateSourceState?.();return accepted;}catch(e){this.assetsPending=null;this.notify(`HDRI LOAD FAILED: ${e?.message||e}`);this.ui?.updateSourceState?.();return false;}}
 async restart(){if(this.restarting)return this.restarting;this.restarting=(async()=>{this.renderer?.dispose();this.renderer=null;$('boot').classList.remove('hidden');$('bootText').textContent='COMPILING THE V4.4B KINETIC GPU PIPELINE…';try{const renderer=new XenofieldRenderer($('scene'),m=>this.notify(m),$('envPreview'));this.renderer=renderer;await renderer.init(this.store.settings);if(this.importedMeshSource)renderer.setImportedMesh(this.importedMeshSource,this.store.settings);renderer.setPreviewEnabled(this.previewEnabled);renderer.setPalette(this.store.palettes[this.store.settings.lutSlot]);if(this.hdriFrame)renderer.queueEnvironment(this.hdriFrame,'hdri');this.fallbackActive=false;this.fallbackReason='';$('scene').classList.remove('hidden');$('fallback').classList.add('hidden');}catch(e){this.renderer?.dispose();this.renderer=null;this.fallbackActive=true;this.fallbackReason=e?.message||String(e);$('scene').classList.add('hidden');$('fallback').classList.remove('hidden');const state=navigator.gpu?'WebGPU exists, but the GPU renderer failed to initialise.':'WebGPU is unavailable in this browser/GPU configuration.';this.notify(`${this.fallbackReason} ${state} Showing the CPU SkySynth/environment preview only.`);}finally{$('boot').classList.add('hidden');}})();try{return await this.restarting;}finally{this.restarting=null;}}
 waitForRenderStart(){return new Promise(resolve=>{const gate=$('renderGate');$('boot').classList.add('hidden');gate.classList.remove('hidden');const start=()=>{gate.classList.add('hidden');gate.removeEventListener('pointerdown',start);resolve();};gate.addEventListener('pointerdown',start,{once:true});});}
 async start(){await this.waitForRenderStart();await this.restart();this.running=true;this.lastFrame=0;this.lastRAF=0;requestAnimationFrame(t=>this.frame(t));if(this.store.settings.envMode==='hdri'||this.store.settings.mixerEnabled){try{const file=await loadLastHDRI();if(file)await this.importHDRI(file);else if(this.store.settings.envMode==='hdri'){this.store.set('envMode','plasma');this.notify('No stored HDRI was found; displaying SkySynth until a panorama is loaded.');}}catch{if(this.store.settings.envMode==='hdri')this.store.set('envMode','plasma');this.notify('Could not restore the panorama. Please load the HDRI again.');}}if(this.store.lastError)this.notify(this.store.lastError);}
 frame(now){
  if(!this.running)return;requestAnimationFrame(t=>this.frame(t));if(document.hidden){this.lastRAF=now;return;}const s=this.store.settings,frameStart=performance.now(),gpuSynth=!!this.renderer?.ready,bridgeAt=performance.now();if(!gpuSynth)this.bridge.tick(now,s,this.store.palettes[s.lutSlot]);const bridgeTickMs=performance.now()-bridgeAt,rafDt=this.lastRAF?Math.max(.001,(now-this.lastRAF)/1000):1/60;this.lastRAF=now;let moveMs=0,renderMs=0,instantFPS=this.fpsSmooth;
  const previewVisible=$('envPreview').getClientRects().length>0;if(this.fallbackActive&&this.previewEnabled&&previewVisible&&this.previewDirty&&now-this.lastPreviewDraw>=200)this.drawPreview();
  const interval=1000/Math.max(1,s.displayFPS);if(!this.lastFrame||now-this.lastFrame>=interval-.5){const renderDelta=this.lastFrame?Math.max(.001,(now-this.lastFrame)/1000):1/Math.max(1,s.displayFPS),simDt=Math.min(renderDelta,1/Math.max(30,s.displayFPS*.8)),moveAt=performance.now();this.renderer?.move(this.cameraKeys,simDt,s);moveMs=performance.now()-moveAt;try{const renderAt=performance.now();if(this.renderer?.render(simDt,s,this.store.palettes[s.lutSlot])){this.presented++;instantFPS=Math.min(s.displayFPS,1/renderDelta);this.fpsSmooth+= (instantFPS-this.fpsSmooth)*.18;}renderMs=performance.now()-renderAt;}catch(e){this.notify(`Rendering stopped: ${e.message}`);if(this.renderer)this.renderer.ready=false;}this.lastFrame=now;}
  const worker=this.bridge.metrics||{},rendererMetrics=this.renderer?.metrics?.()||{},rt=rendererMetrics.timings||{},gpu=rendererMetrics.gpuTimingsMs||{},workerActive=!gpuSynth;const sample={t:now,fps:this.fpsSmooth,frameMs:1000/Math.max(.1,this.fpsSmooth),frameTotal:performance.now()-frameStart,bridgeTickMs,workerMs:workerActive?(worker.workerMs||0):0,workerGenerateMs:workerActive?(worker.generate||0):0,workerPipelineMs:workerActive?(worker.pipeline||0):0,workerMipMs:workerActive?(worker.mips||0):0,previewDrawMs:this.fallbackActive?(this.previewDrawMs||0):0,moveMs,renderCpuMs:rt.renderCpuMs||renderMs,envUploadMs:rt.environmentUploadMs||0,fillUniformsMs:rt.fillUniformsMs||0,gpuSynthEncodeMs:rt.gpuSynthEncodeMs||0,gpuEnvironmentEncodeMs:rt.gpuEnvironmentEncodeMs||0,...gpu};this.lastFrameProfile=sample;this.profilerHistory.push(sample);if(this.profilerHistory.length>300)this.profilerHistory.shift();this.ui?.updateProfiler?.(this.profilerHistory,s.displayFPS);const rawMod=gpuSynth?(rendererMetrics.modOutput||0):(worker.modOutput||0),smoothA=1-Math.exp(-Math.max(rafDt,1/120)*12);this.smoothedMod+=(rawMod-this.smoothedMod)*smoothA;if(now-this.lastModUI>=100){this.lastModUI=now;this.ui?.updateModulation?.(this.smoothedMod);$('modOutput').textContent=`MOD ${this.smoothedMod.toFixed(2)} · BASE PARAMETERS UNCHANGED`;}
  if(now-this.lastStatus>500){this.fps=this.presented*1000/(now-this.lastStatus);this.presented=0;this.lastStatus=now;const m=this.renderer?.metrics(),mixLabel=s.mixerEnabled?`MIX ${Math.round(s.mixerMix*100)}% HDRI`:s.envMode.toUpperCase();$('status').textContent=this.fallbackActive?`CPU ENVIRONMENT PREVIEW ONLY · ${navigator.gpu?'GPU RENDERER INITIALISATION FAILED':'WEBGPU UNAVAILABLE'} · SKYSYNTH/HDRI CONTROLS REMAIN ACTIVE`:`${this.fps.toFixed(0)} FPS · ${s.sceneMode.toUpperCase()} · ${m?.renderSize?.join(' × ')||'starting'} · ${mixLabel} · SYNTH ${s.sourceWidth}×${s.sourceWidth/2} → MAP ${s.envMapWidth}×${Math.round(s.envMapWidth/2)} @ ${s.generatorFPS} Hz · 0 underwater objects`;}
  if(now-this.lastMetricsUI>=1000){this.lastMetricsUI=now;$('metrics').textContent=JSON.stringify(this.metrics(),null,2);}
 }
 startLook(e){if(e.button!==0)return;this.lookPointer={x:e.clientX,y:e.clientY,id:e.pointerId};$('scene').setPointerCapture(e.pointerId);}
 look(e){if(!this.lookPointer||!this.renderer)return;const dx=e.clientX-this.lookPointer.x,dy=e.clientY-this.lookPointer.y;this.lookPointer.x=e.clientX;this.lookPointer.y=e.clientY;this.renderer.camera.yaw-=dx*.003;this.renderer.camera.pitch=Math.max(-1.4,Math.min(1.4,this.renderer.camera.pitch-dy*.003));}
 stopLook(){this.lookPointer=null;}
 zoom(delta){if(!this.renderer)return;if(this.store.settings.sceneMode==='planet'||this.store.settings.sceneMode==='mesh')this.renderer.camera.orbit=Math.max(160,Math.min(900,this.renderer.camera.orbit*Math.exp(delta*.001)));else this.renderer.camera.position[1]=Math.max(5,Math.min(150,this.renderer.camera.position[1]*Math.exp(delta*.001)));}
 resetCamera(){this.renderer?.resetCamera();this.ui?.clearHeld();}
 capture(){const canvas=$(this.fallbackActive?'fallback':'scene');canvas.toBlob(blob=>{if(blob)download(`Xenofield-${this.store.settings.sceneMode}${this.fallbackActive?'-CPU-preview':''}.png`,blob,'image/png');else this.notify('Screenshot capture failed.');},'image/png');}
 metrics(){return {version:'4.4b',globalStack:this.store.globalStackName,panelPresets:{...this.store.panelSelections},mode:this.store.settings.sceneMode,environmentMode:this.store.settings.envMode,mixerEnabled:this.store.settings.mixerEnabled,asset:this.assetName||null,meshAsset:this.renderer?.meshAssetName||this.meshName||null,meshStats:this.renderer?.meshStats||null,fps:Number(this.fps.toFixed(1)),renderer:this.renderer?.metrics()||{backend:'CPU environment preview only'},generator:this.renderer?.ready?{backend:'GPU SkySynth',workerIdle:true,modOutput:this.renderer.metrics().modOutput,gpuSynth:true}:{frames:this.bridge.frames,pending:this.bridge.busy?1:0,...this.bridge.metrics},profiling:{latest:this.lastFrameProfile,historyLength:this.profilerHistory.length},gpuTimingsMs:this.renderer?.metrics()?.gpuTimingsMs||null,errors:this.errors};}
 dispose(){this.running=false;this.bridge.dispose();this.renderer?.dispose();this.store.dispose();clearTimeout(this.storeTimer);clearTimeout(this.meshRebuildTimer);}
}
if(typeof document!=='undefined'&&document.getElementById('workspace')){const app=new XenofieldApp();app.start().catch(e=>app.notify(e.message));window.addEventListener('beforeunload',()=>app.dispose());}
