import {SceneAuxGPU} from './scene-aux.js';
import {XenoVolumeGPU} from './xenovolume.js';
import {ProceduralCloudGPU} from './procedural-cloud.js';
import {TemporalFieldGPU} from './temporal.js';
import {createCommonLayout,packKinetic,KINETIC_UNIFORM_BYTES} from './common.js';
import {MASK_ROUTE,DEPTH_FX,VOLUME_COMPOSITE,DISTORTION,COLOUR,AA_RESOLVE,DEBUG_VIEW,bloomMaskShader,bloomBlurShader,bloomCompositeShader} from './effects-shaders.js';
import {PROCEDURAL_CLOUD_COMPOSITE} from './procedural-cloud-shaders.js';
import {safePipeline,texture,renderPass} from './gpu-utils.js';
import {hasKineticWork,cameraDiscontinuity} from './quality.js';
import {blueNoiseBytes} from './blue-noise.js';
const TIMING_KEYS=Object.freeze({'SceneAux':'gpuSceneAuxMs','Depth Pyramid':'gpuDepthPyramidMs','Mask Router':'gpuMaskRouterMs','Volume Density':'gpuVolumeDensityMs','Volume Light':'gpuVolumeLightMs','Volume Raymarch':'gpuVolumeRaymarchMs','Volume Composite':'gpuVolumeCompositeMs','Cloud Density':'gpuCloudDensityMs','Cloud Raymarch':'gpuCloudRaymarchMs','Cloud Composite':'gpuCloudCompositeMs','Temporal':'gpuTemporalMs','Depth FX':'gpuDepthFXMs','Distortion':'gpuDistortionMs','Feedback':'gpuFeedbackMs','Positive Bloom':'gpuPositiveBloomMs','Dark Bloom':'gpuDarkBloomMs','Colour LUT':'gpuColourMs','AA Resolve':'gpuAAResolveMs','Debug':'gpuDebugMs'});
export class KineticCompositorGPU{
 constructor(renderer){this.r=renderer;this.d=renderer.device;this.pipelines={};this.errors={};this.time=0;this.historyValid=false;this.blooms={};this.passCounts={};this.previousImageValid=false;this.timing=label=>{this.passCounts[label]=(this.passCounts[label]||0)+1;return this.r.gpuTimestampWrites(TIMING_KEYS[label]||label);};}
 async init(){const d=this.d;this.layout=createCommonLayout(d);this.buffer=d.createBuffer({label:'kinetic controls',size:KINETIC_UNIFORM_BYTES,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.sampler=d.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear'});
 this.black=texture(d,'neutral kinetic black',1,1);this.white=texture(d,'neutral kinetic white',1,1);this.far=texture(d,'neutral far depth',1,1,'r32float');d.queue.writeTexture({texture:this.black},new Uint16Array([0,0,0,0]),{bytesPerRow:8},[1,1]);d.queue.writeTexture({texture:this.white},new Uint16Array([15360,15360,15360,15360]),{bytesPerRow:8},[1,1]);d.queue.writeTexture({texture:this.far},new Float32Array([20000]),{bytesPerRow:4},[1,1]);this.noise=d.createTexture({label:'64² toroidal void-ranked blue noise',size:[64,64],format:'r8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});d.queue.writeTexture({texture:this.noise},blueNoiseBytes(),{bytesPerRow:64},[64,64]);
 const stages={mask:MASK_ROUTE,depth:DEPTH_FX,volume:VOLUME_COMPOSITE,cloud:PROCEDURAL_CLOUD_COMPOSITE,distortion:DISTORTION,colour:COLOUR,aa:AA_RESOLVE,debug:DEBUG_VIEW,positiveMask:bloomMaskShader(false),positiveH:bloomBlurShader(false,false),positiveV:bloomBlurShader(false,true),positiveCompose:bloomCompositeShader(false),darkMask:bloomMaskShader(true),darkH:bloomBlurShader(true,false),darkV:bloomBlurShader(true,true),darkCompose:bloomCompositeShader(true)};
 for(const [name,shader] of Object.entries(stages)){try{this.pipelines[name]=await safePipeline(d,`Kinetic ${name}`,shader,'main',['rgba16float'],d.createPipelineLayout({bindGroupLayouts:[this.layout]}));}catch(e){this.fail(name,e);}}
 for(const [name,Class] of [['aux',SceneAuxGPU],['temporal',TemporalFieldGPU],['volume',XenoVolumeGPU],['cloud',ProceduralCloudGPU]]){try{const instance=new Class(name==='aux'?this.r:this);this[name]=instance;await instance.init();}catch(e){this[name]?.dispose?.();this[name]=null;this.fail(name,e);}}
 this.ready=true;
 }
 fail(name,error){this.errors[name]=error?.message||String(error);this.r.onError(`V4.4b ${name} disabled; base scene retained: ${this.errors[name]}`);}
 resources(overrides={}){return {image:this.r.hdr||this.black,depth:this.auxActive?this.aux.depth:this.far,aux:this.auxActive?this.aux.surface:this.black,volume:this.volumeResult||this.black,signals:this.volumeActive?this.volume.signals:this.black,history:this.temporal?.current('scene')||(this.previousImageValid?this.previousImage:null)||this.black,historyDepth:this.temporal?.tracks.get('scene')?.depth||this.far,feedback:this.temporal?.current('feedback')||this.black,atlas:this.r.detail,environment:this.r.plasmaEnvironment,lut:this.r.lutTexture,noise:this.noise,pyramid:this.pyramidActive?this.aux.pyramid:(this.auxActive?this.aux.depth:this.far),extra:this.black,router:this.preMask||this.white,hdri:this.r.hdriEnvironment||this.black,...overrides};}
 group(overrides={}){const q=this.resources(overrides),keys=['image','depth','aux','volume','signals','history','historyDepth','feedback','atlas','environment','lut','noise','pyramid','extra','router','hdri'];return this.d.createBindGroup({layout:this.layout,entries:[{binding:0,resource:{buffer:q.buffer||this.buffer}},{binding:1,resource:this.sampler},...keys.map((key,i)=>({binding:i+2,resource:q[key].createView()}))]});}
 prepare(s,dt){this.settings=s;this.passCounts={};if(!s.paused)this.time+=Math.max(0,Math.min(dt,.1));const r=this.r,w=r.width,h=r.height;
 const sizeKey=[w,h,r.outputWidth,r.outputHeight,r.sampleCount].join(':');if(sizeKey!==this.sizeKey){this.releaseScreen();this.sizeKey=sizeKey;this.historyValid=false;this.temporal?.reset(null,'resize / quality allocation');}
 const state={mode:s.sceneMode,position:Array.from(r.uniforms.subarray(16,19)),forward:Array.from(r.uniforms.subarray(28,31)),orbit:r.camera.orbit};
 const semantic=[s.sceneMode,s.volumeSpace,s.volumeResolution,s.volumeRenderScale,s.volumeSource,s.volumeSourceB,s.temporalSamples,s.jitterPattern,s.volumeEnabled,s.procCloudEnabled,s.feedbackEnabled,s.projectionA,s.projectionB,s.meshAsset,s.depthEnabled,s.distortionEnabled].join('|');
 if(cameraDiscontinuity(this.cameraState,state)||semantic!==this.semantic||(s.sceneMode==='mesh'&&this.geometry!==r.customMesh)){this.temporal?.reset(null,'camera / mode / sampling discontinuity');this.historyValid=false;this.previousImageValid=false;}this.cameraState=state;this.semantic=semantic;this.geometry=r.customMesh;
 this.active=hasKineticWork(s);if(!this.active&&this.wasActive){this.releaseScreen();this.aux?.disposeTargets();for(const name of ['scene','volume','feedback'])this.temporal?.release(name);}this.wasActive=this.active;this.auxActive=!!(this.active&&this.aux?.ready);if(this.auxActive)this.aux.ensure(w,h,s);
 this.volumeActive=!!(s.volumeEnabled&&this.volume?.ready&&this.auxActive);if(this.volumeActive){const priorRaw=this.volume.raw;this.volume.ensure(w,h,s);if(priorRaw!==this.volume.raw)this.volumeResult=null;this.volume.prepare(s,this.time);}else if(this.volume?.n){this.volume.release();this.temporal?.release('volume');this.volumeResult=null;}
 this.cloudActive=!!(s.procCloudEnabled&&this.cloud?.ready&&this.auxActive);if(this.cloudActive){this.cloud.ensure(w,h,s);this.cloud.prepare(s,this.time,r.frames);}else if(this.cloud?.n)this.cloud.release();
 const usesNew=v=>/^(scene-|inverse-|depth-|normal-|surface-|volume-|history-|feedback|silhouette)/.test(v);
 this.needSceneMask=!!(s.maskEnabled&&[s.maskSourceA,s.maskSourceB].some(usesNew));this.needPreMask=this.needSceneMask||(this.volumeActive&&s.volumeUseMask);
 if(this.needPreMask&&!this.preMask){this.preMask=texture(this.d,'shared current depth / prior volume mask',w,h);r.rebuildSceneGroup();}else if(!this.needPreMask&&this.preMask){r.retire([this.preMask]);this.preMask=null;r.rebuildSceneGroup();}
 const activeMasks=[...(s.maskEnabled?[s.maskSourceA,s.maskSourceB]:[]),s.volumeEnabled?s.volumeMask:null,s.depthEnabled?s.depthMask:null,s.distortionEnabled?s.distortionMask:null,s.feedbackEnabled?s.feedbackMask:null,s.positiveEnabled?s.positiveMask:null,s.darkEnabled?s.darkMask:null,s.colourEnabled?s.colourMask:null];
 this.pyramidActive=!!(this.auxActive&&this.aux.reduce&&s.depthPyramidEnabled&&(s.depthEnabled||s.darkEnabled||s.kineticDebug==='depth-pyramid'||activeMasks.includes('silhouette')));
 if(!s.temporalEnabled&&s.temporalSamples==='off')this.temporal?.release('scene');if(!s.feedbackEnabled)this.temporal?.release('feedback');if(!s.volumeTemporal){this.volumeResult=this.volumeActive?this.volume.raw:null;this.temporal?.release('volume');}
 this.needPriorImage=[...(s.maskEnabled?[s.maskSourceA,s.maskSourceB]:[]),s.volumeEnabled?s.volumeMask:null,s.depthEnabled?s.depthMask:null,s.distortionEnabled?s.distortionMask:null,s.feedbackEnabled?s.feedbackMask:null,s.positiveEnabled?s.positiveMask:null,s.darkEnabled?s.darkMask:null,s.colourEnabled?s.colourMask:null,s.distortionEnabled?s.distortionSource:null].some(v=>v?.startsWith('history'));
 if(this.needPriorImage&&!this.previousImage)this.previousImage=texture(this.d,'prior scene for general history masks',w,h);if(!this.needPriorImage&&this.previousImage){r.retire([this.previousImage]);this.previousImage=null;this.previousImageValid=false;}
 if(this.active&&!this.ping)this.ping=[texture(this.d,'compositor scratch A',w,h),texture(this.d,'compositor scratch B',w,h)];
 for(const kind of ['positive','dark'])if(!s[`${kind}Enabled`]&&this.blooms[kind]){r.retire(this.blooms[kind].textures);delete this.blooms[kind];}
 if((w!==r.outputWidth||h!==r.outputHeight)&&!this.resolved)this.resolved=texture(this.d,'high-quality presentation resolve',r.outputWidth,r.outputHeight);
 this.params=packKinetic(s,r,this,dt);this.params[47*4+3]=this.pyramidActive?this.aux.mipCount:1;this.params[46*4+1]=Math.min(s.debugMip,this.params[47*4+3]-1);this.d.queue.writeBuffer(this.buffer,0,this.params);
 }
 beforeScene(encoder,s){if(!this.auxActive)return;this.aux.encode(encoder,s,this.timing);if(this.pyramidActive)this.aux.encodePyramid(encoder,this.timing,true);if(this.needPreMask&&this.pipelines.mask){const group=this.group({image:this.previousImageValid?this.previousImage:this.black,volume:this.volumeResult||this.black,router:this.white});renderPass(encoder,this.pipelines.mask,group,[this.preMask],'Mask Router',this.timing);}}
 next(input){return this.ping[0]===input?this.ping[1]:this.ping[0];}
 run(encoder,key,input,label,extra={}){const pipeline=this.pipelines[key];if(!pipeline)return input;const out=this.next(input);renderPass(encoder,pipeline,this.group({image:input,...extra}),[out],label,this.timing);return out;}
 bloom(encoder,kind,input,s){if(!['Mask','H','V','Compose'].every(k=>this.pipelines[kind+k]))return input;const w=Math.max(1,Math.ceil(this.r.width/+s.bloomResolution)),h=Math.max(1,Math.ceil(this.r.height/+s.bloomResolution));let b=this.blooms[kind];if(!b||b.width!==w||b.height!==h){if(b)this.r.retire(b.textures);b={width:w,height:h,textures:[texture(this.d,`${kind} bloom mask`,w,h),texture(this.d,`${kind} bloom horizontal`,w,h),texture(this.d,`${kind} bloom vertical`,w,h)]};this.blooms[kind]=b;}
 const label=kind==='dark'?'Dark Bloom':'Positive Bloom';renderPass(encoder,this.pipelines[kind+'Mask'],this.group({image:input}),[b.textures[0]],label,this.timing);renderPass(encoder,this.pipelines[kind+'H'],this.group({image:b.textures[0]}),[b.textures[1]],label,this.timing);renderPass(encoder,this.pipelines[kind+'V'],this.group({image:b.textures[1]}),[b.textures[2]],label,this.timing);return this.run(encoder,kind+'Compose',input,label,{extra:b.textures[2]});}
 afterScene(encoder,s){let current=this.r.hdr;this.volumeResult=this.volumeActive?this.volume.raw:null;
 if(this.volumeActive){this.volume.encodeCache(encoder,s,this.timing);this.volumeResult=this.volume.encodeRay(encoder,this.resources({volume:this.black,signals:this.black,extra:this.far}),this.timing);if(s.volumeTemporal&&this.temporal?.ready)this.volumeResult=this.temporal.resolve(encoder,'volume',this.volumeResult,this.volume.depth,this.volume.width,this.volume.height,this.resources(),s,this.timing);}
 let cloudResult=null;if(this.cloudActive){this.cloud.encodeCache(encoder,this.timing);cloudResult=this.cloud.encodeRay(encoder,this.aux.depth,this.timing);}
 if(this.active&&this.auxActive){if(s.depthEnabled)current=this.run(encoder,'depth',current,'Depth FX');if(this.volumeActive)current=this.run(encoder,'volume',current,'Volume Composite',{extra:this.volume.depth});if(this.cloudActive&&cloudResult)current=this.run(encoder,'cloud',current,'Cloud Composite',{volume:cloudResult});if(s.distortionEnabled)current=this.run(encoder,'distortion',current,'Distortion');
 // Conservative scene history is resolved BEFORE destructive feedback and signed grading.
 if((s.temporalEnabled||s.temporalSamples!=='off')&&this.temporal?.ready)current=this.temporal.resolve(encoder,'scene',current,this.aux.depth,this.r.width,this.r.height,this.resources(),s,this.timing);
 if(s.feedbackEnabled&&this.temporal?.ready){const feedback=this.temporal.feedback(encoder,current,this.aux.depth,this.r.width,this.r.height,this.resources(),s,this.timing),out=this.next(current);renderPass(encoder,this.temporal.feedbackComposite,this.group({image:current,feedback}),[out],'Feedback',this.timing);current=out;}
 if(s.positiveEnabled)current=this.bloom(encoder,'positive',current,s);if(s.darkEnabled)current=this.bloom(encoder,'dark',current,s);if(s.colourEnabled)current=this.run(encoder,'colour',current,'Colour LUT');
 if(s.kineticDebug!=='final'){let extra=this.black;if(s.kineticDebug==='positive-bloom')extra=this.blooms.positive?.textures[0]||this.black;if(s.kineticDebug==='dark-bloom')extra=this.blooms.dark?.textures[0]||this.black;current=this.run(encoder,'debug',current,'Debug',{volume:this.volumeActive?this.volume.raw:this.black,extra});}}
 if(this.resolved&&this.pipelines.aa){renderPass(encoder,this.pipelines.aa,this.group({image:current}),[this.resolved],'AA Resolve',this.timing);current=this.resolved;}
 if(this.needPriorImage&&this.previousImage){encoder.copyTextureToTexture({texture:this.r.hdr},{texture:this.previousImage},[this.r.width,this.r.height]);this.previousImageValid=true;}
 this.previousVP=new Float32Array(this.r.uniforms.subarray(0,16));this.previousCamera=Array.from(this.r.uniforms.subarray(16,19));this.previousJitter=[...(this.r.frameJitter||[0,0])];this.historyValid=true;return current;
 }
 releaseScreen(){this.r.retire([...(this.ping||[]),this.preMask,this.resolved,this.previousImage,...Object.values(this.blooms).flatMap(v=>v.textures)]);this.ping=null;this.preMask=null;this.resolved=null;this.previousImage=null;this.previousImageValid=false;this.blooms={};this.volumeResult=null;this.temporal?.reset(null,'resource generation changed');this.r.rebuildSceneGroup();}
 metrics(){return {active:this.active,passes:{...this.passCounts},timingActivity:Object.fromEntries(Object.entries(TIMING_KEYS).map(([label,key])=>[key,this.passCounts[label]||0])),errors:{...this.errors},volume:this.volume?.metrics()||null,proceduralCloud:this.cloud?.metrics()||null,historyResets:this.temporal?.resetCount||0,lastHistoryReset:this.temporal?.lastReset,historyTracks:Object.fromEntries([...(this.temporal?.tracks||[])].map(([key,t])=>[key,{size:[t.width,t.height],age:t.age,valid:t.valid}])),maskLatency:'Current depth/normal; previous-frame volume/history in scene materials. Current volume/history in compositor.',depthPyramidLevels:this.pyramidActive?this.aux?.mipCount:0};}
 dispose(){this.releaseScreen();this.aux?.dispose();this.volume?.dispose();this.cloud?.dispose();this.temporal?.dispose();this.r.retire([this.black,this.white,this.far,this.noise,this.buffer]);this.ready=false;}
}
