import {PROCEDURAL_CLOUD_DENSITY,PROCEDURAL_CLOUD_RAY} from './procedural-cloud-shaders.js';
import {safePipeline,texture,computePass} from './gpu-utils.js';
import {KINETIC_UNIFORM_BYTES} from './common.js';
import {effectiveCloudCacheResolution} from './quality.js';

export class ProceduralCloudGPU{
 constructor(graph){this.g=graph;this.r=graph.r;this.d=graph.d;this.ready=false;this.current=0;this.cacheTextures=[];this.screenTextures=[];this.first=true;this.generations=0;this.blend=1;this.frameSinceUpdate=0;}
 async init(){const d=this.d;this.densityPipeline=await safePipeline(d,'Procedural Cloud Density',PROCEDURAL_CLOUD_DENSITY,'main',[],'auto',true);this.sampler=d.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear'});this.cacheLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,texture:{viewDimension:'3d'}},{binding:2,visibility:GPUShaderStage.FRAGMENT,texture:{viewDimension:'3d'}}]});this.sceneLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform',minBindingSize:KINETIC_UNIFORM_BYTES}},{binding:1,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'unfilterable-float'}}]});this.rayPipeline=await safePipeline(d,'Procedural Cloud Raymarch',PROCEDURAL_CLOUD_RAY,'main',['rgba16float'],d.createPipelineLayout({bindGroupLayouts:[this.sceneLayout,this.cacheLayout]}));this.ready=true;}
 view(t){return t.createView({dimension:'3d'});}
 ensure(w,h,s){const requested=Math.max(16,Math.round(+s.procCloudCacheRes||96)),n=effectiveCloudCacheResolution(s);this.requestedN=requested;if(n!==this.n){this.r.retire(this.cacheTextures);this.n=n;this.cacheTextures=Array.from({length:2},(_,i)=>this.d.createTexture({label:`Procedural cloud density generation ${i} ${n}³`,size:[n,n,n],dimension:'3d',format:'rgba16float',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST}));this.current=0;this.first=true;this.generations=0;this.signature=null;this.frameSinceUpdate=0;}
  const divider=Math.max(1,+s.procCloudRenderScale||1),width=Math.max(1,Math.ceil(w/divider)),height=Math.max(1,Math.ceil(h/divider));if(width!==this.width||height!==this.height){this.r.retire(this.screenTextures);this.width=width;this.height=height;this.raw=texture(this.d,'procedural cloud radiance / alpha',width,height);this.screenTextures=[this.raw];}
 }
 prepare(s,time,frame){const keys=['procCloudDensity','procCloudCoverage','procCloudScale','procCloudAltitude','procCloudDetail','procCloudWindSpeed','procCloudHeight'];const sig=keys.map(k=>`${k}:${s[k]}`).join('|');const changed=sig!==this.signature;this.signature=sig;const rate=Math.max(1,+s.procCloudCacheUpdate||1);const cadenceChanged=rate!==this.cadence;this.cadence=rate;const cadenceDue=this.lastFrame===undefined||frame-this.lastFrame>=rate;this.densityDue=this.first||changed||cadenceChanged||(!s.paused&&cadenceDue);if(this.densityDue){if(!this.first)this.current=1-this.current;this.lastFrame=frame;this.frameSinceUpdate=0;this.generations++;}else this.frameSinceUpdate=Math.max(0,frame-(this.lastFrame??frame));let linear=this.first?1:Math.min(1,(this.frameSinceUpdate+1)/rate);if(s.procCloudCacheSmooth>0)linear=Math.pow(linear,1/(1+s.procCloudCacheSmooth*4));this.blend=linear;this.cloudTime=time*s.procCloudWindSpeed;}
 encodeCache(encoder,timing){if(!this.densityDue)return;const cur=this.cacheTextures[this.current];const group=this.d.createBindGroup({layout:this.densityPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.g.buffer}},{binding:1,resource:this.view(cur)}]});computePass(encoder,this.densityPipeline,group,this.n,'Cloud Density',timing);if(this.first){encoder.copyTextureToTexture({texture:cur},{texture:this.cacheTextures[1-this.current]},[this.n,this.n,this.n]);this.first=false;this.blend=1;}}
 encodeRay(encoder,depth,timing){const desc={label:'Procedural Cloud Raymarch',colorAttachments:[{view:this.raw.createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:0}}]};const tw=timing('Cloud Raymarch');if(tw)desc.timestampWrites=tw;const scene=this.d.createBindGroup({layout:this.sceneLayout,entries:[{binding:0,resource:{buffer:this.g.buffer}},{binding:1,resource:depth.createView()}]});const caches=this.d.createBindGroup({layout:this.cacheLayout,entries:[{binding:0,resource:this.sampler},{binding:1,resource:this.view(this.cacheTextures[1-this.current])},{binding:2,resource:this.view(this.cacheTextures[this.current])}]});const p=encoder.beginRenderPass(desc);p.setPipeline(this.rayPipeline);p.setBindGroup(0,scene);p.setBindGroup(1,caches);p.draw(3);p.end();return this.raw;}
 metrics(){return {cache:this.n?[this.n,this.n,this.n]:null,requestedCache:this.requestedN||0,cacheLimited:!!this.n&&this.n!==(this.requestedN||this.n),framebuffer:[this.width||0,this.height||0],generations:this.generations,interpolation:this.blend,cacheBytes:this.n?this.n**3*8*2:0,worldCenter:this.g.settings?[this.g.settings.procCloudCenterX,this.g.settings.procCloudCenterY,this.g.settings.procCloudCenterZ]:null,worldSize:this.g.settings?[this.g.settings.procCloudSizeX,this.g.settings.procCloudSizeY,this.g.settings.procCloudSizeZ]:null};}
 release(){this.r.retire([...this.cacheTextures,...this.screenTextures]);this.cacheTextures=[];this.screenTextures=[];this.raw=null;this.n=0;this.width=0;this.height=0;this.signature=null;this.lastFrame=undefined;this.first=true;this.blend=1;}
 dispose(){this.release();this.ready=false;}
}
