import {densityShader,lightShader,volumeMipShader,VOLUME_RAY} from './volume-shaders.js';
import {safePipeline,texture,computePass} from './gpu-utils.js';
export class XenoVolumeGPU{
 constructor(graph){this.g=graph;this.r=graph.r;this.d=graph.d;this.ready=false;this.current=0;this.cacheTextures=[];this.screenTextures=[];this.generations=0;this.lightingUpdates=0;this.nextDensity=-1;this.nextLight=-1;this.blend=1;}
 async init(formats=['rgba8unorm','rgba16float']){const d=this.d;let last;for(const format of formats){try{this.densityPipeline=await safePipeline(d,`Volume Density ${format}`,densityShader(format),'main',[], 'auto',true);this.lightPipeline=await safePipeline(d,`Volume Light ${format}`,lightShader(format),'main',[],'auto',true);this.mipPipeline=await safePipeline(d,`Volume mips ${format}`,volumeMipShader(format),'main',[],'auto',true);this.format=format;last=null;break;}catch(e){last=e;}}if(last)throw last;
 this.sampler=d.createSampler({magFilter:'linear',minFilter:'linear',mipmapFilter:'linear'});this.cacheLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}},...[1,2].map(binding=>({binding,visibility:GPUShaderStage.FRAGMENT,texture:{viewDimension:'3d'}}))]});
 this.raySceneLayout=d.createBindGroupLayout({label:'raymarch minimal scene inputs',entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform',minBindingSize:1280}},{binding:1,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}},...[3,4,11,13,17].map(binding=>({binding,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:binding===3?'unfilterable-float':'float'}}))]});
 this.rayPipeline=await safePipeline(d,'Volume Raymarch',VOLUME_RAY,'main',['rgba16float','rgba16float','r32float'],d.createPipelineLayout({bindGroupLayouts:[this.raySceneLayout,this.cacheLayout]}));this.ready=true;}
 ensure(w,h,s){const n=+s.volumeResolution;if(n!==this.n){this.r.retire(this.cacheTextures);this.n=n;this.mips=Math.floor(Math.log2(n))+1;this.cacheTextures=Array.from({length:3},(_,i)=>this.d.createTexture({label:`XenoVolume ${i===2?'lighting scratch':`generation ${i}`} ${n}³ ${this.format}`,size:[n,n,n],dimension:'3d',format:this.format,mipLevelCount:this.mips,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST}));this.caches=this.cacheTextures.slice(0,2);this.scratch=this.cacheTextures[2];this.current=0;this.first=true;this.nextDensity=-1;this.nextLight=-1;this.g.temporal?.reset('volume');}
 const width=Math.max(1,Math.ceil(w/+s.volumeRenderScale)),height=Math.max(1,Math.ceil(h/+s.volumeRenderScale));if(width!==this.width||height!==this.height){this.r.retire(this.screenTextures);this.width=width;this.height=height;this.raw=texture(this.d,'sparse volume radiance / opacity',width,height);this.signals=texture(this.d,'volume density / light / structure / emission',width,height);this.depth=texture(this.d,'volume opacity-weighted ray distance',width,height,'r32float');this.screenTextures=[this.raw,this.signals,this.depth];this.g.temporal?.reset('volume');}
 }
 prepare(s,time){const keys=Object.keys(s).filter(key=>/^volume(Source|Generator|Shape|Density$|Coverage|Threshold|Softness|Scale$|Detail$|Warp|Power|Quantize|Posterize|Invert|Phase$|UseMask)/.test(key)||/^projection|^projector|^noixture/.test(key));const signature=keys.map(key=>`${key}:${s[key]}`).join('|');const changed=signature!==this.signature;this.signature=signature;
 const densityRateChanged=this.densityRate!==s.volumeDensityFPS;const lightRateChanged=this.lightRate!==s.volumeLightFPS;this.densityRate=s.volumeDensityFPS;this.lightRate=s.volumeLightFPS;
 this.densityDue=this.first||changed||densityRateChanged||time>=this.nextDensity;
 const lightSignature=[s.volumeLighting,s.volumeLightSteps,s.volumeAttenuation,...this.r.uniforms.subarray(136,139)].join('|');const lightChanged=lightSignature!==this.lightSignature;this.lightSignature=lightSignature;
 this.lightDue=this.first||changed||lightChanged||lightRateChanged||time>=this.nextLight;
 this.mipsDue=s.volumeLighting==='mip-shadow'&&(this.densityDue||this.first||lightChanged);
 if(this.densityDue){if(!this.first)this.current=1-this.current;this.lastDensity=time;this.nextDensity=time+1/s.volumeDensityFPS;this.generations++;}
 if(this.lightDue){this.nextLight=time+1/s.volumeLightFPS;this.lightingUpdates++;}
 this.blend=this.first?1:Math.min(1,Math.max(0,(time-this.lastDensity)*s.volumeDensityFPS));
 }
 view(t,mip=undefined){return t.createView({dimension:'3d',...(mip===undefined?{}:{baseMipLevel:mip,mipLevelCount:1})});}
 group(pipeline,entries){return this.d.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:entries.map((resource,binding)=>({binding,resource}))});}
 encodeCache(encoder,s,timing){const cur=this.caches[this.current],old=this.caches[1-this.current],g=this.g;
 if(this.densityDue){const group=this.group(this.densityPipeline,[{buffer:g.buffer},this.sampler,this.view(old),this.view(cur,0),this.r.detail.createView(),this.r.plasmaEnvironment.createView(),(g.preMask||g.white).createView(),{buffer:this.r.ocean.cascades[0].state}]);computePass(encoder,this.densityPipeline,group,this.n,'Volume Density',timing);}
 if(this.mipsDue){for(let mip=1;mip<this.mips;mip++){const group=this.group(this.mipPipeline,[this.view(cur,mip-1),this.view(cur,mip)]);computePass(encoder,this.mipPipeline,group,Math.max(1,this.n>>mip),'Volume Density',timing);}}
 if(this.lightDue){const group=this.group(this.lightPipeline,[{buffer:g.buffer},this.sampler,this.view(cur),this.view(this.scratch,0)]);computePass(encoder,this.lightPipeline,group,this.n,'Volume Light',timing);encoder.copyTextureToTexture({texture:this.scratch},{texture:cur},[this.n,this.n,this.n]);}
 if(this.first){encoder.copyTextureToTexture({texture:cur},{texture:old},[this.n,this.n,this.n]);this.first=false;}
 }
 encodeRay(encoder,resources,timing){const desc={label:'Volume Raymarch',colorAttachments:[this.raw,this.signals,this.depth].map(t=>({view:t.createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:0}}))};const tw=timing('Volume Raymarch');if(tw)desc.timestampWrites=tw;
 const group=this.d.createBindGroup({layout:this.cacheLayout,entries:[{binding:0,resource:this.sampler},{binding:1,resource:this.view(this.caches[1-this.current])},{binding:2,resource:this.view(this.caches[this.current])}]});const p=encoder.beginRenderPass(desc);p.setPipeline(this.rayPipeline);p.setBindGroup(0,this.d.createBindGroup({layout:this.raySceneLayout,entries:[{binding:0,resource:{buffer:this.g.buffer}},{binding:1,resource:this.g.sampler},{binding:3,resource:resources.depth.createView()},{binding:4,resource:resources.aux.createView()},{binding:11,resource:resources.environment.createView()},{binding:13,resource:resources.noise.createView()},{binding:17,resource:resources.hdri.createView()}]}));p.setBindGroup(1,group);p.draw(3);p.end();return this.raw;}
 metrics(){return {format:this.format,cache:this.n?[this.n,this.n,this.n]:null,framebuffer:[this.width||0,this.height||0],generations:this.generations,lightingUpdates:this.lightingUpdates,interpolation:this.blend,cacheBytes:this.n?Math.ceil(this.n**3*(this.format==='rgba8unorm'?4:8)*3*8/7):0};}
 release(){this.r.retire([...this.cacheTextures,...this.screenTextures]);this.cacheTextures=[];this.screenTextures=[];this.caches=null;this.raw=null;this.signals=null;this.depth=null;this.n=0;this.width=0;this.height=0;this.signature=null;this.lightSignature=null;this.first=true;}
 dispose(){this.release();this.ready=false;}
}
